### PR TITLE
Switch to using string-based formatting for time elapsed

### PR DESCRIPTION
**Pull request by cdrage**
This PR:
  - Uses string based formatting for the time
  - No longer uses "%v" with time.Duration, so there are no
  false-positives when displaying the time

Closes https://github.com/openshift/odo/issues/1811

### CODE REVIEW

**Comment by cdrage** [comment]
Just waiting to see if tests are green / there's no errors in CI :)

/hold

**Comment by cdrage** [comment]
> Everything seems to be 0ms https://travis-ci.com/openshift/odo/jobs/208179822#L823
> 
> ```
> Validation
> •  Validating component  ...
> ✓  Validating component [0ms]
> •  Checking component  ...
> ✓  Checking component [0ms]
> Configuration changes
> •  Creating component  ...
> ✓  Initializing component
> •  Triggering build from git  ...
> ✓  Triggering build from git [0ms]
> •  Waiting for build to finish  ...
> ✓  Waiting for build to finish [0ms]
> •  Deploying component testcmp  ...
> ✓  Deploying component testcmp [0ms]
> ✓  Creating component [0ms]
> •  Applying configuration  ...
> ✓  Applying configuration [0ms]
> Running odo with args: [url create myurl --port 8080] 
> ✓  URL myurl created  
> Run `odo push` to apply URL: myurl
> ```
> 
> Even on my local machine, actual time is around 20s but it shows 0ms
> 
> Also it's showing wrong time in some cases.
> 
> ```
> [mrinaldas@localhost odo]$ odo project delete hiziertwcw -f
>  ✓  Deleting project hiziertwcw [58m]
> Deleted project : hiziertwcw
> ```
> 
> The actual time was around 6s but it shows 58 minutes.

This is so strange and honestly I can't find where in the world it's causing this... It seems as though each time it's within a testing suite `time.Now()` and parsing isn't working correctly..

I'll try to investigate this further, but honestly, it's getting to the point where I should just close the PR hah.

**Comment by mik-dass** [comment]
@cdrage Still giving wrong values https://travis-ci.com/openshift/odo/jobs/208596892#L759

**Comment by cdrage** [comment]
/hold cancel

@mik-dass @surajnarwade @girishramnani another review? :)

**Comment by mik-dass** [comment]
> @mik-dass @surajnarwade @girishramnani another review? :)

Already lgtm from my side

**Comment by kadel** [comment]
> /lgtm
> Works for me locally even with the verbose flag and
> Also CI is reporting correct values and code lgtm

this pr was already `/lgtm`ed,  you should have used `/approve`

**Pull request merged**
