### PR TITLE
Various e2e fixes for OpenShiftCI

### PR DESCRIPTION
**Pull request by kadel**
fixing e2e tests on OpenShift CI - what was left from #1360

### CODE REVIEW

**Comment by kadel** [comment]
/test e2e-core

timeouts :-(

**Comment by kadel** [comment]
aws error
/test e2e-core

**Comment by kadel** [comment]
again

```
level=warning msg="Found override for ReleaseImage. Please be warned, this is not advised"
level=info msg="Consuming \"Install Config\" from target directory"
level=info msg="Creating infrastructure resources..."
level=error
level=error msg="Error: Error applying plan:"
level=error
level=error msg="4 errors occurred:"
level=error msg="\t* module.vpc.aws_route.igw_route: 1 error occurred:"
level=error msg="\t* aws_route.igw_route: Error creating route: timeout while waiting for state to become 'success' (timeout: 2m0s)"
level=error
level=error
level=error msg="\t* module.vpc.aws_route_table_association.route_net[1]: 1 error occurred:"
level=error msg="\t* aws_route_table_association.route_net.1: timeout while waiting for state to become 'success' (timeout: 5m0s)"
level=error
level=error
level=error msg="\t* module.vpc.aws_route.to_nat_gw[5]: 1 error occurred:"
level=error msg="\t* aws_route.to_nat_gw.5: Error creating route: timeout while waiting for state to become 'success' (timeout: 2m0s)"
level=error
level=error
level=error msg="\t* module.vpc.aws_route_table_association.private_routing[4]: 1 error occurred:"
level=error msg="\t* aws_route_table_association.private_routing.4: timeout while waiting for state to become 'success' (timeout: 5m0s)"
level=error
level=error
level=error
level=error
level=error
level=error msg="Terraform does not automatically rollback in the face of errors."
level=error msg="Instead, your Terraform state file has been partially updated with"
level=error msg="any resources that successfully completed. Please address the error"
level=error msg="above and apply again to incrementally change your infrastructure."
level=error
level=error
level=fatal msg="failed to fetch Cluster: failed to generate asset \"Cluster\": failed to create cluster: failed to apply using Terraform"
```

/test e2e-core

**Comment by kadel** [comment]
timeout


/test e2e-core

**Comment by kadel** [comment]
🎉 e2e passing on openshiftCI and Travis
/cc @amitkrout @mohammedzee1000 @anmolbabu 

/hold cancel

**Comment by amitkrout** [comment]
Awesome!!! 
Running the test again just to make sure changes are stable enough 

/retest

**Comment by amitkrout** [comment]
#1470

**Pull request merged**
