### PR TITLE
Fixed issues identified by golangci-lint and added linter to make validate

### LINKED ISSUE #1927: golangci-lint reports dead code, missing error checks and other issues.
golangci-lint is a meta-linter that runs a bunch of other linting tools (lint, vet etc.) very quickly.
With default settings it catches a lot of real problems and very few false ones.
I recommend we included it in the odo build vaildation.

## Actual behavior

In root of odo repo:
```
go get github.com/golangci/golangci-lint/cmd/golangci-lint
golangci-lint run ./...
```
Prints a lot of  issues

## Expected behavior

No issues.

## Any logs, error output, etc?

[lint.txt](https://github.com/openshift/odo/files/3412381/lint.txt)

### PR DESCRIPTION
**Pull request by alanconway**
Fixes issues identified by golangci-lint, and adds that linter to 
the Makefile goget-tools and validate.

These static analysis tools turn up a lot of real bugs, and not a lot
of false ones. It is well worth while making the effort to write clean
code in order to get advance warning of bugs.

## Was the change discussed in an issue?

Fixes #1927

## How to test changes?

The behavior of odo should not have changed - all tests should pass as before.

`make lint` should list no issues.

### CODE REVIEW

**Comment by alanconway** [comment]
/retest
If the retest fails I'll look into it - possible one of the changes introduced a bug.

**Comment by alanconway** [comment]
The same commit for this PR has both passed and failed on all the failing tests on different runs
https://openshift-gce-devel.appspot.com/pr/openshift_odo/1928

Where can I  see the test results for CI on branch master to compare and get an idea if these are test flakes on master or regressions in this PR? I can't get a clean test run on master on my own repo but that might be environmental problems on my end.

**Comment by cdrage** [comment]
@alanconway CI is failing right now since they're having cluster-wide issues at the moment :(. So just have to wait and see.

**Comment by amitkrout** [comment]
@alanconway I have reduced the no of test node to 2 in one of my pr which will helps to avoid the occurrence of test flake. cc_ @cdrage 

Please rebase it

**Comment by alanconway** [comment]
> @alanconway I have reduced the number of test node to `2` in one of my pr #1875 which will helps to avoid such occurrence of test flake. cc_ @cdrage
> 
> Please rebase it

Done.

**Comment by amitkrout** [comment]
@alanconway 
```
golangci-lint run ./...
pkg/util/fileIndexer.go:151:12: ineffectual assignment to `err` (ineffassign)
	jsonData, err := json.Marshal(writeMap)
	          ^
tests/integration/component.go:498:12: Error return value of `os.Mkdir` is not checked (errcheck)
			os.Mkdir(context, 0755)
			        ^
pkg/odo/cli/component/common_push.go:155:38: SA1024: cutset contains duplicate characters (staticcheck)
		cpo.componentContext = strings.Trim(filepath.Dir(cpo.localConfigInfo.Filename), ".odo")
		                                   ^
pkg/util/fileIndexer.go:129:16: S1005: should omit value from range; this loop is equivalent to `for fileName := range ...` (gosimple)
	for fileName, _ := range readData {
	              ^
make: *** [lint] Error 1
```
Can you please fix those errors
Details log - https://travis-ci.com/openshift/odo/jobs/220638299

**Comment by amitkrout** [comment]
```
 Checking http://uberjaropenjdk-app-xaorupsjwh.apps.ci-op-vr5j92m1-f09f4.origin-ci-int-aws.dev.rhcloud.com, for HTTP Booster
try 0 of 90 
[...]
```
Could not ping the url within 90 tries
/test integration

**Comment by amitkrout** [comment]
> @alanconway
> 
> ```
> golangci-lint run ./...
> pkg/util/fileIndexer.go:151:12: ineffectual assignment to `err` (ineffassign)
> 	jsonData, err := json.Marshal(writeMap)
> 	          ^
> tests/integration/component.go:498:12: Error return value of `os.Mkdir` is not checked (errcheck)
> 			os.Mkdir(context, 0755)
> 			        ^
> pkg/odo/cli/component/common_push.go:155:38: SA1024: cutset contains duplicate characters (staticcheck)
> 		cpo.componentContext = strings.Trim(filepath.Dir(cpo.localConfigInfo.Filename), ".odo")
> 		                                   ^
> pkg/util/fileIndexer.go:129:16: S1005: should omit value from range; this loop is equivalent to `for fileName := range ...` (gosimple)
> 	for fileName, _ := range readData {
> 	              ^
> make: *** [lint] Error 1
> ```
> 
> Can you please fix those errors
> Details log - https://travis-ci.com/openshift/odo/jobs/220638299

/hold

**Comment by amitkrout** [comment]
> ```
>  Checking http://uberjaropenjdk-app-xaorupsjwh.apps.ci-op-vr5j92m1-f09f4.origin-ci-int-aws.dev.rhcloud.com, for HTTP Booster
> try 0 of 90 
> [...]
> ```
> 
> Could not ping the url within 90 tries
> /test integration

Same failure
/test integration

**Comment by amitkrout** [comment]
ping @alanconway

**Comment by alanconway** [comment]
This branch is stale. If we want to add more linters to the project, better to start over.

**Pull request closed without merging**
