### PR TITLE
Update required s2i imagestreams for nodejs and java on IBM Power

### PR DESCRIPTION
**Pull request by sarveshtamba**
**What type of PR is this?**
/kind bug

**What does does this PR do / why we need it**:
To update the required s2i imagestream for nodejs and java application om IBM Power.

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [ ] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by sarveshtamba** [comment]
Similar changes as in approved/merged PR - https://github.com/openshift/odo/pull/4180

**Review by mohammedzee1000 — APPROVED** [review]
Looks good to me
/lgtm

**Comment by girishramnani** [comment]
/hold
@sarveshtamba what is the latest nodejs in the IBM power arch CI platform?
because currently we have `rhscl/nodejs-12-rhel7` in our supported nodejs images

**Comment by girishramnani** [comment]
this PR https://github.com/openshift/odo/pull/4180 has the same image imports, can we make a common shell script that has common bits for both archs?

**Comment by zhengxiaomei123** [comment]
> this PR #4180 has the same image imports, can we make a common shell script that has common bits for both archs?

@girishramnani I also got this info from @mohammedzee1000 . It's ok for us. If you plan to do the spliting work, We will update the script following yours.

**Comment by sarveshtamba** [comment]
> /hold
> @sarveshtamba what is the latest nodejs in the IBM power arch CI platform?
> because currently we have `rhscl/nodejs-12-rhel7` in our supported nodejs images

Hi @girishramnani this PR and ( PR #4180 ) is precisely to make use of the latest `rhscl/nodejs-12-rhel7` nodejs image for the relevant test cases.

**Comment by sarveshtamba** [comment]
> > this PR #4180 has the same image imports, can we make a common shell script that has common bits for both archs?
> 
> @girishramnani I also got this info from @mohammedzee1000 . It's ok for us. If you plan to do the spliting work, We will update the script following yours.

@girishramnani I agree with @zhengxiaomei123 , for now we can merge this PR, since this resolves multiple test failures on P (& similarly on Z). We can take up the refactoring work post this PR merge on both P & Z.

**Pull request merged**
