### PR TITLE
Update CLI reference.

### PR DESCRIPTION
**Pull request by boczkowska**
/kind documentation
[skip ci]

**What does does this PR do / why we need it**:
Update the CLI reference.
**Which issue(s) this PR fixes**:

Fixes https://github.com/openshift/odo/issues/3870

**PR acceptance criteria**:

- [x] Documentation 

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by boczkowska** [comment]
@prietyc123 could you take a look? I used a script to extract all the descriptions, hopefully nothing is lost.

(Updating the upstream docs first since it will take forever to merge it downstream :disappointed: )

**Comment by cdrage** [comment]
@boczkowska curious what script you used?

Otherwise, this LGTM to me! I'll at least approve it.

/approve

**Comment by girishramnani** [comment]
charlie's approve didn't stick. let me see if mine does
/approve
/lgtm

**Comment by girishramnani** [comment]
awesome - now it worked. I had to add the owners file before

**Pull request merged**
