### PR TITLE
removed unnecessary HasAvailableLocalFlag checks from root usage template

### PR DESCRIPTION
**Pull request by girishramnani**
## What is the purpose of this change? What does it change?

see $SUBJECT

## Was the change discussed in an issue?
No issue

## How to test changes?
`odo` <- output of this shouldn't change

### CODE REVIEW

**Comment by amitkrout** [comment]
> removed unnecessary HasAvailableLocalFlag checks from root usage template

@girishramnani Can you please add some more context of what was the issue and what improvement this pr brings ?

**Comment by kadel** [comment]
What is `HasAvailableLocalFlags` and why it is unnecessary?

/hold

**Pull request merged**
