### PR TITLE
WIP Make Devfile the default deployment mechanism for odo 2.0.0

### PR DESCRIPTION
**Pull request by cdrage**
**What type of PR is this?**
> Uncomment only one ` /kind` line, and delete the rest.
> For example, `> /kind bug` would simply become: `/kind bug`

/kind feature

**What does does this PR do / why we need it**:

Makes Devfile the default deployment mechanism, removing S2I in favour
of Devfile deployment.

**Which issue(s) this PR fixes**:

https://github.com/openshift/odo/issues/3550

**How to test changes / Special notes to the reviewer**:

Run:

```sh
odo preference set experimental false
odo create --starter nodejs
odo push
```

And it should deploy devfile.

### CODE REVIEW

**Comment by cdrage** [comment]
Note, WIP. Don't merge! Opened this PR to test integration tests.

**Comment by prietyc123** [comment]
@cdrage pr needs rebase

**Comment by cdrage** [comment]
> @cdrage pr needs rebase

It's going to need a ton of rebases before the release haha. Hence WIP :) I have a feeling this will be a rebase-everyday PR for a while.

**Comment by metacosm** [comment]
Maybe convert the PR to draft?

**Comment by cdrage** [comment]
Bit confused with regards to @metacosm experimental mode being dealt with once and for all?

At the moment in this PR I'm essentially ripping experimental out for create / push / etc. But we will leave it in for experimental features such as for Docker (which will stay experimental after 2.0 comes out).

**Comment by metacosm** [comment]
> Bit confused with regards to @metacosm experimental mode being dealt with once and for all?
> 
> At the moment in this PR I'm essentially ripping experimental out for create / push / etc. But we will leave it in for experimental features such as for Docker (which will stay experimental after 2.0 comes out).

Sorry didn't see this comment until after I edited my previous one. If we're going to have several experimental features at once, we might want to use feature flags so that they can be de-/activated independently and leave the checks in the code so that we don't need to go through a big "purge" each time a new feature is promoted?

**Comment by cdrage** [comment]
@metacosm This will only be happening once since we're graduating from using S2I. I do agree we need to have flags in the future. But all of these features leaving experimental at once would be okay for the upcoming release. 

The only thing staying in experimental is Docker mode which we will be (partly) supporting.

**Pull request closed without merging**
