### PR TITLE
Removes travis & codecov configuration

### PR DESCRIPTION
**Pull request by dharmit**
**What type of PR is this?**
/kind cleanup

**What does this PR do / why we need it**:
odo doesn't use travis any more.

**Which issue(s) this PR fixes**:

Fixes: None

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [x] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:
Test should pass.

### CODE REVIEW

**Review by anandrkskd — COMMENTED** [review]
LGTM

**Comment by dharmit** [comment]
@prietyc123 is the failure related to your proposed fix in https://github.com/openshift/odo/pull/4630/? Because it seems unrelated to code change in this PR:
```
 INFO[2021-04-16T07:18:21Z] • Failure [246.176 seconds]     
INFO[2021-04-16T07:18:21Z] odo supported images e2e tests               
INFO[2021-04-16T07:18:21Z] /go/src/github.com/openshift/odo/tests/e2escenarios/e2e_images_test.go:17 
INFO[2021-04-16T07:18:21Z]   odo supported private registry images deployment 
INFO[2021-04-16T07:18:21Z]   /go/src/github.com/openshift/odo/tests/e2escenarios/e2e_images_test.go:125 
INFO[2021-04-16T07:18:21Z]     Should be able to verify the openjdk-11-rhel8 image [It] 
INFO[2021-04-16T07:18:21Z]     /go/src/github.com/openshift/odo/tests/e2escenarios/e2e_images_test.go:133 
INFO[2021-04-16T07:18:21Z]                                              
INFO[2021-04-16T07:18:21Z]     No future change is possible.  Bailing out early after 240.909s. 
INFO[2021-04-16T07:18:21Z]     Running odo with args [odo push --context /tmp/843824974] 
INFO[2021-04-16T07:18:21Z]     Expected                                 
INFO[2021-04-16T07:18:21Z]         <int>: 1                             
INFO[2021-04-16T07:18:21Z]     to match exit code:                      
INFO[2021-04-16T07:18:21Z]         <int>: 0                         
INFO[2021-04-16T07:18:21Z]                                              
INFO[2021-04-16T07:18:21Z]     /go/src/github.com/openshift/odo/tests/helper/helper_run.go:34 
```

**Comment by prietyc123** [comment]
> @prietyc123 is the failure related to your proposed fix in #4630? Because it seems unrelated to code change in this PR:

No, its nowhere related to #4630 🙂 . Its a flake tracked https://github.com/openshift/odo/issues/2877

**Pull request merged**
