### PR TITLE
Added java-maven to the list of components to be tested

### LINKED ISSUE #4162: Add e2e scenario for java-maven devfile debug command
/kind flake

## Actual behavior
As an odo user, I want to create a java-maven project from a devfile starter project, then be able to use the debugger to debug the application running in the cluster.

This is continuation of issue #3377 , there is a dependency on issue  devfile/api#115 as starterProject is not available for java-maven.

## Expected behavior
starterProject should be included in the java-maven devfile

## Acceptance Criteria 
- [ ] Update e2e scenario to add java-maven coverage
- [ ] Run test e2e scenario (make test-e2e-devfile) to ensure it passes

### PR DESCRIPTION
**Pull request by rnapoles-rh**
**What type of PR is this?**
/kind feature

**What does does this PR do / why we need it**:
Adding java-maven to be tested in the devfile debug e2e scenarios

**Which issue(s) this PR fixes**:

Fixes #4162

**PR acceptance criteria**:

- [ ] Unit test 

- [x] Integration test 

- [ ] Documentation 

- [x] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:
make test-e2e-devfile

### CODE REVIEW

**Comment by rnapoles-rh** [comment]
devfile debug for nodejs failed for this PR, however in PR4406 test for java-openliberty failed and nodejs passed. Retesting.

**Comment by dharmit** [comment]
```
I0211 04:16:39.847647  978229 events.go:52] Warning Event: Count: 7, Reason: Failed, Message: Error: secret "hzhglm-etcdcluster-example" not found
[ssh:Fedora 32] [odo]  ✗  Waiting for component to start [5m] [WARNING x7: Failed]
[ssh:Fedora 32] [odo]  ✗  Failed to start component with name hzhglm. Error: Failed to create the component: error while waiting for deployment rollout: timeout while waiting for hzhglm deployment roll out\nFor more information to help determine the cause of the error, re-run with '-v'.
[ssh:Fedora 32] [odo] See below for a list of failed events that occured more than 5 times during deployment:
[ssh:Fedora 32] [odo] 
[ssh:Fedora 32] [odo]  NAME                                      COUNT  REASON  MESSAGE                        
[ssh:Fedora 32] [odo] 
[ssh:Fedora 32] [odo]  hzhglm-788f84d788-ggpwb.16629655170957fd  7      Failed  Error: secret                  
[ssh:Fedora 32] [odo]                                                           "hzhglm-etcdcluster-example"   
[ssh:Fedora 32] [odo]                                                           not found                      
[ssh:Fedora 32] [odo] 
[ssh:Fedora 32] [odo] 
[ssh:Fedora 32] Deleting project: denjxzfvkn
[ssh:Fedora 32] Running odo with args [odo project delete denjxzfvkn -f] 
```
#4301
/retest

**Review by dharmit — APPROVED** [review]
/approve
/lgtm

(small change.)

**Pull request merged**
