### PR TITLE
Add "pretty" library for testing

### PR DESCRIPTION
**Pull request by cdrage**
Adds the "pretty" library for easier debugging.

See below:

```sh
--- FAIL: TestListWithDetailedStatus (0.00s)
    service_test.go:482:  [
          {
           TypeMeta: {
            Kind: "Service",
            APIVersion: "odo.openshift.io/v1alpha1",
           },
           ObjectMeta: {
            Name: "mysql-persistent",
            GenerateName: "",
            Namespace: "",
            SelfLink: "",
            UID: "",
            ResourceVersion: "",
            Generation: 0,
            CreationTimestamp: {
             Time: 0001-01-01 00:00:00 +0000 UTC,
            },
            DeletionTimestamp: nil,
            DeletionGracePeriodSeconds: nil,
            Labels: {
            },
            Annotations: {
            },
            OwnerReferences: [
            ],
            Initializers: nil,
            Finalizers: [
            ],
            ClusterName: "",
           },
           Spec: {
            Type: "mysql-persistent",
            Plan: "default",
           },
           Status: {
        -   Status: "ProvisionedSuccessfully",
        +   Status: "ProvisionedAndLinked",
           },
```

Vs:

```
--- FAIL: TestListWithDetailedStatus (0.00s)
    service_test.go:481: expected output: []service.Service{service.Service{TypeMeta:v1.TypeMeta{Kind:"Service", APIVersion:"odo.openshift.io/v1alpha1"}, ObjectMeta:v1.ObjectMeta{Name:"mysql-persistent", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Locati
on)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:service.ServiceSpec{Type:"mysql-persistent", Plan:"default"}, Status:service.Serv
iceStatus{Status:"ProvisionedSuccessfully"}}, service.Service{TypeMeta:v1.TypeMeta{Kind:"Service", APIVersion:"odo.openshift.io/v1alpha1"}, ObjectMeta:v1.ObjectMeta{Name:"postgresql-ephemeral", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}
, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:service.ServiceSpec{Type:"postgresql-ephemeral", Plan:"default"}, Status:service.ServiceSta
tus{Status:"ProvisionedSuccessfully"}}, service.Service{TypeMeta:v1.TypeMeta{Kind:"Service", APIVersion:"odo.openshift.io/v1alpha1"}, ObjectMeta:v1.ObjectMeta{Name:"mongodb", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp
:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:service.ServiceSpec{Type:"mongodb", Plan:"default"}, Status:service.ServiceStatus{Status:"ProvisionedSuccessfu
lly"}}, service.Service{TypeMeta:v1.TypeMeta{Kind:"Service", APIVersion:"odo.openshift.io/v1alpha1"}, ObjectMeta:v1.ObjectMeta{Name:"jenkins-persistent", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), Del
etionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:service.ServiceSpec{Type:"jenkins-persistent", Plan:"default"}, Status:service.ServiceStatus{Status:"Provisioning"}}},got: []servic
e.Service{service.Service{TypeMeta:v1.TypeMeta{Kind:"Service", APIVersion:"odo.openshift.io/v1alpha1"}, ObjectMeta:v1.ObjectMeta{Name:"mysql-persistent", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), Del
etionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:service.ServiceSpec{Type:"mysql-persistent", Plan:"default"}, Status:service.ServiceStatus{Status:"ProvisionedAndLinked"}}, service
.Service{TypeMeta:v1.TypeMeta{Kind:"Service", APIVersion:"odo.openshift.io/v1alpha1"}, ObjectMeta:v1.ObjectMeta{Name:"postgresql-ephemeral", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePer
iodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:service.ServiceSpec{Type:"postgresql-ephemeral", Plan:"default"}, Status:service.ServiceStatus{Status:"ProvisionedAndBound"}}, service.Service{T
ypeMeta:v1.TypeMeta{Kind:"Service", APIVersion:"odo.openshift.io/v1alpha1"}, ObjectMeta:v1.ObjectMeta{Name:"mongodb", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil
), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:service.ServiceSpec{Type:"mongodb", Plan:"default"}, Status:service.ServiceStatus{Status:"ProvisionedSuccessfully"}}, service.Service{TypeMeta:v1.TypeMeta{Kind:"Servic
e", APIVersion:"odo.openshift.io/v1alpha1"}, ObjectMeta:v1.ObjectMeta{Name:"jenkins-persistent", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]
string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Spec:service.ServiceSpec{Type:"jenkins-persistent", Plan:"default"}, Status:service.ServiceStatus{Status:"Provisioning"}}}
```

Closes: https://github.com/openshift/odo/issues/2120

### CODE REVIEW

**Comment by kadel** [comment]
/retest
```
[oc] 'Running oc with args [oc get is java -n openshift -o jsonpath='{range .spec.tags[*]}{.name}{"\n"}{end}']
[oc] '8
[oc] latest
[oc] 'Running oc with args [oc --request-timeout 5m import-image java:8 --namespace=wdjfwaeark --from=registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.5 --confirm]
[oc] error: tag 1.5 failed: Internal error occurred: received unexpected HTTP status: 503 Service Unavailable
[oc] imagestream.image.openshift.io/java imported with errors
[oc] 
[oc] Name:			java
[oc] Namespace:		wdjfwaeark
[oc] Created:		Less than a second ago
[oc] Labels:			<none>
[oc] Annotations:		openshift.io/image.dockerRepositoryCheck=2019-09-12T18:35:30Z
[oc] Image Repository:	image-registry.openshift-image-registry.svc:5000/wdjfwaeark/java
[oc] Image Lookup:		local=false
[oc] Unique Images:		0
[oc] Tags:			1
[oc] 
[oc] 8
[oc]   tagged from registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.5
[oc] 
[oc]   ! error: Import failed (InternalError): Internal error occurred: received unexpected HTTP status: 503 Service Unavailable
[oc]       Less than a second ago
[oc] 
[oc] 
```

**Comment by cdrage** [comment]
@dharmit 
Yeah, order doesn't matter :)

**Comment by cdrage** [comment]
Rebased, up for another review :+1:

**Pull request merged**
