### PR TITLE
Remove -q param in odo project command

### LINKED ISSUE #2863: weird -q param for project
/kind bug

## What versions of software are you using?
master build code 5ab3fd979ee9dfb84ef14e12ebeedfba7ef34f06

**Operating System:**

**Output of `odo version`:**

## How did you run odo exactly?

the -q is weird, 
```
[root@xyimgr77 fff]# ./odo project
Error: Subcommand not found, use one of the available commands: create, delete, get, list, set
Usage:
  odo project [options] [flags]
  odo project [command]

Examples:
  # Set the active project
  odo project set

  # Create a new project
  odo project create myproject

  # List all the projects
  odo project list

  ....
Flags:
  -h, --help    Help for project
  -q, --short   If true, display only the project name
```

### PR DESCRIPTION
**Pull request by jichenjc**
**What type of PR is this?**

/kind bug
**What does does this PR do / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #2863 

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by girishramnani** [comment]
@mohitsuman do you use this flag anywhere in the vscode adapter?

**Comment by mohitsuman** [comment]
> @mohitsuman do you use this flag anywhere in the vscode adapter?

@girishramnani  No we do not use this param in vscode side as of now.

**Comment by girishramnani** [comment]
got it,
/approve

**Comment by girishramnani** [comment]
small enough change. merging
/lgtm

**Pull request merged**
