### PR TITLE
Fixing golang image pull error

### PR DESCRIPTION
**Pull request by prietyc123**
**What type of PR is this?**

/kind failing-test

**What does does this PR do / why we need it**:

Fixing ci failure.

```
error: build error: failed to pull image: After retrying 2 times, Pull image still failed due to error: while pulling "docker://registry.svc.ci.openshift.org/openshift/release:golang-1.13" as "registry.svc.ci.openshift.org/openshift/release:golang-1.13": Error initializing source docker://registry.svc.ci.openshift.org/openshift/release:golang-1.13: error pinging docker registry registry.svc.ci.openshift.org: invalid status code from registry 503 (Service Unavailable)
```

**Which issue(s) this PR fixes**:

Fixes #?

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [ ] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Review by mohammedzee1000 — APPROVED** [review]
Looks good to me
/lgtm

**Comment by mohammedzee1000** [comment]
The tests will fail as until the image is in master, it will still try to pull old image

**Review by dharmit — APPROVED** [review]
/approve

**Comment by mohammedzee1000** [comment]
@kadel @dharmit this might need an override.
And yes, image pull is verified

```
❯ podman pull registry.ci.openshift.org/openshift/release:golang-1.13
Trying to pull registry.ci.openshift.org/openshift/release:golang-1.13...
Getting image source signatures
Copying blob 2d473b07cdd5 [--------------------------------------] 169.6KiB / 72.6MiB
Copying blob 7e8f78e3fb4e [--------------------------------------] 118.6KiB / 315.8MiB
^C%                                                                                                 
```

**Comment by dharmit** [comment]
> The tests will fail as until the image is in master, it will still try to pull old image

So does this PR need to be merged manually?

@prietyc123 @mohammedzee1000

**Comment by mohammedzee1000** [comment]
@dharmit see the comment i made above, so yes

**Pull request merged**
