### PR TITLE
Update required s2i imagestreams for nodejs and java on IBM Z.

### PR DESCRIPTION
**Pull request by zhengxiaomei123**
**What type of PR is this?**
/kind bug
**What does does this PR do / why we need it**:
To update the required s2i imagestream for nodejs and java application.

**PR acceptance criteria**:

- [x] Unit test 

- [x] Integration test 

- [x] Documentation 

- [x] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by jichenjc** [comment]
@zhengxiaomei123 can you help to provide an issue about the update purpose?

**Comment by zhengxiaomei123** [comment]
> @zhengxiaomei123 can you help to provide an issue about the update purpose?

@jichenjc Just update the s2i imagestream, there is on issue opened for it.

**Review by mohammedzee1000 — APPROVED** [review]
Looks good to me
/approve

**Pull request merged**
