### PR TITLE
Refactors and moves buildConfigs, imageStreams and some other resources

### PR DESCRIPTION
**Pull request by mik-dass**
**What type of PR is this?**

/kind code-refactoring
/kind cleanup

**What does does this PR do / why we need it**:

Refactors and moves buildConfigs, imageStreams and some other resources like deployments etc into new files or existing files.

**Which issue(s) this PR fixes**:

Fixes part of #4093 

**PR acceptance criteria**:

- [X] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [ ] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

- Tests should pass.

### CODE REVIEW

**Comment by mik-dass** [comment]
```
[odo]  ✗  Waiting for component to start [5m]
[odo]  ✗  Failed to start component with name yhjtpr. Error: Failed to create the component: error while waiting for deployment rollout: timeout while waiting for yhjtpr deployment roll out
Deleting project: afzsefccet
```
/retest

**Comment by dharmit** [comment]
> ```
> [odo]  ✗  Waiting for component to start [5m]
> [odo]  ✗  Failed to start component with name yhjtpr. Error: Failed to create the component: error while waiting for deployment rollout: timeout while waiting for yhjtpr deployment roll out
> Deleting project: afzsefccet
> ```
> 
> /retest

Looks like #3256.

**Comment by dharmit** [comment]
Once again the CI's failing on:
```
[odo]  ✗  Waiting for component to start [5m]
[odo]  ✗  Failed to start component with name fcaivh. Error: Failed to create the component: error while waiting for deployment rollout: timeout while waiting for fcaivh deployment roll out
Deleting project: mpvdkbglsm 
```
:disappointed:

**Review by dharmit — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
