### PR TITLE
Uncommenting spec in java test file

### PR DESCRIPTION
**Pull request by amitkrout**
## What is the purpose of this change? What does it change?

Uncommenting java test as it seems to be fixed in pr #1740
## How to test changes?

make test-java-e2e

### CODE REVIEW

**Comment by amitkrout** [comment]
Java test went fine in first run. Running it for second time
/test integration

**Comment by amitkrout** [comment]
```
[odo]  ✗  Unable to connect to OpenShift cluster, is it down?
```
/test integration

However java component test passed. Its ready for review cc_ @kadel

**Comment by amitkrout** [comment]
> /approve
> /lgtm

Sorry @dharmit 
Just uncommented few more java component test. 

You need to review it again as new changes removed ```approve``` and ```lgtm``` labels

**Comment by dharmit** [comment]
> Sorry @dharmit
> Just uncommented few more java component test.
> 
> You need to review it again as new changes removed `approve` and `lgtm` labels

No issues. But it didn't remove "approved" label. Only "lgtm" was removed. Shouldn't that be removed as well? :thinking: 

/lgtm

**Pull request merged**
