### PR TITLE
Bump odo version to 1.0.0-beta7 in VERSION file

### PR DESCRIPTION
**Pull request by amitkrout**
Bump odo version to 1.0.0-beta7 in "build/VERSION" file

### CODE REVIEW

**Comment by kadel** [comment]
/hold

Shouldn't we bump it directly to 1.0 once it gets out?

**Comment by cdrage** [comment]
@kadel The version is currently Beta7, we should update it ASAP before 1.0.0 comes out?

**Comment by kadel** [comment]
> @kadel The version is currently Beta7, we should update it ASAP before 1.0.0 comes out?

1.0.0  should be out in a few hours

**Comment by amitkrout** [comment]
> > @kadel The version is currently Beta7, we should update it ASAP before 1.0.0 comes out?
> 
> 1.0.0 should be out in a few hours
> 
> #2296

@kadel Yes, but this is the last step for beta release as per the release doc - https://github.com/openshift/odo/blob/master/docs/dev/development.adoc#releasing-a-new-version

Just a question - What is the use of updating version info in build/VERSION file ? and what impact it brings if we missed it ?

**Comment by cdrage** [comment]
@kadel Alright. Let's do another release and get 1.0.0 out?

**Comment by amitkrout** [comment]
> @kadel Alright. Let's do another release and get 1.0.0 out?

1.0 GA is out, So this is no more a valid pr.
/close

**Pull request closed without merging**
