### PR TITLE
Prevent v1 devfiles from being used

### PR DESCRIPTION
**Pull request by johnmcollier**
**What type of PR is this?**
/kind cleanup

**What does does this PR do / why we need it**:
This PR removes the ability to create v1 devfiles in odo, and adds a validation error when a user tries to use one, as most v1 devfiles no long work with odo (and we have feature parity with v2 devfiles)

```
Johns-MacBook-Pro-3:test johncollier$ odo push
 ✗  unsupported devfile version. Only devfiles with schema version 2.0.0 are supported
```
**Which issue(s) this PR fixes**:

Fixes https://github.com/openshift/odo/issues/3621

**PR acceptance criteria**:

- [ ] Unit test 

- [x] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by johnmcollier** [comment]
```
 time="2020-08-19T07:18:26Z" level=error msg="Waiting for container artifacts in pod release-latest in namespace ci-op-wl48wnln" error="pods \"release-latest\" is forbidden: User \"system:serviceaccount:ci:ci-operator\" cannot get resource \"pods\" in API group \"\" in the namespace \"ci-op-wl48wnln\""
time="2020-08-19T07:18:27Z" level=error msg="Waiting for container artifacts in pod release-latest in namespace ci-op-wl48wnln" error="pods \"release-latest\" is forbidden: User \"system:serviceaccount:ci:ci-operator\" cannot get resource \"pods\" in API group \"\" in the namespace \"ci-op-wl48wnln\""
time="2020-08-19T07:18:27Z" level=error msg="Waiting for container artifacts in pod release-latest in namespace ci-op-wl48wnln" error="pods \"release-latest\" is forbidden: User \"system:serviceaccount:ci:ci-operator\" cannot get resource \"pods\" in API group \"\" in the namespace \"ci-op-wl48wnln\""
2020/08/19 07:18:27 error: unable to signal to artifacts container to terminate in pod release-latest, triggering deletion: could not run remote command: pods "release-latest" is forbidden: User "system:serviceaccount:ci:ci-operator" cannot create resource "pods/exec" in API group "" in the namespace "ci-op-wl48wnln"
2020/08/19 07:18:27 error: unable to retrieve artifacts from pod release-latest and the pod could not be deleted: pods "release-latest" is forbidden: User "system:serviceaccount:ci:ci-operator" cannot delete resource "pods" in API group "" in the namespace "ci-op-wl48wnln"
2020/08/19 07:18:27 error: artifacts container for pod release-latest unready: timed out waiting for the condition 
```

Infra flakes

/retest

**Comment by adisky** [comment]
@johnmcollier should we also remove v1 specific code along with it?

**Comment by johnmcollier** [comment]
@adisky That's all the v1 specific code that remains, other than the v1 types (which we're intentionally leaving in the parser for now)

**Review by dev-gaur — APPROVED** [review]

**Comment by girishramnani** [comment]
I would like to get confirmation from @sbose78 's team before we remove the v1 parser and adapter code as they are working on the parser library codebase.
so for now this is good enough for me.
cc @kadel 
/approve

**Comment by kadel** [comment]
> I would like to get confirmation from @sbose78 's team before we remove the v1 parser and adapter code as they are working on the parser library codebase.

There is no plan for that library to support devfile v1

**Pull request merged**
