### PR TITLE
Upgrade apiVersion to v1 from v1alpha1

### PR DESCRIPTION
**Pull request by cdrage**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:

/kind api-change

**What does does this PR do / why we need it**:

We reached 1.0.0 a while ago! We can consider this apiVersion to be v1
now and obviously new features / changes to be alpha.

**Which issue(s) this PR fixes**:

Fixes https://github.com/openshift/odo/issues/2490

**How to test changes / Special notes to the reviewer**:

N/A, just run tests or deploy a component

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

### CODE REVIEW

**Comment by mik-dass** [comment]
According to https://github.com/openshift/odo/issues/2490#issuecomment-596642540
```
we'll have to implement some form of backwards compatibility if there are any breaking changes.
```
but I couldn't find anything to support backwards compatibility or am I missing something?

**Comment by girishramnani** [comment]
I think what @cdrage meant was to maintain backwards compatibility from now on. as currently there is nothing different between v1 and v1alpha1 there is no need to have anything for backward compatibility.

once @cdrage confirms this, I will approve this PR

**Comment by mik-dass** [comment]
> I think what @cdrage meant was to maintain backwards compatibility from now on. as currently there is nothing different between v1 and v1alpha1 there is no need to have anything for backward compatibility.

But I think this will break things for the adapter team. @cdrage am I missing something?

**Comment by kadel** [comment]
/hold
/release-not-action-required
@cdrage please check with @dgolovin and @jeffmaury whatever they are using `apiVersion` field in VSCode and IntelliJ plugins or not.

**Comment by cdrage** [comment]
I confirmed with both Dennis and Jeff over slack that they both do not check for `apiVersion`.

**Comment by cdrage** [comment]
ping @kadel @mik-dass @amitkrout @girishramnani for review + merge

**Comment by mik-dass** [comment]
```
f \"Master Machines\": failed to generate asset \"Platform Credentials Check\": validate AWS credentials: checking install permissions: error simulating policy: Throttling: Rate exceeded\n\tstatus code: 400, request id: 5e2f8636-3f95-4b94-a552-d24caaed21ff"
```
/retest

**Comment by mik-dass** [comment]
@cdrage Most of the json output test cases are failing on the prow

```
• Failure [61.732 seconds]
odo component command tests
/go/src/github.com/openshift/odo/tests/integration/cmd_cmp_test.go:13
  Creating component
  /go/src/github.com/openshift/odo/tests/integration/component.go:52
    should describe pushed component when it is created with json output [It]
    /go/src/github.com/openshift/odo/tests/integration/component.go:249
    Expected
      
        <string>: "...io/v1","kin..."
    to equal               |
        <string>: "...io/v1alpha1..."
```
Can you please have a look?
/hold

**Comment by girishramnani** [comment]
@cdrage any update on this?

**Comment by mik-dass** [comment]
```
level=info msg="Consuming Install Config from target directory"
level=fatal msg="failed to fetch Common Manifests: failed to fetch dependency of \"Common Manifests\": failed to generate asset \"DNS Config\": getting public zone for \"origin-ci-int-aws.dev.rhcloud.com\": listing hosted zones: Throttling: Rate exceeded\n\tstatus code: 400, request id: d0df1712-35fb-41cf-8df6-18b7cae8d2fb"
```
/retest

**Comment by mik-dass** [comment]
@cdrage Can you please rebase this? Rest looks good to me.

**Pull request closed without merging**
