### PR TITLE
Rename install.sh to installer.sh and Add Uninstall

### LINKED ISSUE #1733: Uninstall Script
[kind/Feature]

As far as I can tell, there is no uninstall script available for `odo` at this time. It would be helpful to have an OS-independent script similar to the install script. 

## Which functionality do you think we should add?
Uninstall `odo` in an OS-independent manner.

## Why is this needed?
Give users the ability to uninstall `odo`. My use case is that I would like to remove an old version from an environment I am working in.

### PR DESCRIPTION
**Pull request by danielhelfand**
This pull request is the same as #1762. I am opening a new pull request to address an issue I had with rebasing #1762. 

Closes #1733

### CODE REVIEW

**Comment by danielhelfand** [comment]
@amitkrout Can you give this another look when you have a chance? Thanks.

**Comment by kadel** [comment]
/approve

@danielhelfand Thank you! This looks good.

**Comment by danielhelfand** [comment]
@kadel Appreciate it!

**Pull request merged**
