### PR TITLE
Updating default bootstrapper image to GA'ed image

### PR DESCRIPTION
**Pull request by mohammedzee1000**
registry.access.redhat.com/openshiftdo/odo-init-image-rhel7:1.0.0

Signed-off-by: Mohammed Zeeshan Ahmed <mohammed.zee1000@gmail.com>

### CODE REVIEW

**Comment by kadel** [comment]
/approve

done some quick manual testing, and everything looks good so far

**Comment by mohammedzee1000** [comment]
CI failures
/retest

**Comment by mohammedzee1000** [comment]
CI timeout
/retest

**Pull request merged**
