### PR TITLE
Fixing now implementation for config set and unset in devfile

### LINKED ISSUE #4594: --now flag for odo config set --env not supported for devfiles
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:**

### PR DESCRIPTION
**Pull request by mohammedzee1000**
Signed-off-by: Mohammed Zeeshan Ahmed <mohammed.zee1000@gmail.com>

**What type of PR is this?**
/kind bug

**What does this PR do / why we need it**:
[see title]

**Which issue(s) this PR fixes**:

Fixes #4594

**PR acceptance criteria**:

- [ ] Unit test 

- [x] Integration test 

- [ ] Documentation 

- [x] Update changelog

- [x] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:
With now flag
```bash
> odo create nodejs
...
> odo push

Validation
 ✓  Validating the devfile [164372ns]

Updating services
 ✓  Services and Links are in sync with the cluster, no changes are required

Creating Kubernetes resources for component nodejs-nodejs-ex-odtu
 ✓  Waiting for component to start [7s]
 ✓  Waiting for component to start [427ms]

Applying URL changes
 ✓  URL http-3000: http://http-3000-nodejs-nodejs-ex-odtu-uv.apps.testocp47.psiodo.net/ created

Syncing to component nodejs-nodejs-ex-odtu
 ✓  Checking files for pushing [4ms]
 ✓  Syncing files to the component [9s]

Executing devfile commands for component nodejs-nodejs-ex-odtu
 ✓  Waiting for component to start [371ms]
 ✓  Executing install command "npm install" [11s]
 ✓  Executing run command "npm start" [4s]

Pushing devfile component "nodejs-nodejs-ex-odtu"
 ✓  Changes successfully pushed to component
> oc get deployments
NAME                        READY     UP-TO-DATE   AVAILABLE   AGE
nodejs-nodejs-ex-odtu-app   1/1       1            1           69s
> odo config view
ComponentName: nodejs
Configs:
- ContainerName: runtime
  Ports:
  - ExposedPort: 3000
    Name: http-3000
    Protocol: http
Memory: 1024Mi
> oc describe deployment/nodejs-nodejs-ex-odtu-app
Name:               nodejs-nodejs-ex-odtu-app
Namespace:          uv
CreationTimestamp:  Tue, 06 Jul 2021 19:31:55 +0530
Labels:             app=app
                    app.kubernetes.io/instance=nodejs-nodejs-ex-odtu
                    app.kubernetes.io/managed-by=odo
                    app.kubernetes.io/managed-by-version=v2.2.2
                    app.kubernetes.io/name=nodejs
                    app.kubernetes.io/part-of=app
                    component=nodejs-nodejs-ex-odtu
Annotations:        app.openshift.io/vcs-uri=https://github.com/openshift/nodejs-ex
                    deployment.kubernetes.io/revision=1
Selector:           component=nodejs-nodejs-ex-odtu
Replicas:           1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:       Recreate
MinReadySeconds:    0
Pod Template:
  Labels:  app=app
           app.kubernetes.io/instance=nodejs-nodejs-ex-odtu
           app.kubernetes.io/managed-by=odo
           app.kubernetes.io/managed-by-version=v2.2.2
           app.kubernetes.io/name=nodejs
           app.kubernetes.io/part-of=app
           component=nodejs-nodejs-ex-odtu
  Init Containers:
   copy-supervisord:
    Image:      registry.access.redhat.com/ocp-tools-4/odo-init-container-rhel8:1.1.10
    Port:       <none>
    Host Port:  <none>
    Command:
      /usr/bin/cp
    Args:
      -r
      /opt/odo-init/.
      /opt/odo/
    Environment:  <none>
    Mounts:
      /opt/odo/ from odo-supervisord-shared-data (rw)
  Containers:
   runtime:
    Image:      registry.access.redhat.com/ubi8/nodejs-14:latest
    Port:       3000/TCP
    Host Port:  0/TCP
    Command:
      /opt/odo/bin/supervisord
    Args:
      -c
      /opt/odo/conf/devfile-supervisor.conf
    Limits:
      memory:  1Gi
    Environment:
      PROJECTS_ROOT:                  /project
      PROJECT_SOURCE:                 /project
      ODO_COMMAND_RUN:                npm start
      ODO_COMMAND_RUN_WORKING_DIR:    /project
      ODO_COMMAND_DEBUG:              npm run debug
      ODO_COMMAND_DEBUG_WORKING_DIR:  /project
      DEBUG_PORT:                     5858
    Mounts:
      /opt/odo/ from odo-supervisord-shared-data (rw)
      /project from odo-projects (rw)
  Volumes:
   odo-projects:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
   odo-supervisord-shared-data:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  nodejs-nodejs-ex-odtu-app-56887ccfc6 (1/1 replicas created)
NewReplicaSet:   <none>
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  2m    deployment-controller  Scaled up replica set nodejs-nodejs-ex-odtu-app-56887ccfc6 to 1
> odo config set --env KAFKA_HOST=kafka --env KAFKA_PORT=6639 --now
 ✓  Environment variables were successfully updated
 ✓  Waiting for component to start [367ms]

Validation
 ✓  Validating the devfile [126361ns]

Updating services
 ✓  Services and Links are in sync with the cluster, no changes are required

Creating Kubernetes resources for component nodejs-nodejs-ex-odtu
 ✓  Waiting for component to start [9s]
 ✓  Waiting for component to start [416ms]

Applying URL changes
 ✓  URLs are synced with the cluster, no changes are required.

Syncing to component nodejs-nodejs-ex-odtu
 ✓  Checking file changes for pushing [2ms]
 ✓  Syncing files to the component [9s]

Executing devfile commands for component nodejs-nodejs-ex-odtu
 ✓  Waiting for component to start [362ms]
 ✓  Executing install command "npm install" [10s]
 ✓  Executing run command "npm start" [3s]

Pushing devfile component "nodejs-nodejs-ex-odtu"
 ✓  Changes successfully pushed to component
> odo config view
ComponentName: nodejs
Configs:
- ContainerName: runtime
  EnvironmentVariables:
  - Name: KAFKA_HOST
    Value: kafka
  - Name: KAFKA_PORT
    Value: "6639"
  Ports:
  - ExposedPort: 3000
    Name: http-3000
    Protocol: http
Memory: 1024Mi
> oc describe deployment/nodejs-nodejs-ex-odtu-app
...
    Environment:
      PROJECTS_ROOT:                  /project
      PROJECT_SOURCE:                 /project
      ODO_COMMAND_RUN:                npm start
      ODO_COMMAND_RUN_WORKING_DIR:    /project
      ODO_COMMAND_DEBUG:              npm run debug
      ODO_COMMAND_DEBUG_WORKING_DIR:  /project
      DEBUG_PORT:                     5858
      KAFKA_HOST:                     kafka
      KAFKA_PORT:                     6639
> odo config set Memory 1536Mi --force --now
 ✓  Devfile successfully updated
 ✓  Waiting for component to start [379ms]

Validation
 ✓  Validating the devfile [110625ns]

Updating services
 ✓  Services and Links are in sync with the cluster, no changes are required

Creating Kubernetes resources for component nodejs-nodejs-ex-odtu
 ✓  Waiting for component to start [18s]
 ✓  Waiting for component to start [426ms]

Applying URL changes
 ✓  URLs are synced with the cluster, no changes are required.

Syncing to component nodejs-nodejs-ex-odtu
 ✓  Checking file changes for pushing [4ms]
 ✓  Syncing files to the component [9s]

Executing devfile commands for component nodejs-nodejs-ex-odtu
 ✓  Waiting for component to start [379ms]
 ✓  Executing install command "npm install" [10s]
 ✓  Executing run command "npm start" [3s]

Pushing devfile component "nodejs-nodejs-ex-odtu"
 ✓  Changes successfully pushed to component
> odo config view
ComponentName: nodejs
Configs:
- ContainerName: runtime
  EnvironmentVariables:
  - Name: KAFKA_HOST
    Value: kafka
  - Name: KAFKA_PORT
    Value: "6639"
  Ports:
  - ExposedPort: 3000
    Name: http-3000
    Protocol: http
Memory: 1536Mi
> oc describe deployment/nodejs-nodejs-ex-odtu-app
...
    Limits:
      memory:  1536Mi

...
> odo config unset --env KAFKA_HOST --env KAFKA_PORT --now
 ✓  Environment variables were successfully updated
 ✓  Waiting for component to start [405ms]

Validation
 ✓  Validating the devfile [159908ns]

Updating services
 ✓  Services and Links are in sync with the cluster, no changes are required

Creating Kubernetes resources for component nodejs-nodejs-ex-odtu
 ✓  Waiting for component to start [15s]
 ✓  Waiting for component to start [374ms]

Applying URL changes
 ✓  URLs are synced with the cluster, no changes are required.

Syncing to component nodejs-nodejs-ex-odtu
 ✓  Checking file changes for pushing [2ms]
 ✓  Syncing files to the component [9s]

Executing devfile commands for component nodejs-nodejs-ex-odtu
 ✓  Waiting for component to start [362ms]
 ✓  Executing install command "npm install" [11s]
 ✓  Executing run command "npm start" [4s]

Pushing devfile component "nodejs-nodejs-ex-odtu"
 ✓  Changes successfully pushed to component
> odo config view
ComponentName: nodejs
Configs:
- ContainerName: runtime
  Ports:
  - ExposedPort: 3000
    Name: http-3000
    Protocol: http
Memory: 1536Mi
> oc describe deployment/nodejs-nodejs-ex-odtu-app
...
    Environment:
      PROJECTS_ROOT:                  /project
      PROJECT_SOURCE:                 /project
      ODO_COMMAND_RUN:                npm start
      ODO_COMMAND_RUN_WORKING_DIR:    /project
      ODO_COMMAND_DEBUG:              npm run debug
      ODO_COMMAND_DEBUG_WORKING_DIR:  /project
      DEBUG_PORT:                     5858
    Mounts:

```

Control (to ensure nothin is broken without now flag)

```bash
> odo delete
? Are you sure you want to delete the devfile component: nodejs-nodejs-ex-odtu? Yes

Gathering information for component nodejs-nodejs-ex-odtu
 ✓  Checking status for component [371ms]

Deleting component nodejs-nodejs-ex-odtu
 ✓  Deleting Kubernetes resources for component [360ms]
 ✓  Successfully deleted component
> odo push

Validation
 ✓  Validating the devfile [43446ns]

Updating services
 ✓  Services and Links are in sync with the cluster, no changes are required

Creating Kubernetes resources for component nodejs-nodejs-ex-odtu
 ✓  Waiting for component to start [5s]
 ✓  Waiting for component to start [408ms]

Applying URL changes
 ✓  URL http-3000: http://http-3000-nodejs-nodejs-ex-odtu-uv.apps.testocp47.psiodo.net/ created

Syncing to component nodejs-nodejs-ex-odtu
 ✓  Checking files for pushing [4ms]
 ✓  Syncing files to the component [9s]

Executing devfile commands for component nodejs-nodejs-ex-odtu
 ✓  Waiting for component to start [401ms]
 ✓  Executing install command "npm install" [10s]
 ✓  Executing run command "npm start" [3s]

Pushing devfile component "nodejs-nodejs-ex-odtu"
 ✓  Changes successfully pushed to component
> odo config set Memory 1024Mi --force
 ✓  Devfile successfully updated

Run `odo push` command to apply changes to the cluster
> odo config view
ComponentName: nodejs
Configs:
- ContainerName: runtime
  Ports:
  - ExposedPort: 3000
    Name: http-3000
    Protocol: http
Memory: 1536Mi
> odo config set Memory 1024Mi --force
 ✓  Devfile successfully updated

Run `odo push` command to apply changes to the cluster
> odo config set --env KAFKA_HOST=kafka --env KAFKA_PORT=6639
 ✓  Environment variables were successfully updated

Run `odo push` command to apply changes to the cluster
> odo config view
ComponentName: nodejs
Configs:
- ContainerName: runtime
  EnvironmentVariables:
  - Name: KAFKA_HOST
    Value: kafka
  - Name: KAFKA_PORT
    Value: "6639"
  Ports:
  - ExposedPort: 3000
    Name: http-3000
    Protocol: http
Memory: 1024Mi
> odo push
 ✓  Waiting for component to start [379ms]

Validation
 ✓  Validating the devfile [118638ns]

Updating services
 ✓  Services and Links are in sync with the cluster, no changes are required

Creating Kubernetes resources for component nodejs-nodejs-ex-odtu
 ✓  Waiting for component to start [14s]
 ✓  Waiting for component to start [403ms]

Applying URL changes
 ✓  URLs are synced with the cluster, no changes are required.

Syncing to component nodejs-nodejs-ex-odtu
 ✓  Checking file changes for pushing [2ms]
 ✓  Syncing files to the component [9s]

Executing devfile commands for component nodejs-nodejs-ex-odtu
 ✓  Waiting for component to start [388ms]
 ✓  Executing install command "npm install" [11s]
 ✓  Executing run command "npm start" [3s]

Pushing devfile component "nodejs-nodejs-ex-odtu"
 ✓  Changes successfully pushed to component
> oc describe deployment/nodejs-nodejs-ex-odtu-app
...
    Limits:
      memory:  1Gi
    Environment:
      PROJECTS_ROOT:                  /project
      PROJECT_SOURCE:                 /project
      ODO_COMMAND_RUN:                npm start
      ODO_COMMAND_RUN_WORKING_DIR:    /project
      ODO_COMMAND_DEBUG:              npm run debug
      ODO_COMMAND_DEBUG_WORKING_DIR:  /project
      DEBUG_PORT:                     5858
      KAFKA_HOST:                     kafka
      KAFKA_PORT:                     6639

...
```

### CODE REVIEW

**Comment by mohammedzee1000** [comment]
unrelated fail
/retest

**Comment by mohammedzee1000** [comment]
prow error
/retest

**Comment by mohammedzee1000** [comment]
Prow error
/retest

**Comment by mohammedzee1000** [comment]
prow error
/retest

**Comment by mohammedzee1000** [comment]
Failure seems to be unrelated to the code change
/retest

**Comment by valaparthvi** [comment]
The functionality part works okay.
/approve

**Pull request merged**
