### PR TITLE
Small update to help.

### PR DESCRIPTION
**Pull request by cdrage**
Changes the order of the examples and slightly modifies the output.

```sh
Examples:
  # Create a URL with a specific name by automatically detecting the port used by the image
  odo url create example

  # Create a URL for the current component with a specific port
  odo url create --port 8080

  # Create a URL with a specific name and port
  odo url create example --port 8080

  # Create a URL with a specific name and port for component frontend
  odo url create example --port 8080 --component frontend
```

### CODE REVIEW

**Comment by cdrage** [comment]
Found this while looking at https://github.com/openshift/odo/issues/1772 doc requirements.

**Comment by amitkrout** [comment]
```
 ++ '[' 1 -eq 0 ']'
++ sleep 3
++ for i in '{1..40}'
++ oc login -u developer -p developer
++ '[' 1 -eq 0 ']'
++ sleep 3
++ '[' false == false ']'
++ echo 'Failed to login as developer'
++ exit 1
Failed to login as developer
make[1]: *** [configure-installer-tests-cluster] Error 1
make[1]: Leaving directory `/go/src/github.com/openshift/odo'
make: *** [openshiftci-presubmit-e2e] Error 2 
```
Seems cluster is not responsive within the number of try
/test integration

**Pull request merged**
