### PR TITLE
Devfile registry telemetry integration

### PR DESCRIPTION
**Pull request by GeekArthur**
Signed-off-by: Jingfu Wang <jingfwan@redhat.com>

**What type of PR is this?**
/kind feature

**What does this PR do / why we need it**:
The change is to let odo consume the latest registry library for enabling the devfile registry telemetry on client side.

**Which issue(s) this PR fixes**:
Related issue: https://github.com/devfile/api/issues/281

**PR acceptance criteria**:

- [x] Unit test 

- [x] Integration test 

- [x] Documentation 

- [x] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:
Run `odo catalog` and `odo create` commands then monitor the community registry telemetry to see if the data can be collected.

### CODE REVIEW

**Review by dharmit — CHANGES_REQUESTED** [review]
@GeekArthur WDYT about putting `telemetryClient` as a `const` in one place in the code and reuse it at places where you have currently defined it? IMO, it could go into `pkg/odo/cli/registry/util/util.go` along with what we presently have there:
```go
const (
	RegistryUser = "default"
)
```
Thoughts @feloy @valaparthvi ?

**Comment by GeekArthur** [comment]
> @GeekArthur WDYT about putting `telemetryClient` as a `const` in one place in the code and reuse it at places where you have currently defined it? IMO, it could go into `pkg/odo/cli/registry/util/util.go` along with what we presently have there:
> 
> ```go
> const (
> 	RegistryUser = "default"
> )
> ```
> 
> Thoughts @feloy @valaparthvi ?

Make sense, thanks for suggesting the shared file

**Comment by feloy** [comment]
> @GeekArthur WDYT about putting `telemetryClient` as a `const` in one place in the code and reuse it at places where you have currently defined it? IMO, it could go into `pkg/odo/cli/registry/util/util.go` along with what we presently have there:
> 
> ```go
> const (
> 	RegistryUser = "default"
> )
> ```
> 
> Thoughts @feloy @valaparthvi ?

I agree to put the constant in a common place, but the `util` package is not a place I would first go to find such a constant. Can we instead have a `consts.go` file in the `registry` package (`pkg/odo/cli/registry/consts.go)?

**Comment by dharmit** [comment]
> Can we instead have a `consts.go` file in the `registry` package (`pkg/odo/cli/registry/consts.go`)?

+1

**Comment by GeekArthur** [comment]
> > Can we instead have a `consts.go` file in the `registry` package (`pkg/odo/cli/registry/consts.go`)?
> 
> +1

`pkg/odo/cli/registry/consts.go` has circular dependency issue, so I create a separate `consts` package under ``pkg/odo/cli/registry`, please review again

**Comment by GeekArthur** [comment]
`ci/prow/psi-k8s-ibmc-integration-e2e` fails due to the following errors: 

```
[ssh:Fedora 32] ++ make bin
[ssh:Fedora 32] go: GOPATH entry cannot start with shell metacharacter '~': "~/go"
[ssh:Fedora 32] go: GOPATH entry cannot start with shell metacharacter '~': "~/go"
[ssh:Fedora 32] make: *** [Makefile:62: bin] Error 2
[ssh:Fedora 32] ++ cp -avrf ./odo '~/go/bin/'
[ssh:Fedora 32] cp: cannot stat './odo': No such file or directory
```

It seems like an test automation infrastructure issue, probably need to use absolute path instead of relative path for go

**Comment by valaparthvi** [comment]
@GeekArthur Things lgtm from code perspective, but I was unable to see any data in Devfile Registry on Segment, or was I looking in the wrong place? I tested with `odo create` and `odo catalog list components`. Can you help?

**Comment by dharmit** [comment]
> @GeekArthur Things lgtm from code perspective, but I was unable to see any data in Devfile Registry on Segment, or was I looking in the wrong place? I tested with `odo create` and `odo catalog list components`. Can you help?

I _thinik_ the telemetry data for this will show up on devfile registry side, and not on odo side. Correct me if I'm wrong @GeekArthur.

**Comment by GeekArthur** [comment]
> > @GeekArthur Things lgtm from code perspective, but I was unable to see any data in Devfile Registry on Segment, or was I looking in the wrong place? I tested with `odo create` and `odo catalog list components`. Can you help?
> 
> I _thinik_ the telemetry data for this will show up on devfile registry side, and not on odo side. Correct me if I'm wrong @GeekArthur.

Yes, the telemetry data is on devfile registry side as odo is the client that consumes registry library to interact with.
@valaparthvi You can check the telemetry data of devfile registry here: https://app.segment.com/redhat-devtools/sources/devfile-registry/overview

**Comment by valaparthvi** [comment]
>@valaparthvi You can check the telemetry data of devfile registry here: https://app.segment.com/redhat-devtools/sources/devfile-registry/overview

That is what I did before, but I did not see any data on `odo create` or `odo catalog list components`. Do you see this data on telemetry when you run these commands?

**Review by valaparthvi — APPROVED** [review]

**Comment by valaparthvi** [comment]
@dharmit can you confirm if you can see the data in Devfile Registry and maybe approve it ?

**Pull request merged**
