### PR TITLE
uncomment and fix service tests

### PR DESCRIPTION
**Pull request by kadel**
fixes https://github.com/openshift/odo/issues/1491

### CODE REVIEW

**Comment by kadel** [comment]
/retest

```
level=fatal msg="failed to initialize the cluster: Could not update servicemonitor \"openshift-controller-manager-operator/openshift-controller-manager-operator\" (306 of 307): the server does not recognize this resource, check extension API servers: timed out waiting for the condition"
```

**Comment by kadel** [comment]
ping @amitkrout @mohammedzee1000

**Comment by amitkrout** [comment]
Tested locally
/approve

**Pull request merged**
