### PR TITLE
Removing install script and update other references

### LINKED ISSUE #2914: Update failure
/kind bug

I have tried to update my odo version using the recommended `curl` command on `odo version` command and it failed with the below messages.

**Output of `odo version`:**
```
﻿﻿❯ ❯ odo version
odo v1.0.0-beta5 (4d1d5071)

Server: https://api.rh-us-east-1.openshift.com:443
OpenShift: v3.11.154
Kubernetes: v1.11.0+d4cacc0
---
A newer version of odo (version: v1.1.2) is available.
Update using your package manager, or run
curl https://raw.githubusercontent.com/openshift/odo/master/scripts/installer.sh | sh
to update manually, or visit https://github.com/openshift/odo/releases
---
If you wish to disable the update notifications, you can disable it by running
'odo preference set UpdateNotification false'

❯ curl https://raw.githubusercontent.com/openshift/odo/master/scripts/installer.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9213  100  9213    0     0  33501      0 --:--:-- --:--:-- --:--:-- 33501
# Detecting distribution...
# Detected platform: darwin-amd64
echo_stderr #
odo version "odo v1.0.0-beta5 (4d1d5071)" is already installed on your system. Running this installer script might cause issues with your current installation. If you want to install odo using this script, please remove the current installation of odo from you system.
Aborting now!
```

### PR DESCRIPTION
**Pull request by mohammedzee1000**
**What type of PR is this?**

**What does does this PR do / why we need it**:
Install script now points to releases page and odo.dev. This is so as to not break it for existing

**Which issue(s) this PR fixes**:

Fixes #2914 

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by cdrage** [comment]
Ping @kadel 

If we need this anymore :)

**Comment by dharmit** [comment]
Naive question: there's nothing but bunch of code removal on this one. Would it be a good idea to test this one when we make a new release? I'm personally not sure how to lgtm this otherwise.

@mohammedzee1000 @cdrage

**Comment by dharmit** [comment]
/test v4.4-integration-e2e
#3122 
```
 [odo]  ✗  Failed to start component with name tjvsek.
[odo] Error: Failed to create the component: unable to create or update component: unable to create Deployment tjvsek: deployments.apps "tjvsek" is forbidden: unable to create new content in namespace xvlwmkkyhw because it is being terminated
Deleting project: fckaujaqda
Running odo with args [odo project delete fckaujaqda -f]
[odo] I0601 14:58:14.038362    3850 application.go:49] Unable to list Service Catalog instances: unable to list ServiceInstances: serviceinstances.servicecatalog.k8s.io is forbidden: User "developer" cannot list resource "serviceinstances" in API group "servicecatalog.k8s.io" in the namespace "fckaujaqda"
[odo]  ⚠  Warning! Projects are deleted from the cluster asynchronously. Odo does its best to delete the project. Due to multi-tenant clusters, the project may still exist on a different node.
[odo] I0601 14:58:14.074329    3850 odo.go:72] Could not get the latest release information in time. Never mind, exiting gracefully :)
[odo]  ✓  Deleted project : fckaujaqda
Setting current dir to: /go/src/github.com/openshift/odo/tests/integration/devfile
Deleting dir: /tmp/277106978
• Failure [3.792 seconds]
odo devfile url command tests
/go/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_url_test.go:16
  Creating urls
  /go/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_url_test.go:127
    create with now flag should pass [It]
[Fail] odo devfile url command tests Creating urls [It] create with now flag should pass 
/go/src/github.com/openshift/odo/tests/helper/helper_run.go:34
Ran 60 of 60 Specs in 453.383 seconds
FAIL! -- 59 Passed | 1 Failed | 0 Pending | 0 Skipped
```
/test v4.3-integration-e2e
#2641 
```

• Failure [371.631 seconds]
odo supported images e2e tests
/go/src/github.com/openshift/odo/tests/e2escenarios/e2e_images_test.go:14
  odo supported images deployment
  /go/src/github.com/openshift/odo/tests/e2escenarios/e2e_images_test.go:83
    Should be able to verify the nodejs-8 image [It]
[Fail] odo supported images e2e tests odo supported images deployment [It] Should be able to verify the nodejs-8 image 
/go/src/github.com/openshift/odo/tests/helper/helper_generic.go:148
Ran 23 of 23 Specs in 907.321 seconds
FAIL! -- 22 Passed | 1 Failed | 0 Pending | 0 Skipped
```

**Comment by mohammedzee1000** [comment]
> Naive question: there's nothing but bunch of code removal on this one. Would it be a good idea to test this one when we make a new release? I'm personally not sure how to lgtm this otherwise.
> 
> @mohammedzee1000 @cdrage

The script is no longer usable and is infact no longer referenced by cli/docs.

**Comment by cdrage** [comment]
LGTM!

**Comment by dharmit** [comment]
@mohammedzee1000 this one needs to be rebased since #3318 has fixed an issue:
```
 • Failure [3.847 seconds]
odo devfile create command tests
/go/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_create_test.go:15
  When executing odo create with devfile component type argument and --project flag
  /go/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_create_test.go:74
    should successfully create the devfile component [It]
    /go/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_create_test.go:75
    No future change is possible.  Bailing out early after 1.077s.
      
    Running odo with args [odo create openLiberty --project snrmou]
    Expected
        <int>: 1
    to match exit code:
        <int>: 0
    /go/src/github.com/openshift/odo/tests/helper/helper_run.go:34 
```

**Pull request merged**
