### PR TITLE
Minor improvements for consistency

### LINKED ISSUE #1466: Minor updates to project README for consistency

### PR DESCRIPTION
**Pull request by sspeiche**
## What is the purpose of this change? What does it change?
Want to make clear `odo` is the cli tool and name, having Odo and odo is a little confusing.

## Was the change discussed in an issue?
Fixes #1466

## How to test changes?
With your eyes 👀

### CODE REVIEW

**Comment by girishramnani** [comment]
Just keep an eye on this PR https://github.com/redhat-developer/odo/pull/1462. Might conflict with this.

**Comment by mohammedzee1000** [comment]
Please rebase. Fix for this error is in

**Comment by cdrage** [comment]
Hey @sspeiche could we hold off on this PR for now? @Preeticp just finished a review here: https://github.com/redhat-developer/odo/pull/1462 so I'm hoping to have this merged in and then yours :+1:

**Comment by sspeiche** [comment]
> Hey @sspeiche could we hold off on this PR for now?
Sure, @girishramnani asked me to rebase and I complied

**Comment by mohammedzee1000** [comment]
Hmm this is odd, this looks like a login failed with a 404

**Comment by amitkrout** [comment]
@mohammedzee1000 So you mean after the ```oc apply...``` https://github.com/redhat-developer/odo/blob/master/scripts/configure-installer-tests-cluster.sh#L63-L78  sometimes cluster is not responsive to external route. Hence causing the failure of login as developer. 

So should we think about the increase in [timeout](https://github.com/redhat-developer/odo/blob/master/scripts/configure-installer-tests-cluster.sh#L81) for worst case scenario ?

**Comment by mohammedzee1000** [comment]
Hmm, it already waits for `2 * 30` seconds in total for login anf it appears to have fails after in test .

**Comment by mohammedzee1000** [comment]
@sspeiche can you rebase please

**Comment by amitkrout** [comment]
@sspeiche please rebase the pr.

**Comment by amitkrout** [comment]
@sspeiche Can you please rebase it

**Comment by surajnarwade** [comment]
@sspeiche , we can maybe close this, since @Preeticp is rewriting all the documentation

**Comment by sspeiche** [comment]
@girishramnani asked me to update it, so I did. Also, I'd like less "OpenShift Do" as a way to talk about `odo`. The docs for `kubectl` don't say "Kube Cuttle". Developers will know it as `odo` and "OpenShift Do" is an alternate name. I'd rather teach end users 1 name: `odo`

**Comment by Preeticp** [comment]
@sspeiche got it, we are using OpenShift Do only in the headings and titles, would that be alright?

**Comment by sspeiche** [comment]
> @sspeiche got it, we are using OpenShift Do only in the headings and titles, would that be alright? For instance, we used CDK in the doc text but for headings we use Container Development Kit, same with RHEL and so on.

@Preeticp my point is that `odo` isn't an abbreviation for a longer official product called "OpenShift Do"...the project is `odo` and "OpenShift Do" is just something we'd use as a tag line or a cute hint to remember the command.

My updates were trying to center on `odo` and only call out "OpenShift Do" as more "also affectionately referred to as OpenShift Do"

**Comment by Preeticp** [comment]
Ack @sspeiche will revert OpenShift Do to `odo` in all docs. Thanks for the confirmation.

**Comment by rkratky** [comment]
>  my point is that odo isn't an abbreviation for a longer official product called "OpenShift Do"...the project is odo and "OpenShift Do" is just something we'd use as a tag line

Thanks for the clarification, @sspeiche.

**Comment by amitkrout** [comment]
Recently @Preeticp has pushed many doc changes to master, hope the new changes has your issue addressed. If yes, @sspeiche would you please close the issue

To close this issue just pass ```/close``` in a new line in the comment

**Comment by girishramnani** [comment]
the required changes were incorporated. Closing this PR

**Pull request closed without merging**
