### PR TITLE
Added few supported container images to e2e image test

### PR DESCRIPTION
**Pull request by amitkrout**
**What type of PR is this?**
/kind feature

**What does does this PR do / why we need it**:
Added few supported container images to e2e image test. See list supported container images in https://github.com/openshift/odo-init-image/blob/master/language-scripts/image-mappings.json 
**Which issue(s) this PR fixes**:

Fixes NA, I am sending the pr directly.

**How to test changes / Special notes to the reviewer**:
```make test-e2e-images```

### CODE REVIEW

**Comment by amitkrout** [comment]
prow issue
/retest

**Comment by amitkrout** [comment]
> Maybe it'd be more interesting to retrieve the list, parse it and check images instead of harcoding the references and iterating over them manually?

@metacosm This is a good approach but currently we are hardcoding it because we do not have such command or sub command that can retrieve the supported container images for odo from the concerned registry. @girishramnani @kadel Can you please share your thoughts ?

**Comment by metacosm** [comment]
> > Maybe it'd be more interesting to retrieve the list, parse it and check images instead of harcoding the references and iterating over them manually?
> 
> @metacosm This is a good approach but currently we are hardcoding it because we do not have such command or sub command that can retrieve the supported container images for odo from the concerned registry. @girishramnani @kadel Can you please share your thoughts ?

My point, though, was that the test would retrieve the list outside of odo and then tests the images from that list, not rely on an odo command, which, by essence, might be bugged and shouldn't be relied on in a test anyway. Though, to be fair, the list retrieval code could also be bugged… Test the tests! 😉

**Comment by girishramnani** [comment]
I would find it interesting if we can parse the json output of `odo catalog list components` and then use each of the versions programmatically for testing. This would help in keeping a better api contract with json output users that “whatever we have given you as json output - all those images work”.

This will also allow us to track and detect an unsupported image that lands on the catalog.

**Comment by girishramnani** [comment]
But not sure this should be done as part of this PR

**Comment by amitkrout** [comment]
> My point, though, was that the test would retrieve the list outside of odo and then tests the images from that list, not rely on an odo command, which, by essence, might be bugged and shouldn't be relied on in a test anyway. Though, to be fair, the list retrieval code could also be bugged… Test the tests! 😉

@metacosm Then all the time we need a human effort to monitor the script and as well as odo repo for any changes with respect to supported images. That is why i was looking for a odo specific command that tells us the supported images. As @girishramnani mentioned https://github.com/openshift/odo/pull/3315#issuecomment-641838982 we can parse the catalog list for supported images to avoid human monitoring.

> I would find it interesting if we can parse the json output of odo catalog list components and then use each of the versions programmatically for testing. This would help in keeping a better api contract with json output users that “whatever we have given you as json output - all those images work”.
This will also allow us to track and detect an unsupported image that lands on the catalog.

+1, @girishramnani Here i can see the list of supported container images - https://github.com/openshift/odo-init-image/blob/master/language-scripts/image-mappings.json but in ```odo catalog list components -o json``` i don't see these container images are tagged in the output list. BTW am i looking into the right place for supported container images ?

Question - When we run ```odo component create nodejs -- context <context>``` and then ```odo push -- context <context>``` then which nodejs container image is used to build the nodejs app ? 

> But not sure this should be done as part of this PR

Yes, this will be part of a separate effort.

**Comment by girishramnani** [comment]
Seems like a good cabal topic @amitkrout to discuss not hard coding the images. 
For now this looks ok
/approve

**Comment by girishramnani** [comment]
Do open an issue to track the "scripted approach to testing images"

**Comment by prietyc123** [comment]
> When we run odo component create nodejs -- context <context> and then odo push -- context <context> then which nodejs container image is used to build the nodejs app ?

AFAIK it will by default look into `registry.access.redhat.com` registry and IMO it should build the app from there itself. If it does not find the specified image then only it will go for `docker hub` or any. 

> Yes, this will be part of a separate effort.

Yes, I really like the approach @girishramnani has suggested. This will reduce the manual efforts. And ofcourse it will require more effort and we should do it in different pr. But @amitkrout Can you please create an issue? So that we don't miss it.

**Comment by amitkrout** [comment]
https://github.com/openshift/odo/issues/3307
/test v4.3-integration-e2e

**Comment by amitkrout** [comment]
> @amitkrout Can you please create an issue? So that we don't miss it.

created https://github.com/openshift/odo/issues/3388

**Pull request merged**
