### PR TITLE
Run integration e2e test on mac and windows

### LINKED ISSUE #2540: Run e2e and integration test on windows and macOS host
[kind/Feature]

## Which functionality do you think we should add?

We can borrow macOS host on travis and windows from appveyor then only we can start our tests on these hosts.

## Why is this needed?

Not yet implemented in CI.

 - [ ] Integration tests
     - [ ] Mac OS https://github.com/redhat-developer/odo/issues/5301
     - [x] Windows https://github.com/redhat-developer/odo/issues/5300
 - [ ] e2e tests
     - [ ] Mac OS https://github.com/redhat-developer/odo/issues/5301
     - [x] Windows https://github.com/redhat-developer/odo/issues/5300

### PR DESCRIPTION
**Pull request by amitkrout**
**What type of PR is this?**
/kind feature

**What does does this PR do / why we need it**:
Integration and e2e test coverage on mac and windows
**Which issue(s) this PR fixes**:

Fixes #2540

**How to test changes / Special notes to the reviewer**:
Integration and e2e test should run on windows and mac setup in travis CI

### CODE REVIEW

**Comment by mohammedzee1000** [comment]
It appears that the env's are comping out empty. going to @openshift/openshift-team-developer-productivity-test-platform

**Comment by amitkrout** [comment]
Blocked due to #3270

**Comment by girishramnani** [comment]
@amitkrout this needs rebase, assuming the template based workflow now just has some flaky errors - can we move forward on this?

**Comment by girishramnani** [comment]
Any update on this?

**Comment by amitkrout** [comment]
> Any update on this?

Now i am unblocked via https://github.com/openshift/release/pull/9431.

**Comment by cdrage** [comment]
Any updates @amitkrout ? I'm ready to review this but unsure on the status.

**Comment by amitkrout** [comment]
> Any updates @amitkrout ? I'm ready to review this but unsure on the status.

This pr will be done by phases so that it won't break our master. I have already role out couple of prs for travis cli installation and prow job creation. 

The steps are 

- [ ] Create a prow job - https://github.com/openshift/release/pull/10942
- [ ] Install travis cli in the test container - https://github.com/openshift/odo/pull/3732
- [ ] Travis login using the github secret
- [ ] Find the specific pr travis job to run the test

**Comment by amitkrout** [comment]
Not for sprint 189
/close

**Pull request closed without merging**
