### PR TITLE
Update tests to use updated stack names

### PR DESCRIPTION
**Pull request by johnmcollier**
**What type of PR is this?**
/kind failing-test

**What does does this PR do / why we need it**:
This PR updates the devfile tests to reference the updated devfile stack names that will soon be merged. (see https://github.com/odo-devfiles/registry/pull/11 and https://github.com/openshift/odo/issues/3334). As a result of the rename, the tests the referenced the old name of the tests will fail, so they need to be updated accordingly.

**Which issue(s) this PR fixes**:

Fixes https://github.com/openshift/odo/issues/3334

**How to test changes / Special notes to the reviewer**:
Run `make test`

### CODE REVIEW

**Comment by prietyc123** [comment]
@johnmcollier pr needs rebase

**Comment by maysunfaisal** [comment]
/hold
I didn't know that writing`looks good` adds the label 😮 
Wait for @johnmcollier to indicate when to unhold

**Pull request merged**
