### PR TITLE
devfile watch Interation test on kubernetes cluster using travis CI

### PR DESCRIPTION
**Pull request by prietyc123**
What type of PR is this?

/kind test

What does does this PR do / why we need it:

Runs the devfile watch integration test on kubernetes cluster.

Which issue(s) this PR fixes:

Fixes - Part of #2752

How to test changes / Special notes to the reviewer:

The test should pass on travis with make test-cmd-devfile-watch command.

### CODE REVIEW

**Comment by prietyc123** [comment]
prow failure

/retest

**Comment by amitkrout** [comment]
prow failure
/retest

**Comment by prietyc123** [comment]
Flake refer to issue : https://github.com/openshift/odo/issues/2929

```
Running odo with args [odo service create etcdoperator.v0.9.4 --crd EtcdCluster]
[odo] Deploying service of type: etcdoperator.v0.9.4
[odo]  •  Deploying service  ...
[odo] 
 ✓  Deploying service [96ms]
[odo]  ✓  Service 'etcdoperator.v0.9.4' was created
[odo] 
[odo] Progress of the provisioning will not be reported and might take a long time
[odo] You can see the current status by executing 'odo service list'
[odo] Optionally, link etcdoperator.v0.9.4 to your component by running: 'odo link <component-name>'
Running oc with args [oc get pods -n ci-operator-hub-project]
[oc] NAME                             READY   STATUS     RESTARTS   AGE
[oc] etcd-operator-7987f694f7-lgz2c   3/3     Running    0          88m
[oc] example-2qqbbfzcrf               0/1     Init:0/1   0          1s
Running oc with args [oc get pods example-2qqbbfzcrf -o template="{{.status.phase}}" -n ci-operator-hub-project]
[oc] "Pending"Running oc with args [oc get pods example-2qqbbfzcrf -o template="{{.status.phase}}" -n ci-operator-hub-project]
[oc] "Pending"Running oc with args [oc get pods example-2qqbbfzcrf -o template="{{.status.phase}}" -n ci-operator-hub-project]
[oc] "Pending"Running oc with args [oc get pods example-2qqbbfzcrf -o template="{{.status.phase}}" -n ci-operator-hub-project]
[oc] "Pending"Running oc with args [oc get pods example-2qqbbfzcrf -o template="{{.status.phase}}" -n ci-operator-hub-project]
[oc] "Pending"Running oc with args [oc get pods example-2qqbbfzcrf -o template="{{.status.phase}}" -n ci-operator-hub-project]
[oc] "Pending"Running oc with args [oc get pods example-2qqbbfzcrf -o template="{{.status.phase}}" -n ci-operator-hub-project]
[oc] "Pending"Running oc with args [oc get pods example-2qqbbfzcrf -o template="{{.status.phase}}" -n ci-operator-hub-project]
[oc] "Pending"Running oc with args [oc get pods example-2qqbbfzcrf -o template="{{.status.phase}}" -n ci-operator-hub-project]
[oc] "Pending"Running oc with args [oc get pods example-2qqbbfzcrf -o template="{{.status.phase}}" -n ci-operator-hub-project]
[oc] "Pending"Running oc with args [oc get pods example-2qqbbfzcrf -o template="{{.status.phase}}" -n ci-operator-hub-project]
[oc] "Pending"Running oc with args [oc get pods example-2qqbbfzcrf -o template="{{.status.phase}}" -n ci-operator-hub-project]
[oc] "Pending"Running oc with args [oc get pods example-2qqbbfzcrf -o template="{{.status.phase}}" -n ci-operator-hub-project]
• Failure [16.352 seconds]
odo service command tests for OperatorHub
/go/src/github.com/openshift/odo/tests/integration/operatorhub/cmd_service_test.go:17
  When creating an operator backed service
  /go/src/github.com/openshift/odo/tests/integration/operatorhub/cmd_service_test.go:34
    should be able to create EtcdCluster from its alm example [It]
    /go/src/github.com/openshift/odo/tests/integration/operatorhub/cmd_service_test.go:35
    Timed out after 1.004s.
      
    Running oc with args [oc get pods example-2qqbbfzcrf -o template="{{.status.phase}}" -n ci-operator-hub-project]
    Expected process to exit.  It did not.
    /go/src/github.com/openshift/odo/tests/helper/helper_generic.go:53
```

/retest

**Pull request merged**
