### PR TITLE
Remove the unused step in configure-installer-tests-cluster-s390x.sh.

### PR DESCRIPTION
**Pull request by zhengxiaomei123**
**What type of PR is this?**
> /kind bug

**What does does this PR do / why we need it**:
This removes the getting secret step for my project .
**Which issue(s) this PR fixes**:

Fixes #?

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [ ] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Review by dharmit — APPROVED** [review]
/lgtm

**Review by rnapoles-rh — COMMENTED** [review]
/lgtm

**Pull request merged**
