### PR TITLE
Adds docs for dev.push.path attribute

### PR DESCRIPTION
**Pull request by dharmit**
**What type of PR is this?**
/kind documentation

**What does this PR do / why we need it**:
Updates odo.dev

**Which issue(s) this PR fixes**:

Fixes - NA

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [x] Documentation 

- [x] Update changelog

- [ ] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by girishramnani** [comment]
update the change log maybe @dharmit?
/hold

**Comment by dharmit** [comment]
> update the change log maybe @dharmit?
> /hold

It's already present under https://github.com/openshift/odo/blob/main/Changelog.md#221.

**Pull request merged**
