### PR TITLE
Fixes ephemeral storage mount issue

### PR DESCRIPTION
**Pull request by mik-dass**
**What type of PR is this?**

/kind bug

**What does this PR do / why we need it**:

It fixes the ephemeral storage mount issue.

**Which issue(s) this PR fixes**:

Fixes NA

**PR acceptance criteria**:

- [ ] Unit test 

- [X] Integration test 

- [ ] Documentation 

- [ ] Update changelog

- [ ] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

- Trigger `odo preference set ephemeral false -f`
- Create and push a odo component `odo create nodejs` and `odo push`
- Check the created deployment, the volume `odo-projects` should have a persistent volume claim which points to the newly created source pvc for the component.

### CODE REVIEW

**Comment by kadel** [comment]
> * Trigger `odo preference set ephemeral true -f`
> * Create and push a odo component `odo create nodejs` and `odo push`
> * Check the created deployment, the volume `odo-projects` should have a persistent volume claim which points to the newly created source pvc for the component.

If `ephemeral=true` than the odo-projects volume should be `emptyDir`
if `ephemeral=false` then the odo-projects volume should be `persistentVolumeClaim`

**Comment by mik-dass** [comment]
> If `ephemeral=true` than the odo-projects volume should be `emptyDir`
> if `ephemeral=false` then the odo-projects volume should be `persistentVolumeClaim` 

Fixed the notes

**Comment by dharmit** [comment]
Maybe naive questions, but I'll ask anyway since I'm a bit confused.

* I first set ephemeral to false so that odo uses PVC. 
* Next, I pushed a component for [nodejs-ex](https://github.com/odo-devfiles/nodejs-ex) repo.

What I'm seeing in the `kubectl get pod` is that there are two volumes using the same pvc:
```json
{
    "name": "odo-projects-nodejs-nodejs-ex-xccm-app-vol",
    "persistentVolumeClaim": {
      "claimName": "odo-projects-nodejs-nodejs-ex-xccm-app"
    }
  },
  {
    "name": "odo-projects",
    "persistentVolumeClaim": {
      "claimName": "odo-projects-nodejs-nodejs-ex-xccm-app"
    }
  },
  {
    "emptyDir": {},
    "name": "odo-supervisord-shared-data"
  },
```

And the container's using only `odo-projects`:
```json
[
  {
    "mountPath": "/project",
    "name": "odo-projects"
  },
  {
    "mountPath": "/opt/odo/",
    "name": "odo-supervisord-shared-data"
  },
  {
    "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount",
    "name": "kube-api-access-c9g6t",
    "readOnly": true
  }
]
```
It makes sense that the container's using only one `volumeMount`. But why is odo creating two volumes pointing to the same PVC?

**Comment by mik-dass** [comment]
> What I'm seeing in the kubectl get pod is that there are two volumes using the same pvc:

Fixed

> @mik-dass can you please also update Changelog.md?

Updated

**Comment by mik-dass** [comment]
```
should list current empty project in json format [It]
  /go/src/github.com/openshift/odo/tests/integration/project/cmd_project_test.go:51
  Expected
      
      <string>: {"apiVersion":"odo.dev/v1alpha1","items":[{"apiVersion":"odo.dev/v1alpha1","kind":"Project","metadata":{"creationTimestamp":null,"name":"myproject","namespace":"myproject"},"spec":{},"status":{"active":false}},{"apiVersion":"odo.dev/v1alpha1","kind":"Project","metadata":{"creationTimestamp":null,"name":"nodejs-12","namespace":"nodejs-12"},"spec":{},"status":{"active":false}},{"apiVersion":"odo.dev/v1alpha1","kind":"Project","metadata":{"creationTimestamp":null,"name":"nodejs-12-rhel7","namespace":"nodejs-12-rhel7"},"spec":{},"status":{"active":false}},{"apiVersion":"odo.dev/v1alpha1","kind":"Project","metadata":{"creationTimestamp":null,"name":"nodejs-14","namespace":"nodejs-14"},"spec":{},"status":{"active":false}},{"apiVersion":"odo.dev/v1alpha1","kind":"Project","metadata":{"creationTimestamp":null,"name":"odo-operator-test","namespace":"odo-operator-test"},"spec":{},"status":{"active":false}},{"apiVersion":"odo.dev/v1alpha1","kind":"Project","metadata":{"creationTimestamp":null,"name":"openjdk-11","namespace":"openjdk-11"},"spec":{},"status":{"active":false}},{"apiVersion":"odo.dev/v1alpha1","kind":"Project","metadata":{"creationTimestamp":null,"name":"openjdk-11-rhel8","namespace":"openjdk-11-rhel8"},"spec":{},"status":{"active":false}}],"kind":"List","metadata":{}}
  to contain substring
      <string>: {"apiVersion":"odo.dev/v1alpha1","kind":"Project","metadata":{"creationTimestamp":null,"name":"cmd-project-test51krh","namespace":"cmd-project-test51krh"},"spec":{},"status":{"active":true}}
```
/retest

**Comment by dharmit** [comment]
@mik-dass @kadel can you please share your thoughts on https://github.com/openshift/odo/pull/4979#issuecomment-896522776?

**Comment by dharmit** [comment]
> > What I'm seeing in the kubectl get pod is that there are two volumes using the same pvc:
> 
> Fixed

👍🏾 

@mik-dass can you rebase?

**Comment by mik-dass** [comment]
> @mik-dass can you rebase?

Rebased.

**Comment by dharmit** [comment]
There's way too many failures. Don't know if it's related to the PR.

/test v4.8-integration-e2e

**Pull request merged**
