### PR TITLE
add new reviewers to top level OWNERS

### PR DESCRIPTION
**Pull request by kadel**
Adding  @johnmcollier, @maysunfaisal, @rajivnathan as reviewers.

Are you guys ok with becoming reviewers?
What it means is that you will be able to `/lgtm` PRs.

General info on how reviewers and approvers work can be found at https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md#code-review-using-owners-files

### CODE REVIEW

**Comment by kadel** [comment]
> The following users are mentioned in OWNERS file(s) but are not members of the openshift org.

hmm :-(

**Comment by girishramnani** [comment]
@kadel can we add them as members to the org?

**Pull request merged**
