### PR TITLE
WIP [skip ci] Updating prow scripts to skip ci if commits contain keyword

### PR DESCRIPTION
**Pull request by mohammedzee1000**
Signed-off-by: Mohammed Zeeshan Ahmed <mohammed.zee1000@gmail.com>

**What type of PR is this?**
> Uncomment only one ` /kind` line, and delete the rest.
> For example, `> /kind bug` would simply become: `/kind bug`

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind failing-test
> /kind feature
> /kind flake
> /kind code-refactoring
>
> Documentation changes: Please include [skip ci] in your commit message as well
> /kind documentation
> [skip ci]

**What does does this PR do / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #?

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by girishramnani** [comment]
@mohammedzee1000 any update on this PR?

**Comment by girishramnani** [comment]
Do we need this? Isnt the prow skip CI in PR description is good enough?

**Comment by mohammedzee1000** [comment]
No its not very easy to do that either

**Comment by mohammedzee1000** [comment]
I will get on this asap

**Comment by girishramnani** [comment]
Let’s focus on this later, we have more important issues.
Closing this for now

**Pull request closed without merging**
