### PR TITLE
Fix --namespace flag bug for odo create

### LINKED ISSUE #2796: odo create support both --project and --namespace
/kind bug

## What versions of software are you using?

**Operating System:**
```
MacOS Catalina
```

**Output of `odo version`:**
```
odo v1.1.1 (1eb878ea2)
```

## Expected behavior
Currently `odo create` do support `--namespace` but it doesn't work properly. `odo create` should support both `--project` (for OpenShift user) and `--namespace` (for k8s user) when experimental flag enabled, and the priority of `--namespace` should be higher than `--project` if user pass two flags together with different values although that use case is almost unlikely.

### PR DESCRIPTION
**Pull request by GeekArthur**
Signed-off-by: jingfu wang <jingfu.j.wang@ibm.com>

**What type of PR is this?**
/kind bug

**What does does this PR do / why we need it**:
`odo create` with `--namespace` doesn't work properly, this PR fix the issue.

**Which issue(s) this PR fixes**:
Fixes #2796

### CODE REVIEW

**Comment by GeekArthur** [comment]
@johnmcollier @kadel Can you please review this PR? Thanks

**Comment by GeekArthur** [comment]
@amitkrout Yup, I have the same thoughts before, but I hesitate as it may create merge conflict with this PR https://github.com/openshift/odo/pull/2771, that being said, let me push one more commit to add the integration test

**Comment by GeekArthur** [comment]
@amitkrout I added the integration tests, please review again, thanks!

**Comment by amitkrout** [comment]
@GeekArthur Please rebase. 
 ```tests/integration/cmd_devfile_create_test.go``` has been moved to ```tests/integration/devfile/cmd_devfile_create_test.go```

**Comment by kadel** [comment]
> However i can see missing thing like the command is not updated in UX, i mean `odo create -h` has nothing to show for this command.

@amitkrout what do you mean? Both `--project` and `--namespace` are there
```
▶ ODO_EXPERIMENTAL=false odo create --help

Create a configuration describing a component.

 If a component name is not provided, it'll be auto-generated.

 A full list of component types that can be deployed is available using: 'odo catalog list'

 By default, builder images (component type) will be used from the current namespace. You can explicitly supply a namespace by using: odo create namespace/name:version If version is not specified by default, latest will be chosen as the version.

Usage:
  odo create <component_type> [component_name] [flags]

Examples:
  # Create new Node.js component with the source in current directory.
  odo create nodejs

  # Create new Node.js component named 'frontend' with the source in './frontend' directory
  odo create nodejs frontend --context ./frontend

  # Create new Java component with binary named sample.jar in './target' directory
  odo create java:8  --binary target/sample.jar

  # Create new Node.js component with source from remote git repository
  odo create nodejs --git https://github.com/openshift/nodejs-ex.git

  # Create new Node.js component with custom ports, additional environment variables and memory and cpu limits
  odo create nodejs --port 8080,8100/tcp,9100/udp --env key=value,key1=value1 --memory 4Gi --cpu 2

Flags:
      --app string          Application, defaults to active application
  -b, --binary string       Create a binary file component component using given artifact. Works only with Java components. File needs to be in the context directory.
      --context string      Use given context directory as a source for component settings
      --cpu string          Amount of cpu to be allocated to the component. ex. 100m or 0.1 (sets min-cpu and max-cpu to this value)
      --env stringSlice     Environmental variables for the component. For example --env VariableName=Value
  -g, --git string          Create a git component using this repository.
  -h, --help                Help for create
      --max-cpu string      Limit maximum amount of cpu to be allocated to the component. ex. 1
      --max-memory string   Limit maximum amount of memory to be allocated to the component. ex. 100Mi
      --memory string       Amount of memory to be allocated to the component. ex. 100Mi (sets min-memory and max-memory to this value)
      --min-cpu string      Limit minimum amount of cpu to be allocated to the component. ex. 100m
      --min-memory string   Limit minimum amount of memory to be allocated to the component. ex. 100Mi
  -n, --namespace string    Create devfile component under specific namespace
      --now                 Push changes to the cluster immediately
  -p, --port stringSlice    Ports to be used when the component is created (ex. 8080,8100/tcp,9100/udp)
      --project string      Project, defaults to active project
  -r, --ref string          Use a specific ref e.g. commit, branch or tag of the git repository

Additional Flags:
  -v, --v Level              Log level for V logs. Level varies from 0 to 9 (default 0).
      --vmodule moduleSpec   Comma-separated list of pattern=N settings for file-filtered logging
```

**Comment by GeekArthur** [comment]
> @GeekArthur Thanks for adding integration test.
> 
> However i can see missing thing like the command is not updated in UX, i mean `odo create -h` has nothing to show for this command.
> 
> other observation like
> 
> ```
> $ odo create openLiberty --namespace test123
>  ✓  Checking if the specified component type is supported devfile component type [180272ns]
>  ✓  Validating component [102178ns]
> Please use `odo push` command to create the component with source deployed
> 
> $ tree -a .
> .
> ├── .odo
> │   └── env
> │       └── env.yaml
> └── devfile.yaml
> 2 directories, 2 files
> ```
> 
> The same above structure is being observed with our regular odo command `odo create nodejs --project test123`. Seems it has conflict with regular odo component config.yaml as well as the component dir structure.
> 
> Ping @kadel @girishramnani

@amitkrout We have both `--project` and `--namespace` flags in `odo create -h` as @kadel shows above, can you explain more about the concern?

Actually this file system structure
```
├── .odo
│   └── env
│       └── env.yaml
└── devfile.yaml
```
is there for a long time, it shares the `.odo` folder with s2i component but I think they are mutually exclusive since we have the validation code to ensure they can't be created at the same

@amitkrout Also integration tests are moved, please review again

**Comment by amitkrout** [comment]
> > However i can see missing thing like the command is not updated in UX, i mean `odo create -h` has nothing to show for this command.
> 
> @amitkrout what do you mean? Both `--project` and `--namespace` are there
> 
> ```
> ▶ ODO_EXPERIMENTAL=false odo create --help
> 
> Create a configuration describing a component.
> 
>  If a component name is not provided, it'll be auto-generated.
> 
>  A full list of component types that can be deployed is available using: 'odo catalog list'
> 
>  By default, builder images (component type) will be used from the current namespace. You can explicitly supply a namespace by using: odo create namespace/name:version If version is not specified by default, latest will be chosen as the version.
> 
> Usage:
>   odo create <component_type> [component_name] [flags]
> 
> Examples:
>   # Create new Node.js component with the source in current directory.
>   odo create nodejs
> 
>   # Create new Node.js component named 'frontend' with the source in './frontend' directory
>   odo create nodejs frontend --context ./frontend
> 
>   # Create new Java component with binary named sample.jar in './target' directory
>   odo create java:8  --binary target/sample.jar
> 
>   # Create new Node.js component with source from remote git repository
>   odo create nodejs --git https://github.com/openshift/nodejs-ex.git
> 
>   # Create new Node.js component with custom ports, additional environment variables and memory and cpu limits
>   odo create nodejs --port 8080,8100/tcp,9100/udp --env key=value,key1=value1 --memory 4Gi --cpu 2
> 
> Flags:
>       --app string          Application, defaults to active application
>   -b, --binary string       Create a binary file component component using given artifact. Works only with Java components. File needs to be in the context directory.
>       --context string      Use given context directory as a source for component settings
>       --cpu string          Amount of cpu to be allocated to the component. ex. 100m or 0.1 (sets min-cpu and max-cpu to this value)
>       --env stringSlice     Environmental variables for the component. For example --env VariableName=Value
>   -g, --git string          Create a git component using this repository.
>   -h, --help                Help for create
>       --max-cpu string      Limit maximum amount of cpu to be allocated to the component. ex. 1
>       --max-memory string   Limit maximum amount of memory to be allocated to the component. ex. 100Mi
>       --memory string       Amount of memory to be allocated to the component. ex. 100Mi (sets min-memory and max-memory to this value)
>       --min-cpu string      Limit minimum amount of cpu to be allocated to the component. ex. 100m
>       --min-memory string   Limit minimum amount of memory to be allocated to the component. ex. 100Mi
>   -n, --namespace string    Create devfile component under specific namespace
>       --now                 Push changes to the cluster immediately
>   -p, --port stringSlice    Ports to be used when the component is created (ex. 8080,8100/tcp,9100/udp)
>       --project string      Project, defaults to active project
>   -r, --ref string          Use a specific ref e.g. commit, branch or tag of the git repository
> 
> Additional Flags:
>   -v, --v Level              Log level for V logs. Level varies from 0 to 9 (default 0).
>       --vmodule moduleSpec   Comma-separated list of pattern=N settings for file-filtered logging
> ```

Ahh, my bad. Actually i was searching in the example section. As this is a key flag for creation of odo devfile component, so thought there should be an example for better user experience. I have created a separate issue #2812 to track devfile UX issues.

@kadel As per the command you executed ```ODO_EXPERIMENTAL=false odo create --help``` if you are seeing ```--namespace``` flag then there is problem because namespace flag should not be displayed when experimental is disable. Can you please cross verify the command again. 

Ideally ```ODO_EXPERIMENTAL=true odo create --help``` should be the command to see ```--namespace``` flag in UX.

**Comment by amitkrout** [comment]
prow issue
/test v4.1-integration-e2e-benchmark

**Comment by amitkrout** [comment]
> > @GeekArthur Thanks for adding integration test.
> > However i can see missing thing like the command is not updated in UX, i mean `odo create -h` has nothing to show for this command.
> > other observation like
> > ```
> > $ odo create openLiberty --namespace test123
> >  ✓  Checking if the specified component type is supported devfile component type [180272ns]
> >  ✓  Validating component [102178ns]
> > Please use `odo push` command to create the component with source deployed
> > 
> > $ tree -a .
> > .
> > ├── .odo
> > │   └── env
> > │       └── env.yaml
> > └── devfile.yaml
> > 2 directories, 2 files
> > ```
> > 
> > 
> > The same above structure is being observed with our regular odo command `odo create nodejs --project test123`. Seems it has conflict with regular odo component config.yaml as well as the component dir structure.
> > Ping @kadel @girishramnani
> 
> @amitkrout We have both `--project` and `--namespace` flags in `odo create -h` as @kadel shows above, can you explain more about the concern?
> 
> Actually this file system structure
> 
> ```
> ├── .odo
> │   └── env
> │       └── env.yaml
> └── devfile.yaml
> ```
> 
> is there for a long time, it shares the `.odo` folder with s2i component but I think they are mutually exclusive since we have the validation code to ensure they can't be created at the same

@GeekArthur Let me put in this way 

I am just enable experimental along with regular nodejs odo create command
``` 
$ ODO_EXPERIMENTAL=true odo create nodejs --context ../tests/examples/source/nodejs/
 ✓  Checking if the specified component type is supported devfile component type [164155ns]
 ✓  Validating component [67410ns]

Please use `odo push` command to create the component with source deployed
```

Expectation:
Nodejs component should be created along with component dir in context dir

```
$ ls -a ../tests/examples/source/nodejs/
.               ..              package.json    server.js
```
No component dir i mean ```.odo``` not found in context dir

Actual:

All the component configuration found the the same dir from where i launches the command

```
$ tree -a 
.
├── .odo
│   └── env
│       └── env.yaml
└── devfile.yaml
```
Why a this configuration files are created for regular odo component create command ?

Seems regular java component works but not properly
```
$ ODO_EXPERIMENTAL=true odo create java --context ../tests/examples/source/openjdk/
 ✗  Checking if the specified component type is supported devfile component type [60904ns]   <-- Why its checking for dev file support ?

Please run 'odo catalog list components' for a list of supported devfile component types
 ✓  Validating component [655ms]

Please use `odo push` command to create the component with source deployed
````
$ ls -a ../tests/examples/source/openjdk/
.               ..          src.   .odo      pom.xml
```

May be you need to handle devfile component create just by passing devfile subcommand. For example
```
odo create devfile <component> --namespace test
```
So that it will be easy to distinguish between devfile and regular command.

**Comment by amitkrout** [comment]
> > > @GeekArthur Thanks for adding integration test.
> > > However i can see missing thing like the command is not updated in UX, i mean `odo create -h` has nothing to show for this command.
> > > other observation like
> > > ```
> > > $ odo create openLiberty --namespace test123
> > >  ✓  Checking if the specified component type is supported devfile component type [180272ns]
> > >  ✓  Validating component [102178ns]
> > > Please use `odo push` command to create the component with source deployed
> > > 
> > > $ tree -a .
> > > .
> > > ├── .odo
> > > │   └── env
> > > │       └── env.yaml
> > > └── devfile.yaml
> > > 2 directories, 2 files
> > > ```
> > > 
> > > 
> > > The same above structure is being observed with our regular odo command `odo create nodejs --project test123`. Seems it has conflict with regular odo component config.yaml as well as the component dir structure.
> > > Ping @kadel @girishramnani
> > 
> > 
> > @amitkrout We have both `--project` and `--namespace` flags in `odo create -h` as @kadel shows above, can you explain more about the concern?
> > Actually this file system structure
> > ```
> > ├── .odo
> > │   └── env
> > │       └── env.yaml
> > └── devfile.yaml
> > ```
> > 
> > 
> > is there for a long time, it shares the `.odo` folder with s2i component but I think they are mutually exclusive since we have the validation code to ensure they can't be created at the same
> 
> @GeekArthur Let me put in this way
> 
> I just enable experimental along with regular nodejs odo create command
> 
> ```
> $ ODO_EXPERIMENTAL=true odo create nodejs --context ../tests/examples/source/nodejs/
>  ✓  Checking if the specified component type is supported devfile component type [164155ns]
>  ✓  Validating component [67410ns]
> 
> Please use `odo push` command to create the component with source deployed
> ```
> 
> Expectation:
> Nodejs component should be created along with component dir in context dir
> 
> ```
> $ ls -a ../tests/examples/source/nodejs/
> .               ..              package.json    server.js
> ```
> 
> No component dir i mean `.odo` not found in context dir
> 
> Actual:
> 
> All the component configuration found the the same dir from where i launches the command
> 
> ```
> $ tree -a 
> .
> ├── .odo
> │   └── env
> │       └── env.yaml
> └── devfile.yaml
> ```
> 
> Why a this configuration files are created for regular odo component create command ?
> 
> Seems regular java component works but not properly
> 
> ```
> $ ODO_EXPERIMENTAL=true odo create java --context ../tests/examples/source/openjdk/
>  ✗  Checking if the specified component type is supported devfile component type [60904ns]   <-- Why its checking for dev file support ?
> 
> Please run 'odo catalog list components' for a list of supported devfile component types
>  ✓  Validating component [655ms]
> 
> Please use `odo push` command to create the component with source deployed
> 
> $ ls -a ../tests/examples/source/openjdk/
> .               ..          src.   .odo      pom.xml
> ```
> 
> May be you need to handle devfile component create just by passing devfile subcommand. For example
> 
> ```
> odo create devfile <component> --namespace test
> ```
> 
> So that it will be easy to distinguish between devfile and regular command.

Found the same issue on master aswell. Issue created - #2813

**Comment by amitkrout** [comment]
prow issue
/test v4.1-integration-e2e-benchmark

**Comment by GeekArthur** [comment]
@amitkrout I see what you mean, thanks for your explanations and the two issues you open. I can open separate PRs to resolve the two issues as they are separate issues (this PR only fixes the --namespace issue)

To summarize the expected implementations of two issues here:

Devfile UX improvements with experimental mode enabled (https://github.com/openshift/odo/issues/2812)
- Add examples to the help page
- Remove --namespace when experimental mode is disabled

Directory structure issue with experimental mode enabled (https://github.com/openshift/odo/issues/2813)
- I can describe the current design and answer your question under the issue and we can discuss there directly

@amitkrout Given this issue is only fixes the --namespace and the fix isn't directly related with the two issues above, can you review/approve this PR only again? Thanks

**Comment by GeekArthur** [comment]
@amitkrout @kadel 
Just confirm the `--namespace` won't be displayed with experimental mode disables because of this line: https://github.com/openshift/odo/blob/master/pkg/odo/cli/component/create.go#L721, so just need to add examples to the help page.

**Pull request merged**
