### PR TITLE
Fix typo in app test file

### PR DESCRIPTION
**Pull request by prietyc123**
## What is the purpose of this change? What does it change?

Typo Fix
## Was the change discussed in an issue?
No

## How to test changes?

Check the spelling of ```Successfully``` in file.

### CODE REVIEW

**Comment by prietyc123** [comment]
#2088 
 /test v4.1-integration

**Comment by mik-dass** [comment]
```
•  Retrieving component data  ...
[odo]  ✓  Retrieving component data [149ms]
[odo]  •  Triggering build from git  ...
[odo]  ✓  Triggering build from git [82ms]
[odo]  •  Waiting for build to finish  ...
[odo]  ✓  Waiting for build to finish [55s]
[odo]  •  Applying configuration  ...
[odo]  ✗  Failed To Update Config To Component Deployed
[odo]  ✗  Applying configuration [79ms]
```
/retest

**Comment by amitkrout** [comment]
just a typo fix
/approve
/lgtm

**Pull request merged**
