### PR TITLE
Fixes catalog list services for minishift

### LINKED ISSUE #4376: "odo catalog list services" fails on minishift
/kind bug

## What versions of software are you using?

**Operating System:** Fedora

**Output of `odo version`:** `master`

## How did you run odo exactly?
* Enabled Service Catalog on minishift.
* Executed `odo catalog list services`

## Actual behavior
```sh
$ odo catalog list services
 ✗  clusterserviceversions.operators.coreos.com is forbidden: User "developer" cannot list clusterserviceversions.operators.coreos.com in the namespace "myproject": no RBAC policy matched
```

## Expected behavior
odo should have ignored unavailability of CSVs (or Operators) on minishift and shown services available through Service Catalog instead.

### PR DESCRIPTION
**Pull request by dharmit**
**What type of PR is this?**
/kind bug

**What does this PR do / why we need it**:
$subject

**Which issue(s) this PR fixes**:

Fixes #4376

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [x] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:
`odo catalog list services` should pass on all the three platforms:
* Kubernetes (minikube)
* OCP 4.x (CRC)
* OCP 3.11 (minishift)

### CODE REVIEW

**Comment by dharmit** [comment]
Unit test failure:
```
golangci-lint run ./... --timeout 5m
pkg/odo/cli/catalog/list/services.go:44:58: S1002: should omit comparison to bool constant, can be simplified to `!csvSupport` (gosimple)
		} else if csvSupport, _ := o.KClient.IsCSVSupported(); csvSupport == false {
```

**Comment by anandrkskd** [comment]
I have tested PR on openshift 3.11(minishift) and it's passing successfully.

**Pull request merged**
