### PR TITLE
Cleaning up OpenShift CI files

### PR DESCRIPTION
**Pull request by amitkrout**
**What kind of PR is this?**

/kind cleanup
/kind test

**What does does this PR do / why we need it**:
Cleaning up openshiftci presubmit files.
**Which issue(s) this PR fixes**:

Fixes - No, however cleanup is needed after #2401 went in

**How to test changes / Special notes to the reviewer**:
OpenShift CI should pass

### CODE REVIEW

**Comment by amitkrout** [comment]
```
 [odo]  ✗  Failed to create component with name nodejs. Please use `odo config view` to view settings used to create component. Error: unable to wait for build nodejs-myapp-1 to run: timed out waiting for the condition 
```
/test v4.1-integration-e2e-benchmark

**Comment by cdrage** [comment]
LGTM.
/lgtm

**Comment by amitkrout** [comment]
#2088 
/test v4.1-integration-e2e-benchmark

**Pull request merged**
