### PR TITLE
Switch from glide to go mod

### PR DESCRIPTION
**Pull request by kadel**
**What type of PR is this?**

/kind cleanup
/kind code-refactoring

**What does does this PR do / why we need it**:
Glide is starting to create a lot of problems.
For example, I was not able to figure out how to vendor package that uses go mod versioning like for example`"github.com/go-git/go-git/v5"`. Based on issues on glide repo it looks like it is not supported an it never will be because glide is no longer maintained.

I know that this is not the best time to introduce something new, but without this, I'm not able to move forward with https://github.com/openshift/odo/pull/3867

**Which issue(s) this PR fixes**:

Fixes https://github.com/openshift/odo/issues/2585
Automatically fixes https://github.com/openshift/odo/issues/3700

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [ ] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by girishramnani** [comment]
looks good and deosn't break the tests
/lgtm

**Comment by kadel** [comment]
> /hold
> need to resolve cross-compiling issues (`-mod=vendor` is not applied there)

resolved 
/hold cancel

**Review by mohammedzee1000 — APPROVED** [review]
Looking good

/lgtm

**Pull request merged**
