### PR TITLE
Add changelogs

### PR DESCRIPTION
**Pull request by valaparthvi**
**What type of PR is this?**
/kind documentation

**What does this PR do / why we need it**:
This PR adds information about important features, tests, documentation and bug fixes for the new release.
**Which issue(s) this PR fixes**:
Fixes #?

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [X] Update changelog

- [ ] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Review by dharmit — COMMENTED** [review]
/approve

**Comment by valaparthvi** [comment]
/override ci/prow/v4.7-integration-e2e
/override ci/prow/psi-unit-test-mac
/override ci/prow/psi-kubernetes-integration-e2e
/override  ci/prow/psi-unit-test-windows

This is a doc PR and it doesn't require any testing.

**Pull request merged**
