### PR TITLE
remove --app, --component and --project from odo url

### PR DESCRIPTION
**Pull request by girishramnani**
## What is the purpose of this change? What does it change?
see $SUBJECT

## Was the change discussed in an issue?
part of https://github.com/openshift/odo/issues/2243

## How to test changes?
```
odo url create --help
```
shouldn't have the flags

### CODE REVIEW

**Comment by kadel** [comment]
Shouldn't we also remove all the logic that is using those flags?

**Comment by girishramnani** [comment]
Sure, But I think --component flag is still used in link and unlink and service catalog uses the other two

**Comment by girishramnani** [comment]
Interestingly the logic related to those flags has been already removed

**Comment by girishramnani** [comment]
so after going through the code, I figured out the reason. The `--component`, `--app` and `--project` flags are populated when we initialise a `NewContext`.
https://github.com/openshift/odo/blob/4eee157aa9eb5d660d79b516a7e18328b6728d46/pkg/odo/genericclioptions/context.go#L254-L277

This code is common among all commands and as `odo link, unlink and service` still use these flags we cannot remove that code.
@kadel

**Comment by kadel** [comment]
> so after going through the code, I figured out the reason. The `--component`, `--app` and `--project` flags are populated when we initialise a `NewContext`.
> https://github.com/openshift/odo/blob/4eee157aa9eb5d660d79b516a7e18328b6728d46/pkg/odo/genericclioptions/context.go#L254-L277
> 
> This code is common among all commands and as `odo link, unlink and service` still use these flags we cannot remove that code.
> @kadel

ok, that makes sense

**Comment by girishramnani** [comment]
This PR removes flags which might affect other projects dependent on odo so added a label so the release manager adds this PR in the release notes

**Comment by amitkrout** [comment]
#2204

**Pull request merged**
