### PR TITLE
Updates associated with OL App Stack Intro changes

### PR DESCRIPTION
**Pull request by mezarin**
**What type of PR is this?**
> Uncomment only one ` /kind` line, and delete the rest.
> For example, `> /kind bug` would simply become: `/kind bug`

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind failing-test
> /kind feature
> /kind flake
> /kind code-refactoring
>
> Documentation changes: CI will automatically skip test runs if it is a doc related change.

/kind documentation

**What does this PR do / why we need it**:

This PR updates the documentation that references the Open Liberty stack intro application (https://github.com/OpenLiberty/application-stack-intro.git). There was a recent change to the mentioned application that affects how an odo component is created.

**Which issue(s) this PR fixes**:

Fixes #?
There is no issue for this PR. Please let me know if one is needed for this small doc update.

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [x] Documentation 

- [ ] Update changelog

- [x] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:
N/A

### CODE REVIEW

**Comment by mezarin** [comment]
FYI @scottkurz

**Review by scottkurz — COMMENTED** [review]
Just mentioning my #4720 includes this same change basically and also a change to use the endpoint in the devfile.

**Comment by dharmit** [comment]
@mezarin @scottkurz 

> Just mentioning my #4720 includes this same change basically and also a change to use the endpoint in the devfile.

In that case, which one should we prioritize? If we merge your PR, the same changes proposed in this PR also get in along with more changes. Should we get only #4720 in and close this?

**Comment by scottkurz** [comment]
> 
> 
> @mezarin @scottkurz
> 
> > Just mentioning my #4720 includes this same change basically and also a change to use the endpoint in the devfile.
> 
> In that case, which one should we prioritize? If we merge your PR, the same changes proposed in this PR also get in along with more changes. Should we get only #4720 in and close this?

@dharmit  we can close this and focus on #4720.  Thanks

**Pull request closed without merging**
