### PR TITLE
Use the generators from devfile/library

### LINKED ISSUE #4209: Use the generators from devfile/library
With #4134 merged, https://github.com/devfile/api/issues/184 is in progress where the PR is going to merge the generators code to devfile/library.

Once the code is merged to devfile/library, odo  need to start using the generators from the devfile/library module.

### PR DESCRIPTION
**Pull request by maysunfaisal**
**What type of PR is this?**
/kind cleanup
/kind code-refactoring

**What does does this PR do / why we need it**:
Uses the generator code from devfile/library repo

**Which issue(s) this PR fixes**:

Fixes #4209 

**PR acceptance criteria**:

- [x] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [x] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:
Unit and Integration tests should pass

### CODE REVIEW

**Review by mik-dass — APPROVED** [review]
CI is green
/approve

**Comment by maysunfaisal** [comment]
interesting, the bot auto-added the `lgtm` label by itself after `approve` 🤔

**Comment by mik-dass** [comment]
> interesting, the bot auto-added the `lgtm` label by itself after `approve` 🤔  or perhaps its because the `approve` was in a github approve review.

I guess it was because the `approve` was in a GitHub approval. But there was a recent decision to merge PRs with only one approval in the future. I am not sure if that has been enabled and added the label in this case.

**Comment by dharmit** [comment]
> I guess it was because the `approve` was in a GitHub approval. But there was a recent decision to merge PRs with only one approval in the future. I am not sure if that has been enabled and added the label in this case.

Nope. It's because, as far as I have observed, that's how GH works. The PR for making only one lgtm as required for a PR is still open https://github.com/openshift/release/pull/13942. :smile:

**Pull request merged**
