### PR TITLE
Fix project unzip function on Windows

### LINKED ISSUE #3296: `odo create --downloadSource` is broken on Windows
/kind bug
/area devfile
/area devfileV2

## What versions of software are you using?

**Operating System:**
Windows 10

It seems that `odo create --downloadSource` functions differently on Windows, as it doesn't clone the sample project to the same directory as the devfile, but rather a subdirectory within the folder:
```
PS D:\ododev\sourcemapping> odo create nodejs --downloadSource
Experimental mode is enabled, use at your own risk
Validation
 V  Checking devfile compatibility [979000ns]
 V  Creating a devfile component from registry: DefaultDevfileRegistry [1ms]
 V  Validating devfile component [0ns]
Please use `odo push` command to create the component with source deployed
PS D:\ododev\sourcemapping> ls
    Directory: D:\ododev\sourcemapping
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        2020-06-03   1:40 PM                .odo
d-----        2020-06-03   1:40 PM                odo-devfiles-nodejs-ex-39b5ec7
-a----        2020-06-03   1:40 PM            731 devfile.yaml
```
This will cause the source code to get synced to `/projects/<project-name>/odo-devfiles-nodejs-ex-39b5ec7`, rather than `/projects/<project-name>`, which breaks most of the devfiles in odo.

On macOS, it clones the sample project to the same directory as the devfile and everything works fine:
```
Johns-MacBook-Pro-3:nodejs johncollier$ odo create nodejs --downloadSource
Experimental mode is enabled, use at your own risk

Validation
 ✓  Checking devfile compatibility [100451ns]
 ✓  Creating a devfile component from registry: DefaultDevfileRegistry [84496ns]
 ✓  Validating devfile component [177559ns]

Please use `odo push` command to create the component with source deployed
Johns-MacBook-Pro-3:nodejs johncollier$ ls
LICENSE			app			package-lock.json
README.md		devfile.yaml		package.json
```

### PR DESCRIPTION
**Pull request by neeraj-laad**
**What type of PR is this?**
/kind bug

**What does does this PR do / why we need it**:
Fixes issues with unzipping files on Windows

**Which issue(s) this PR fixes**:

Fixes #3296 

**PR acceptance criteria**:

- [x] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer**:
- `odo create nodejs --downloadSource` 
- Verify that the project is cloned in current dir and not under a dir like `odo-devfiles-nodejs-ex-*`
- This should be tested on Windows and non-Windows platforms.

### CODE REVIEW

**Comment by prietyc123** [comment]
Seems a real failure to me on windows https://travis-ci.com/github/openshift/odo/jobs/364238986#L193-L198

/hold

**Comment by neeraj-laad** [comment]
@prietyc123 I have fixed the tests on Windows now.

**Comment by neeraj-laad** [comment]
@johnmcollier @prietyc123 Let me know if the PR looks ok now.

**Comment by prietyc123** [comment]
> @prietyc123 I have fixed the tests on Windows now.

/unhold

**Pull request merged**
