### PR TITLE
Add tests for odo catalog search failing

### PR DESCRIPTION
**Pull request by cdrage**
Adds tests for odo catalog search failing

Closes https://github.com/openshift/odo/issues/2147

### CODE REVIEW

**Comment by mik-dass** [comment]
```
Expected
        <string>:  ✗  The current directory does not represent an odo component. Use 'odo create' to create component here or switch to directory with a component
```
@cdrage I guess this PR needs a rebase as https://github.com/openshift/odo/pull/2134 is already in

**Comment by mik-dass** [comment]
```
Authentication required for https://127.0.0.1:8443 (openshift)
[odo] Username: Password: Login failed (401 Unauthorized)
[odo] Verify you have provided correct credentials.
[odo]  ✗  challenger chose not to retry the request
```
/retest

**Comment by amitkrout** [comment]
Travis failure is fixed in #2164 
/lgtm

**Pull request merged**
