### PR TITLE
Fix install URL link

### PR DESCRIPTION
**Pull request by scottkurz**
Signed-off-by: Scott Kurz <skurz@us.ibm.com>

/kind documentation
[skip ci]

**What does does this PR do / why we need it**:

Looks like the install link changed within the OpenShift doc.

Old: https://docs.openshift.com/container-platform/latest/cli_reference/openshift_developer_cli/installing-odo.html
New: https://docs.openshift.com/container-platform/latest/cli_reference/developer_cli_odo/installing-odo.html

**PR acceptance criteria**:

- [X ] Documentation 

- [X ] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

### CODE REVIEW

**Review by mik-dass — APPROVED** [review]
/lgtm

**Review by rnapoles-rh — APPROVED** [review]
/lgtm

**Pull request merged**
