### PR TITLE
Bumping odo version v2.0.5 -> v2.0.6

### PR DESCRIPTION
**Pull request by mohammedzee1000**
Signed-off-by: Mohammed Zeeshan Ahmed <mohammed.zee1000@gmail.com>

### CODE REVIEW

**Review by dharmit — APPROVED** [review]

**Comment by mohammedzee1000** [comment]
Fails not related to code. Cannot block release any further

**Comment by kadel** [comment]
/test v4.7-integration-e2e
--

**Comment by mohammedzee1000** [comment]
This is taking too long and the errors are not even related to the PR. We do not want to delay the release further.

**Comment by mohammedzee1000** [comment]
Will merge manually, if issue is not sorted by tommorow morning
/refresh
/retest

**Review by rnapoles-rh — COMMENTED** [review]
/lgtm

**Comment by mohammedzee1000** [comment]
Merging manually as any further delay  could push release to next week

**Pull request merged**
