### PR TITLE
Bumps version to v1.0.0-beta3

### PR DESCRIPTION
**Pull request by mik-dass**
Release notes draft

So what's new in v1.0.0-beta3?

Enhancements
- Adds a timer to UI / UX output to the odo component creation output. #1795 
- We can now run `odo component describe/delete/list` and `odo app describe/delete/list` outside a directory containing a odo component. #1792 and #1779  
- The problem of wrong path during odo create in interactive mode is fixed. #1764 
- We can now view odo config info from the local config without talking to the server. #1758 
- Adds a "shortcut" section to odo --help. #1763 
- Adds a `path` flag to `odo list` for viewing all components in a directory. #1771 
- Improves URL creation and deletion UI/UX. #1774 
- Rename install.sh to installer.sh and Add Uninstall #1802 
- Fix infinite wait in CreateNewProject #1785 
- Remove multiple "odo app list" entries #1767 
- Create the preference file lazily #1765 
- Add "shortcut" section to odo help #1763 

Breaking changes
- The global preference's default name changes to preference.yaml instead of config.yaml. As this file is present in the ~/.odo folder it will not colide with the config.yaml if someone chooses to create a component in home dir. For backward compatibility, just rename the file to preference.yaml. #1784

### CODE REVIEW

**Comment by kadel** [comment]
Please add Release notes as a description for this PR

**Comment by mik-dass** [comment]
```
error: build error: After retrying 2 times, Pull image still failed due to error: while pulling "docker://image-registry.openshift-image-...............
```
/retest

**Comment by cdrage** [comment]
/hold

Hey @mik-dass 

You need to update the release notes to note the different sections (internal,  testing/ci,  documentation, etc.)

You are also missing a lot more merged PR's since the last date of the release:

https://github.com/openshift/odo/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Amerged+closed%3A%3E2019-05-20+

You are also missing:
 - https://github.com/openshift/odo/pull/1784 is a breaking change
 - emphasis on new UI output (you can add an asciinema maybe? https://github.com/openshift/odo/pull/1774)
 - even small things like documentation changes aren't listed (example, https://github.com/openshift/odo/pull/1748 isn't on the list and not in a separate section)

**Comment by kadel** [comment]
> * Adds a `path` flag to `odo list` for viewing all components in a directory which is in the same project. #1771

this is not correct description. --path has nothing to do with the component project

**Comment by kadel** [comment]
> * rename install.sh to installer.sh and Add Uninstall #1802
> * fix infinite wait in CreateNewProject #1785
> * remove multiple "odo app list" entries #1767
> * create the preference file lazily #1765
> * add "shortcut" section to odo help #1763

all other entries are starting with uppercase letter

**Comment by mik-dass** [comment]
@kadel Fixed

**Comment by mik-dass** [comment]
```
odoSourceE2e
/home/travis/gopath/src/github.com/openshift/odo/tests/integration/source_test.go:12
  odo component creation
  /home/travis/gopath/src/github.com/openshift/odo/tests/integration/source_test.go:28
    Should be able to deploy a wildfly source application [It]
    /home/travis/gopath/src/github.com/openshift/odo/tests/integration/source_test.go:75
    Unexpected error:
        <*url.Error | 0xc0002010b0>: {
            Op: "Get",
            URL: "http://wildfly-app-8080-app-duxuphitha.127.0.0.1.nip.io",
            Err: {
                Op: "dial",
                Net: "tcp",
                Source: nil,
                Addr: nil,
                Err: {
                    Err: "server misbehaving",
                    Name: "wildfly-app-8080-app-duxuphitha.127.0.0.1.nip.io",
                    Server: "169.254.169.254:53",
                    IsTimeout: false,
                    IsTemporary: true,
                },
            },
        }
        Get http://wildfly-app-8080-app-duxuphitha.127.0.0.1.nip.io: dial tcp: lookup wildfly-app-8080-app-duxuphitha.127.0.0.1.nip.io on 169.254.169.254:53: server misbehaving
```
/retest

**Pull request merged**
