### PR TITLE
Refractor BeforeEach and AfterEach function for test script

### LINKED ISSUE #3337: refactoring integrations and e2e tests - abstracting Before/After Each
We have a lot of duplicated code in our tests, mainly in After and Before Each function.

All common logic from those functions should be abstracted away to separate functions.
This will make it much easier to manage resources that are being created and it will be easier to do a proper clean up.

I've tried to do that at https://github.com/openshift/odo/pull/3221 but sadly before I could finish it it got out of sync with the master to the point that it can't be saved. It is going to be easier to start from scratch than trying to resolve all conflicts.

The above PR is not perfect there is a lot of things that can be done better, but it can be used as an example of how to streamline After and Before Each function.

/area testing
/kind code-refactoring

### PR DESCRIPTION
**Pull request by prietyc123**
**What type of PR is this?**

/kind cleanup
/area testing
/kind code-refactoring

**What does does this PR do / why we need it**:

Removes test script code duplication in BeforeEach and AfterEach functions

**Which issue(s) this PR fixes**:

Fixes #3337 

**PR acceptance criteria**:

- [ ] Unit test 

- [x] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer**:

All the test script should run with CommonBeforeEach and CommonAfterEach functions

### CODE REVIEW

**Comment by prietyc123** [comment]
https://github.com/openshift/odo/issues/3755#issuecomment-675283651

/test unit

**Comment by prietyc123** [comment]
deployment rollout errors out for `odo push` in operator hub very frequently https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_odo/3763/pull-ci-openshift-odo-master-v4.5-integration-e2e/1302824936884146176#1:build-log.txt%3A1423

Analysing the issue in https://github.com/openshift/odo/pull/3906 

/retest

**Comment by dharmit** [comment]
@prietyc123 this one needs rebase

**Comment by prietyc123** [comment]
Closing this pr as this pr messed up after v2.0.0 release. Also we need to do some clean up with s2i tests spec. I will cover all the concern in different pr.

**Pull request closed without merging**
