### PR TITLE
Renaming entrypoint scripts to use new job

### PR DESCRIPTION
**Pull request by mohammedzee1000**
- 4.6 will now run the old presubmit-all script
 - psi will run as 4.6-e2e-4x-psi

Signed-off-by: Mohammed Zeeshan Ahmed <mohammed.zee1000@gmail.com>

### CODE REVIEW

**Comment by anandrkskd** [comment]
@mohammedzee1000 should we also remove the old [presubmit-all script](https://github.com/mohammedzee1000/odo/blob/psi_optional/scripts/openshiftci-presubmit-all-tests-old.sh) ? or we are going to use it somewere

**Comment by mohammedzee1000** [comment]
Interesting. Wonder why it failed on nodejs-14 o_O
```
Summarizing 1 Failure:
[Fail] odo supported images e2e tests odo supported private registry images deployment [It] Should be able to verify the nodejs-14 image 
/go/src/github.com/openshift/odo/tests/helper/helper_run.go:34
Ran 30 of 30 Specs in 1140.566 seconds
FAIL! -- 29 Passed | 1 Failed | 0 Pending | 0 Skipped
Ginkgo ran 1 suite in 19m2.657091023s
Test Suite Failed
make: *** [test-e2e-all] Error 1
+ error=true
+ '[' true ']'
```
anycase lets try one more time
/retest

**Comment by anandrkskd** [comment]
its tracked under https://github.com/openshift/odo/pull/4416

**Comment by mohammedzee1000** [comment]
Same fail again

**Review by rnapoles-rh — APPROVED** [review]

**Pull request merged**
