### PR TITLE
Fixes path for odo create interactive

### LINKED ISSUE #2163: odo create interactive generates incorrect config
[kind/bug]

## What versions of software are you using?
- Operating System: Win10Pro
- Output of `odo version`:

```
odo v1.0.0-beta5 (4d1d5071)     
                                
Server: https://172.18.84.8:8443
Kubernetes: v1.11.0+d4cacc0
```     

## How did you run odo exactly?

`odo create `

then
- select `java` for the component type
- select `8` for the component version
- select `local` for input type
- select `.` for relative path (even through the full path was proposed)
- select `comp1` for component name
- select `sbapp` for the application name
- accepted the project
- select `N` for advanced options
```

? Which component type do you wish to create java                           
? Which version of 'java' component type do you wish to create 8            
? Which input type do you wish to use for the component local               
? Location of path component, relative to 'C:\work\src\tmp\demo170\comp1' . 
? What do you wish to name the new component comp1                          
? Which application do you want the commponent to be associated with sbapp  
? Which project go you want the component to be created in sbproj           
? Do you wish to set advanced options No                                    
 V  Validating component [12ms]                                             
Please use `odo push` command to create the component with source deployed
```  
Then the config file is:

```
kind: LocalConfig
apiversion: odo.openshift.io/v1alpha1
ComponentSettings:
  Type: java:8
  SourceLocation: C:\work\src\tmp\demo170\comp1
  SourceType: local
  Application: sbapp
  Project: sbproj
  Name: comp1

```

## Actual behavior

Wrong config file generated (SourceLocation should be .)

## Expected behavior

Generated config file should have (SourceLocation .)

### PR DESCRIPTION
**Pull request by mik-dass**
fixes #2163 

How to test:
Trigger `odo create` in a directory, enter response of `Location of path component, relative to ...` and check if the correct response is stored by `odo config view`

### CODE REVIEW

**Comment by dharmit** [comment]
@mik-dass If instead of hitting the "Return" key, I choose to provide the full path to the component directory, it fails:
```sh
$ odo create
? Which component type do you wish to create nodejs
? Which version of 'nodejs' component type do you wish to create latest
? Which input type do you wish to use for the component local
X Sorry, your reply was invalid: path '~/src/nodejs-ex' does not exist on the file system
? Location of path component, relative to '/home/dshah/src/nodejs-ex' /home/dshah/src/nodejs-ex
? What do you wish to name the new component nodejs
? Which application do you want the commponent to be associated with app
? Which project go you want the component to be created in myproject
? Do you wish to set advanced options No
 ✓  Validating component [25ms]
Please use `odo push` command to create the component with source deployed

$ odo push
Validation
 ✓  Checking component [7ms]

Configuration changes
 ✓  Initializing component
 ✓  Creating component [192ms]

Pushing to component nodejs of type local
 ✓  Checking files for pushing [794780ns]
 ✗  open /home/dshah/src/nodejs-ex/home/dshah/src/nodejs-ex: no such file or directory
```

**Comment by mik-dass** [comment]
```
? Location of path component, relative to '/home/dshah/src/nodejs-ex'
```
@dharmit  we are informing the user that the path should be relative to the directory

**Comment by mik-dass** [comment]
```•  Waiting for build to finish  ...
[odo]  ✗  Waiting for build to finish [30s]
[odo]  ✗  Failed to create component with name testcmp. Please use `odo config view` to view settings used to create component. Error: unable to wait for build testcmp-e2e-xyzk-1 to run: timed out waiting for the condition
```
/retest

**Comment by dharmit** [comment]
> ```
> ? Location of path component, relative to '/home/dshah/src/nodejs-ex'
> ```
> 
> @dharmit we are informing the user that the path should be relative to the directory

Ack. My bad on missing that piece of info.

/hold cancel

**Comment by kadel** [comment]
/retest

```
level=warning msg="Found override for release image. Please be warned, this is not advised"
level=info msg="Consuming \"Install Config\" from target directory"
level=info msg="Creating infrastructure resources..."
level=error
level=error msg="Error: Error retrieving Listener: timeout while waiting for state to become 'success' (timeout: 1m0s)"
level=error
level=error msg="  on ../tmp/openshift-install-774646207/vpc/master-elb.tf line 142, in resource \"aws_lb_listener\" \"api_external_api\":"
level=error msg=" 142: resource \"aws_lb_listener\" \"api_external_api\" {"
level=error
level=error
```

**Pull request merged**
