### PR TITLE
Fixing wrong project passed to the component

### PR DESCRIPTION
**Pull request by prietyc123**
**What type of PR is this?**

/kind failing-test

**What does does this PR do / why we need it**:

Unblock CI and fix the failure https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-odo-master-v4.5-integration-e2e-periodic/1358928787923800064#1:build-log.txt%3A779 

**Which issue(s) this PR fixes**:

Fixes 

**PR acceptance criteria**:

- [ ] Unit test 

- [x] Integration test 

- [ ] Documentation 

- [ ] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

`make test-e2e-images` should pass

### CODE REVIEW

**Review by dharmit — APPROVED** [review]
/lgtm

**Comment by prietyc123** [comment]
component push fails on deployment roll out on psi cluster
```
I0209 06:58:30.626844  206136 events.go:52] Warning Event: Count: 5, Reason: Failed, Message: Error: ImagePullBackOff
[ssh:Fedora 32] [odo]  ✗  Waiting for component to start [5m] [WARNING x5: Failed]
[ssh:Fedora 32] [odo]  ✗  Failed to start component with name priylt. Error: Failed to create the component: error while waiting for deployment rollout: timeout while waiting for priylt deployment roll out\nFor more information to help determine the cause of the error, re-run with '-v'.
[ssh:Fedora 32] [odo] See below for a list of failed events that occured more than 5 times during deployment:
[ssh:Fedora 32] [odo] 
[ssh:Fedora 32] [odo]  NAME                                      COUNT  REASON  MESSAGE                 
[ssh:Fedora 32] [odo] 
[ssh:Fedora 32] [odo]  priylt-7995d85b64-9z982.166201e8f991f2d3  5      Failed  Error: ImagePullBackOff 
```
Tracked in https://github.com/openshift/odo/issues/3256

Also operator hub tests are failing on secrets
```
[ssh:Fedora 32] [odo]  ✗  Waiting for component to start [5m] [WARNING x7: Failed]
[ssh:Fedora 32] [odo]  ✗  Failed to start component with name qgtsfd. Error: Failed to create the component: error while waiting for deployment rollout: timeout while waiting for qgtsfd deployment roll out\nFor more information to help determine the cause of the error, re-run with '-v'.
[ssh:Fedora 32] [odo] See below for a list of failed events that occured more than 5 times during deployment:
[ssh:Fedora 32] [odo] 
[ssh:Fedora 32] [odo]  NAME                                     COUNT  REASON  MESSAGE                        
[ssh:Fedora 32] [odo] 
[ssh:Fedora 32] [odo]  qgtsfd-f749fd5ff-zhglb.1661fe6152cec023  7      Failed  Error: secret                  
[ssh:Fedora 32] [odo]                                                          "qgtsfd-etcdcluster-example"   
[ssh:Fedora 32] [odo]                                                          not found       
```
issue has been tracked https://github.com/openshift/odo/issues/4301

**Comment by prietyc123** [comment]
platform failure

/retest

**Review by rnapoles-rh — APPROVED** [review]

**Pull request merged**
