### PR TITLE
Don't fail the command if listing a CR's instances fails

### LINKED ISSUE #4221: odo service list fails with one service
/kind bug

When odo encounters a problem with one of the operators it fails the listing for all services. For instance in this case it fails to get services with tekton and fails the listing of services for all operators although the rest is fine.

## What versions of software are you using?

**Operating System:**
MacOS

**Output of `odo version`:**
❯ odo version
odo v2.0.1 (a9fff7da4)

## How did you run odo exactly?
odo service list 

## Actual behavior
 ✗  the server could not find the requested resource

## Expected behavior
list of available services especially operators. 

## Any logs, error output, etc?
```
I1115 13:42:12.398461    9288 service.go:314] Getting services started from operator: openshift-pipelines-operator.v1.0.1
I1115 13:42:12.398478    9288 service.go:454] Getting instances of: config.operator.tekton.dev
I1115 13:42:12.398548    9288 round_trippers.go:423] curl -k -v -XGET  -H "Accept: application/json" -H "User-Agent: odo/v0.0.0 (darwin/amd64) kubernetes/$Format" -H "Authorization: Bearer -nUI" 'https://.../apis/operator.tekton.dev/v1alpha1/namespaces/gercan-stage/config'
I1115 13:42:12.401809    9288 util.go:764] Cached response used.
I1115 13:42:12.430347    9288 round_trippers.go:443] GET https://api.member.crt-stage.com:6443/apis/operator.tekton.dev/v1alpha1/namespaces/gercan-stage/config 404 Not Found in 31 milliseconds
I1115 13:42:12.430366    9288 round_trippers.go:449] Response Headers:
I1115 13:42:12.430369    9288 round_trippers.go:452]     X-Content-Type-Options: nosniff
I1115 13:42:12.430373    9288 round_trippers.go:452]     X-Kubernetes-Pf-Flowschema-Uid: 7c172f0f-
I1115 13:42:12.430376    9288 round_trippers.go:452]     X-Kubernetes-Pf-Prioritylevel-Uid: e3dbd267
I1115 13:42:12.430379    9288 round_trippers.go:452]     Content-Length: 19
I1115 13:42:12.430382    9288 round_trippers.go:452]     Date: Sun, 15 Nov 2020 18:42:12 GMT
I1115 13:42:12.430385    9288 round_trippers.go:452]     Audit-Id: f030c88a
I1115 13:42:12.430388    9288 round_trippers.go:452]     Cache-Control: no-cache, private
I1115 13:42:12.430392    9288 round_trippers.go:452]     Content-Type: text/plain; charset=utf-8
```

### PR DESCRIPTION
**Pull request by dharmit**
**What type of PR is this?**
/kind bug

**What does this PR do / why we need it**:
It prevents `odo service list` from entirely failing if listing instances of one or a few of the CRs fails.

**Which issue(s) this PR fixes**:

Fixes #4221 

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [ ] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:
1. On a CRC system, install etcd Operator and Red Hat OpenShift Pipelines Operator
1. Look for output similar to below:
    ```sh
    $ odo catalog list services
    Operators available in the cluster
    NAME                                           CRDs
    etcdoperator.v0.9.4-clusterwide                EtcdCluster, EtcdBackup, EtcdRestore
    redhat-openshift-pipelines-operator.v1.2.1     Config
    ```
1. Do `odo service list`. We didn't start a service from any CR/Operator yet so you should see output like below:
    ```sh
    $ odo service list           
    Failed to list services for operator(s): "redhat-openshift-pipelines-operator.v1.2.1/Config"
    ✗  no operator backed services found in namespace: myproject
    ```
1. Now create an EtcdCluster using: `odo service create etcdoperator.v0.9.4-clusterwide/EtcdCluster`. Listing the services should show output like below:
    ```sh
    $ odo service list
    NAME                    AGE
    EtcdCluster/example     6m2s

    Failed to list services for Operator(s): "redhat-openshift-pipelines-operator.v1.2.1/Config"
    ```

### CODE REVIEW

**Comment by adisky** [comment]
> 3. Do `odo service list`. We didn't start a service from any CR/Operator yet so you should see output like below:
>    ```shell
>    $ odo service list           
>    Failed to list services for operator(s): "redhat-openshift-pipelines-operator.v1.2.1/Config"
>    ✗  no operator backed services found in namespace: myproject
>    ```
> 4. Now create an EtcdCluster using: `odo service create etcdoperator.v0.9.4-clusterwide/EtcdCluster`. Listing the services should show output like below:
>    ```shell
>    $ odo service list
>    NAME                    AGE
>    EtcdCluster/example     6m2s
>    
>    Failed to list services for Operator(s): "redhat-openshift-pipelines-operator.v1.2.1/Config"
>    ```

shouldn't here the output be `service does not exist` instead of `failed to list services`?

**Comment by dharmit** [comment]
> shouldn't here the output be `service does not exist` instead of `failed to list services`?

No, because we're actually failing to list operands (service) created using this CR. It's an issue with the underlying CR in this particular case as mentioned on https://github.com/openshift/odo/issues/4221#issuecomment-731989529.

**Comment by dharmit** [comment]
@adisky can you PTAL if there's anything else you'd like me address here? I have already made the change that we discussed yesterday https://github.com/openshift/odo/pull/4300/commits/47f27bb44f8d7dbf23c7880f93f80bdc1e96fefa.

**Comment by adisky** [comment]
@dharmit Thanks, looks good to me now
/lgtm

**Pull request merged**
