### PR TITLE
Modifies WaitForDeploymentRollout() to collect events.

### PR DESCRIPTION
**Pull request by mik-dass**
**What type of PR is this?**

/kind flake

**What does does this PR do / why we need it**:

Modifies WaitForDeploymentRollout() to collect events. It also uses WaitAndGetPodWithEvents() for getting the pod in the adapter package.

**Which issue(s) this PR fixes**:

Fixes NA

**PR acceptance criteria**:

- [X] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [ ] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

- Tests should pass.
- If failures related to https://github.com/openshift/odo/issues/3256 occur, collected events should be printed.

### CODE REVIEW

**Comment by kadel** [comment]
This is great! I was just trying to untangle the `WaitAndGetPod` vs `WaitAndGetPodWithEvents` mess.

Could we completely remove `WaitAndGetPod` and replace it with `WaitAndGetPodWithEvents`?

**Comment by mik-dass** [comment]
```
[odo] Push successful

1952

[odo] ✗ Waiting for build to finish [6m]

1953

[odo] ✗ Failed to create component with name uberjar-git-test. Please use `odo config view` to view settings used to create component. Error: failed to build component with args {Name:uberjar-git-test SourcePath:https://github.com/geoand/javalin-helloworld SourceRef:master SourceType:git ImageName:java:8 EnvVars:[DEBUG_PORT=5858] Ports:[8080/TCP 8443/TCP 8778/TCP] Resources:&ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},} ApplicationName:app Wait:true StorageToBeMounted:map[] StdOut:0xc0000fe008}: unable to build uberjar-git-test-app-1, error: : timeout waiting for build uberjar-git-test-app-1 to start
```
/retest

**Comment by mik-dass** [comment]
```
Error creating VPC: VpcLimitExceeded: The maximum number of VPCs has been reached."
```
/retest

**Comment by mik-dass** [comment]
> Could we completely remove `WaitAndGetPod` and replace it with `WaitAndGetPodWithEvents`?

WaitAndGetPod() was not being used anywhere after the initial changes in the PR. I have removed the function in the latest commit.

**Review by dharmit — COMMENTED** [review]
/lgtm

**Comment by dharmit** [comment]
> ```
> [odo] Push successful
> 
> 1952
> 
> [odo] ✗ Waiting for build to finish [6m]
> 
> 1953
> 
> [odo] ✗ Failed to create component with name uberjar-git-test. Please use `odo config view` to view settings used to create component. Error: failed to build component with args {Name:uberjar-git-test SourcePath:https://github.com/geoand/javalin-helloworld SourceRef:master SourceType:git ImageName:java:8 EnvVars:[DEBUG_PORT=5858] Ports:[8080/TCP 8443/TCP 8778/TCP] Resources:&ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},} ApplicationName:app Wait:true StorageToBeMounted:map[] StdOut:0xc0000fe008}: unable to build uberjar-git-test-app-1, error: : timeout waiting for build uberjar-git-test-app-1 to start
> ```
> 
> /retest

Should we have been able to see what's proposed in this PR when we hit this failure on CI?

**Comment by mik-dass** [comment]
> Should we have been able to see what's proposed in this PR when we hit this failure on CI?

It was a build failure and is not related to https://github.com/openshift/odo/issues/3256.

**Pull request merged**
