### PR TITLE
odo link: fix command description

### PR DESCRIPTION
**Pull request by kadel**
**What type of PR is this?**

/kind cleanup

**What does this PR do / why we need it**:
odo link had an outdated description
 commands supports linking two devfile components

### CODE REVIEW

**Review by valaparthvi — APPROVED** [review]

**Review by valaparthvi — CHANGES_REQUESTED** [review]
https://github.com/openshift/odo/pull/4930/files#diff-65ce0831cfcea5d7cd8cd8c5fc59b342b13cf367f4c7ff976aba7b1ac3f83eaaR69
>We can now link the two applications (works only with s2i components):
odo link backend --component frontend

Can you fix this line as well?

**Comment by kadel** [comment]
> https://github.com/openshift/odo/pull/4930/files#diff-65ce0831cfcea5d7cd8cd8c5fc59b342b13cf367f4c7ff976aba7b1ac3f83eaaR69
> 
> > We can now link the two applications (works only with s2i components):
> > odo link backend --component frontend
> 
> Can you fix this line as well?

:+1: done

**Review by valaparthvi — APPROVED** [review]

**Comment by valaparthvi** [comment]
I am also approving this PR since it's a really small change.
/approve

**Comment by valaparthvi** [comment]
> odo link and unlink command tests
/go/src/github.com/openshift/odo/tests/integration/cmd_link_unlink_test.go:10
  when running help for link and unlink command
  /go/src/github.com/openshift/odo/tests/integration/cmd_link_unlink_test.go:32
    should display the help [It]
    /go/src/github.com/openshift/odo/tests/integration/cmd_link_unlink_test.go:33
>
>     to contain substring
>        <string>: works only with s2i components 

Missed out on this one.

**Comment by mik-dass** [comment]
```
    to contain substring
        <string>: works only with s2i components
```
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_odo/4930/pull-ci-openshift-odo-main-v4.7-integration-e2e/1418565524144525312

/hold

**Comment by dharmit** [comment]
@kadel can you please address the changes requested by @valaparthvi & @mik-dass? Also, please update the Changelog.md file.

**Comment by kadel** [comment]
> Also, please update the Changelog.md file.

Should something as small as this be in the changelog?

**Comment by dharmit** [comment]
> > Also, please update the Changelog.md file.
> 
> Should something as small as this be in the changelog?

IMO yes because it's still a user facing change nonetheless. We tend to (or, maybe, we should) put even the things that don't directly impact users in the Changelog. I'm trying to use it as the source of truth for Sprint Review document, making announcements of new release at the end of each Sprint, and maybe even blog on docusaurus site announcing new release every Sprint.

**Comment by kadel** [comment]
> > > Also, please update the Changelog.md file.
> > 
> > 
> > Should something as small as this be in the changelog?
> 
> IMO yes because it's still a user facing change nonetheless. We tend to (or, maybe, we should) put even the things that don't directly impact users in the Changelog. I'm trying to use it as the source of truth for Sprint Review document, making announcements of new release at the end of each Sprint, and maybe even blog on docusaurus site announcing new release every Sprint.

udpated

**Review by dharmit — APPROVED** [review]

**Pull request merged**
