### PR TITLE
do not create service if the devfile does not contain endpoint

### LINKED ISSUE #2748: push failed with devfile without endpoinds
```
apiVersion: 1.0.0
metadata:
  name: java
components:
  - type: dockerimage
    alias: tools
    image: quay.io/eclipse/che-java11-maven:nightly
    memoryLimit: 512Mi
    mountSources: true
    volumes:
      - name: m2
        containerPath: /home/user/.m2
commands:
  - name: devBuild
    actions:
      - type: exec
        component: tools
        command: "mvn package"
  - name: devRun
    actions:
      - type: exec
        component: tools
        command: "java -jar target/*.jar"
```
```
▶ odo push
 •  Push devfile component demo-backend  ...
 ✗  Failed to start component with name demo-backend.
Error: Failed to create the component: unable to create or update component: unable to create Service for demo-backend: Service "demo-backend" is invalid: spec.ports: Required value
```

/kind bug
/priority high
/area devfile

### PR DESCRIPTION
**Pull request by yangcao77**
Signed-off-by: Stephanie <stephanie.cao@ibm.com>

**What type of PR is this?**
> Uncomment only one ` /kind` line, and delete the rest.
> For example, `> /kind bug` would simply become: `/kind bug`

/kind bug

**What does does this PR do / why we need it**:
Devfile without endpoint is also a valid devfile, not every application need to have ports exposed.

Checks if the devfile has ports exposed before creating service; if not, do not create service.

Upon update, checks if there is a service exist; if not, create a service if devfile has port exposed. 

**Which issue(s) this PR fixes**:

Fixes #2748

**How to test changes / Special notes to the reviewer**:

git clone Clone https://github.com/rajivnathan/openLibertyDevfile
comment out the endpoint in the devfile

```
odo preference set experimental true
 ./odo push --devfile ./devfile.yaml
```
Verify a deploy and a pod have been created with no errors 

uncomment the endpoint in the devfile

```
./odo push
```

Verify a service with the component name has been created.
Describe the service, verify the port matches the endpoint in the devfile.

### CODE REVIEW

**Comment by yangcao77** [comment]
@kadel @johnmcollier Can you help review this PR? Thanks

**Comment by amitkrout** [comment]
https://github.com/openshift/odo/issues/2641
/test v4.1-integration-e2e-benchmark

**Comment by yangcao77** [comment]
@amitkrout @johnmcollier I've added integration test. Please help review again. Thanks!

**Pull request merged**
