### PR TITLE
Making pre-test setup script check api server stability

### PR DESCRIPTION
**Pull request by mohammedzee1000**
Signed-off-by: Mohammed Zeeshan Ahmed <mohammed.zee1000@gmail.com>

## What is the purpose of this change? What does it change?

The script now checks if api server is stable after success login
and if not does reasonable retry of login

## Was the change discussed in an issue?
Attempt at mitigation #1638  

## How to test changes?

Tests should fail less often due to api server flapping

### CODE REVIEW

**Comment by cdrage** [comment]
@mohammedzee1000 Will need to rebase this against master now that the updated test suit has been merged in :+1:

**Comment by mohammedzee1000** [comment]
> @mohammedzee1000 Will need to rebase this against master now that the updated test suit has been merged in

Rebased

**Comment by girishramnani** [comment]
\approve

**Pull request merged**
