### PR TITLE
Fixes list and describe of secure URLs for not pushed components

### LINKED ISSUE #3060: For secured url1 'odo url describe url1 -o json' prints 'secure' attribute as `false`
/kind bug

## What versions of software are you using?

**Operating System:**
windows 10
**Output of `odo version`:**
1.2.0
## How did you run odo exactly?
Component has one secured url.
Running:
`odo url describe`
`odo url list`
show the same url with different values for 'secure' attribute.

## Actual behavior
```
denis@denis-ThinkPad-P50:~/test/test-1$ odo url describe url1 -o json
{
    "kind": "url",
    "apiVersion": "odo.openshift.io/v1alpha1",
    "metadata": {
        "name": "url1",
        "creationTimestamp": null
    },
    "spec": {
        "port": 8080,
        "secure": false
    },
    "status": {
        "state": "Pushed"
    }
}
```
`odo ulr list` prints out different json with correct value.
```
denis@denis-ThinkPad-P50:~/test/test-1$ odo url list -o json
{
    "kind": "List",
    "apiVersion": "odo.openshift.io/v1alpha1",
    "metadata": {},
    "items": [
        {
            "kind": "url",
            "apiVersion": "odo.openshift.io/v1alpha1",
            "metadata": {
                "name": "url3",
                "creationTimestamp": null
            },
            "spec": {
                "host": "url3-app1-p1.apps-crc.testing",
                "protocol": "https",
                "port": 8080,
                "secure": true
            },
            "status": {
                "state": "Pushed"
            }
        }
    ]
}
```

## Expected behavior
In both outputs `secure` equals `true`

### PR DESCRIPTION
**Pull request by mik-dass**
**What type of PR is this?**
/kind bug

**What does does this PR do / why we need it**:

Fixes list and describe of secure URLs for not pushed components

**Which issue(s) this PR fixes**:

Fixes #3060 

**How to test changes / Special notes to the reviewer**:

```
odo create nodejs
odo url create example --secure
odo url list                   // secure should be true for the not pushed URL
odo url list -o json       // secure should be true for the not pushed URL
odo describe -o json   // secure should be true for the not pushed URL
odo push
odo url list                     // secure should be true for the pushed URL
odo url list -o json         // secure should be true for the pushed URL
odo describe -o json     // secure should be true for the pushed URL
```

### CODE REVIEW

**Comment by dharmit** [comment]
@mik-dass I'm not sure what's the expected behaviour here but, `odo url list` shows if a URL is a secure or not. However, `odo url describe <url>` doesn't. Is this expected?:
```sh
$ odo url list 
Found the following URLs for component nodejs-nodejs-ex-zali in application app:
NAME     STATE          URL     PORT     SECURE
url1     Not Pushed     ://     8080     true
url2     Not Pushed     ://     8080     false
There are local changes. Please run 'odo push'.

$ odo url describe url2                                    
NAME     STATE          URL     PORT
url2     Not Pushed     ://     8080
There are local changes. Please run 'odo push'.

$ odo url describe url1
NAME     STATE          URL     PORT
url1     Not Pushed     ://     8080
There are local changes. Please run 'odo push'.
```
Things look good otherwise.

**Comment by dharmit** [comment]
Besides that, is it expected that we don't get the URL info after doing `odo push`? Here's the output I'm seeing after doing `odo push`. Note that `odo url describe <url>` doesn't show the URL while `odo url list` does:
```sh
$ odo url describe url2        
NAME     STATE      URL     PORT
url2     Pushed     ://     8080

$ odo url describe url1 
NAME     STATE      URL     PORT
url1     Pushed     ://     8080

$ odo url list
Found the following URLs for component nodejs-nodejs-ex-zali in application app:
NAME     STATE      URL                                             PORT     SECURE
url1     Pushed     https://url1-app-myproject.apps-crc.testing     8080     true
url2     Pushed     http://url2-app-myproject.apps-crc.testing      8080     false
```

**Comment by mik-dass** [comment]
> @mik-dass I'm not sure what's the expected behaviour here but, odo url list shows if a URL is secure or not. However, odo url describe <url> doesn't. Is this expected?:

Yes because currently, for the master branch, the ouput of `url describe` doesn't have a secure column for displaying secure or not. It shows the info in json output though.

> Besides that, is it expected that we don't get the URL info after doing odo push? Here's the output I'm seeing after doing odo push. Note that odo url describe <url> doesn't show the URL while odo url list does

This seems to be in the latest master too

```
[mrinaldas@localhost che-nodejs]$ odo url list
Found the following URLs for component nodejs-che-nodejs-ybjc in application app:
NAME        STATE      URL                                                        PORT     SECURE
example     Pushed     http://example-app-blah.b6ff.rh-idev.openshiftapps.com     8080     false
[mrinaldas@localhost che-nodejs]$ odo url describe example
NAME        STATE      URL     PORT
example     Pushed     ://     8080
```

**Comment by dharmit** [comment]
> This seems to be in the latest master too
> 
> ```
> [mrinaldas@localhost che-nodejs]$ odo url list
> Found the following URLs for component nodejs-che-nodejs-ybjc in application app:
> NAME        STATE      URL                                                        PORT     SECURE
> example     Pushed     http://example-app-blah.b6ff.rh-idev.openshiftapps.com     8080     false
> [mrinaldas@localhost che-nodejs]$ odo url describe example
> NAME        STATE      URL     PORT
> example     Pushed     ://     8080
> ```

Do you think it should be fixed? I can open a different issue for it since it's obviously not a part of this PR. WDYT?

**Comment by mik-dass** [comment]
> Do you think it should be fixed? I can open a different issue for it since it's obviously not a part of this PR. WDYT?

Created issue #3274

**Comment by mik-dass** [comment]
```
[odo] I0603 00:45:27.083489   12865 occlient.go:1764] Status of ref-test-app-1 build is Failed
[odo]  ✗  Waiting for build to finish [1m]
[odo]  ✗  Failed to create component with name ref-test. Please use `odo config view
```
/retest

**Comment by mik-dass** [comment]
```
• Failure [317.853 seconds]
odo devfile watch command tests
/go/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_watch_test.go:15
  when executing odo watch after odo push with custom commands
  /go/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_watch_test.go:115
    should listen for file changes [It]
    /go/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_watch_test.go:116
    Timeout out after � minutes
    /go/src/github.com/openshift/odo/tests/helper/helper_generic.go:148
```
/retest

**Pull request merged**
