### PR TITLE
Remove url describe command

### LINKED ISSUE #2638: Implement `odo storage describe` and `odo url describe` command
## User Story
As a user I want to get the details of a particular storage/url for a component.

## Acceptance Criteria 
- [ ] It should implement command `odo storage describe <storage-name> `
- [ ] It should `odo url describe <url-name>`

## Links 
- Feature Request: 
- Related issue: 

/kind user-story

### PR DESCRIPTION
**Pull request by adisky**
**What type of PR is this?**

 /kind cleanup

**What does does this PR do / why we need it**:
as per the discussions here https://github.com/openshift/odo/issues/2638, we agreed to remove `url describe` command, as `url list` gives sufficient info.

**Which issue(s) this PR fixes**:

Fixes #2638 

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [ ] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by adisky** [comment]
/retest

```
The command "make goget-tools" failed and exited with 2 during .
Your build has been stopped.
go: github.com/openshift/library-go@v0.0.0-20200407165825-2e79bd232e72 requires
	bitbucket.org/ww/goautoneg@v0.0.0-20120707110453-75cd24fc2f2c: reading https://api.bitbucket.org/2.0/repositories/ww/goautoneg?fields=scm: 404 Not Found
go: github.com/openshift/library-go@v0.0.0-20200407165825-2e79bd232e72 requires
	bitbucket.org/ww/goautoneg@v0.0.0-20120707110453-75cd24fc2f2c: reading https://api.bitbucket.org/2.0/repositories/ww/goautoneg?fields=scm: 404 Not Found
```

**Review by dharmit — COMMENTED** [review]
/approve

**Review by mik-dass — APPROVED** [review]
/lgtm

**Comment by kadel** [comment]
> /retest
> 
> ```
> The command "make goget-tools" failed and exited with 2 during .
> Your build has been stopped.
> go: github.com/openshift/library-go@v0.0.0-20200407165825-2e79bd232e72 requires
> 	bitbucket.org/ww/goautoneg@v0.0.0-20120707110453-75cd24fc2f2c: reading https://api.bitbucket.org/2.0/repositories/ww/goautoneg?fields=scm: 404 Not Found
> go: github.com/openshift/library-go@v0.0.0-20200407165825-2e79bd232e72 requires
> 	bitbucket.org/ww/goautoneg@v0.0.0-20120707110453-75cd24fc2f2c: reading https://api.bitbucket.org/2.0/repositories/ww/goautoneg?fields=scm: 404 Not Found
> ```

fix in https://github.com/openshift/odo/pull/3984

**Pull request merged**
