### PR TITLE
Bumping odo version v2.1.0 -> v2.2.0

### PR DESCRIPTION
**Pull request by mohammedzee1000**
Signed-off-by: Mohammed Zeeshan Ahmed <mohammed.zee1000@gmail.com>

### CODE REVIEW

**Comment by dharmit** [comment]
/hold 

Trying to get #4565 in by EOD before this goes in. If it doesn't by EOD, feel free to remove the hold.

**Comment by mohammedzee1000** [comment]
Considering that we are at end of the day and requested pr merged. I will remove the hold
Lets resume release tommorow
/hold cancel

**Review by dharmit — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
