### PR TITLE
Update configure-installer-tests-cluster-ppc64le.sh script to import right imagestream for tests.

### PR DESCRIPTION
**Pull request by sarveshtamba**
**What type of PR is this?**
/kind bug

**What does does this PR do / why we need it**:
There are configured imagestreams for ppc64le arch. Since the library has updated the files, we need to update it to work well with the test suites. Same as PR https://github.com/openshift/odo/pull/4054

**Which issue(s) this PR fixes**:

Fixes #?

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [ ] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Review by mohammedzee1000 — APPROVED** [review]
Looking good
/lgtm

**Review by cdrage — APPROVED** [review]
/approve

**Pull request merged**
