### PR TITLE
Remove empty docs; add when ready

### PR DESCRIPTION
**Pull request by dharmit**
$subject

ping @valaparthvi can you help with this quick one?

/kind documentation

### CODE REVIEW

**Review by valaparthvi — CHANGES_REQUESTED** [review]
What about the quickstart doc? It is not useful as such, are we keeping it?
Other changes look fine.

**Comment by dharmit** [comment]
> What about the quickstart doc? It is not useful as such, are we keeping it?
> Other changes look fine.

I kept it because your PR's addressing it. But it makes sense to remove it. I'll remove that as well.

**Review by valaparthvi — APPROVED** [review]

**Comment by valaparthvi** [comment]
>I kept it because your PR's addressing it. But it makes sense to remove it. I'll remove that as well.

Since you removed other files such as cluster-setup that were being addressed by open PRs, I suggested we remove quickstart as well.

**Comment by valaparthvi** [comment]
/approve 
Minor change, hence approving.

**Pull request merged**
