### PR TITLE
Exports ODO_LOG_LEVEL env variable in integration tests

### PR DESCRIPTION
**Pull request by mik-dass**
**What type of PR is this?**

/kind code-refactoring

**What does does this PR do / why we need it**:

Expose ODO_LOG_LEVEL env to the integration tests for getting verbose logs for failing tests

**How to test changes / Special notes to the reviewer**:
 
Check that a failing test has verbose logs.

### CODE REVIEW

**Comment by girishramnani** [comment]
can we not keep this variable in the `Makefile`?

**Comment by amitkrout** [comment]
> @mik-dass You just need to add `ODO_LOG_LEVEL ?= 4` in the Makefile instead of these changes.

@mik-dass May be not. You need to find a better way to export the env variable in Makefile

**Comment by mik-dass** [comment]
> @mik-dass You just need to add ODO_LOG_LEVEL ?= 4 in the Makefile instead of these changes.

Doesn't work. 

> @mik-dass May be not. You need to find a better way to export the env variable in Makefile

We are already defining env variables for Travis and are exposing env variable in the openshift CI too. 
Exporting in makefile might complicate things when the user wants to apply a different value to the variable.

Also this approach works https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_odo/2595/pull-ci-openshift-odo-master-v4.3-integration-e2e-benchmark/623

**Comment by mik-dass** [comment]
```
✗  Failed To Update Config To Component Deployed.
[odo] Error: unable to update DeploymentConfig for nodejs component: unable to update the current DeploymentConfig nodejs-app: unable to update DeploymentConfig nodejs-app: Operation cannot be fulfilled on deploymentconfigs.apps.openshift.io "nodejs-app": the object has been modified; please apply your changes to the latest version and try again
```
/retest

**Pull request merged**
