### PR TITLE
Lang. and other fixes for homepage

### PR DESCRIPTION
**Pull request by rkratky**
## What is the purpose of this change? What does it change?

* Language and style improvements
* Consolidation of naming (rid of 'OpenShift Do' in favor of 'odo'; https://github.com/openshift/odo/pull/1467#issuecomment-480935375)
* Change demo to embedded

Apologies it's so last-minute.

### CODE REVIEW

**Comment by mohammedzee1000** [comment]
Openshift CI tests are not configured to run against this branhc
/approve

**Comment by mohammedzee1000** [comment]
Something must have broken here. Maybe check travis?

**Comment by mohammedzee1000** [comment]
We dont have a travis against gh-pages at all

**Comment by kadel** [comment]
merging manually

**Pull request merged**
