### PR TITLE
Update doc to support installation on IBM Power for the latest version.[skip ci]

### PR DESCRIPTION
**Pull request by sarveshtamba**
**What type of PR is this?**
/kind documentation
[skip ci]

**What does does this PR do / why we need it**:
Since the odo CI on Power for master has passed for all covered tests, The latest version installation should be added to doc for users of odo on IBM Power. Similar to PR #4040 

**Which issue(s) this PR fixes**:

Fixes #?

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [ ] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Review by mohammedzee1000 — APPROVED** [review]
Looks good
/lgtm

**Comment by prietyc123** [comment]
Doc changes

/override v4.5-integration-e2e

**Comment by amitkrout** [comment]
> /override v4.5-integration-e2e

/override v4.5-integration-e2e

**Pull request merged**
