### PR TITLE
Fix for java image import issue on ppc64le

### PR DESCRIPTION
**Pull request by kandarpamalipeddi**
**What type of PR is this?**
> /kind failing-test

**What does this PR do / why we need it**:
This will fix the issue with Java image import on ppc64le platform.

**Which issue(s) this PR fixes**:

Fixes #4569

**PR acceptance criteria**:

- [ ] Integration test 

**How to test changes / Special notes to the reviewer**:
This PR fix the issue observed with Java image import on Power Systems platform.

Changes in "pkg/catalog/catalog.go" are required to omit the below warning observed with odo:
`        Warning: java:latest is not fully supported by odo, and it is not guaranteed to work`

### CODE REVIEW

**Comment by kadel** [comment]
@kandarpamalipeddi Do we really need this. I know that this was an issue. But I thought this was fixed.

We did workaround in odo https://github.com/openshift/odo/pull/4569
and then we reverted this when it got fixed https://github.com/openshift/odo/pull/4599

**Comment by prietyc123** [comment]
> Do we really need this. I know that this was an issue. But I thought this was fixed.
> 
> We did workaround in odo #4569
> and then we reverted this when it got fixed #4599

Yes, I verified the latest tag for java:8 images locally as well and It was fixed. I am not sure why we need it 😕

**Comment by kandarpamalipeddi** [comment]
> > Do we really need this. I know that this was an issue. But I thought this was fixed.
> > We did workaround in odo #4569
> > and then we reverted this when it got fixed #4599
> 
> Yes, I verified the latest tag for java:8 images locally as well and It was fixed. I am not sure why we need it 😕

This change is old one and got delayed in raising PR.
I verified on cluster and with `latest` things are working fine.

**Comment by prietyc123** [comment]
> I verified on cluster and with latest things are working fine.

Closing this pr as latest java images are working fine now.

**Pull request closed without merging**
