### PR TITLE
Remove the namespace flag from odo

### PR DESCRIPTION
**Pull request by johnmcollier**
Signed-off-by: John Collier <jcollier@redhat.com>

**What type of PR is this?**
/kind cleanup

**What does does this PR do / why we need it**:
This PR removes the old `--namespace` flag from `odo push`. As `odo push` already supported the `--project` flag, this PR just removes the code that enables the namespace flag and updates some tests accordingly.

**Which issue(s) this PR fixes**:

Fixes https://github.com/openshift/odo/issues/3948

**PR acceptance criteria**:

- [ ] Unit test 

- [x] Integration test 

- [ ] Documentation 

- [x] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:
1. `odo push --namespace` doesn't work anymore (invalid flag)
2. `odo push --project <project>` still works

### CODE REVIEW

**Review by prietyc123 — CHANGES_REQUESTED** [review]
Could you please also change the comment https://github.com/openshift/odo/pull/3949/files#diff-af2ba6971e0b886cd1846e13bb7c5925R361 accordingly

**Comment by johnmcollier** [comment]
@prietyc123 Updated

**Review by mik-dass — APPROVED** [review]
/lgtm

**Comment by mik-dass** [comment]
PR needs rebase

**Comment by maysunfaisal** [comment]
re added /lgtm after rebase

**Comment by kadel** [comment]
> re added /lgtm after rebase

the command needs to be on a separate line ;-)

/lgtm

**Comment by maysunfaisal** [comment]
re-add lgtm after rebase
/lgtm

**Pull request merged**
