### PR TITLE
use Gomega matchers for json output

### PR DESCRIPTION
**Pull request by kadel**
json tests are flaky this should help to resolve it

fixes #1625

### CODE REVIEW

**Comment by surajnarwade** [comment]
failed to start cluster,

/retest

**Comment by amitkrout** [comment]
@kadel I am not fully sure that this would work all the time. TBH ```gomega``` matcher will be using similar kind of logic like ```compareJSON```

Analysis : 
```
desired := {"kind":"List","apiVersion":"odo.openshift.io/v1alpha1","metadata":{},"items":[{"kind":"Project","apiVersion":"odo.openshift.io/v1alpha1","metadata":{"name":"json-test","creationTimestamp":null},"spec":{"apps":["myapp"]},"status":{"active":true}},{"kind":"Project","apiVersion":"odo.openshift.io/v1alpha1","metadata":{"name":"myproject","creationTimestamp":null},"spec":{"apps":["myapp"]},"status":{"active":false}}]}
```
Copied actual output from https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_odo/1601/pull-ci-openshift-odo-master-e2e-core/523
```
actaul := {"kind":"List","apiVersion":"odo.openshift.io/v1alpha1","metadata":{},"items":[{"kind":"Project","apiVersion":"odo.openshift.io/v1alpha1","metadata":{"name":"json-test","creationTimestamp":null},"spec":{"apps":["myapp"]},"status":{"active":true}},{"kind":"Project","apiVersion":"odo.openshift.io/v1alpha1","metadata":{"name":"myproject","creationTimestamp":null},"spec":{"apps":["myapp"]},"status":{"active":false}},{"kind":"Project","apiVersion":"odo.openshift.io/v1alpha1","metadata":{"name":"odo2-1555323251","creationTimestamp":null},"spec":{"apps":["myapp"]},"status":{"active":false}}]}
```

The extra output added in the actual output pasted below causing the mismatch. So project ```odo2-1555323251``` is being added in the output. IMO restructure of spec would be helpful. But it surprises me that way it is not reproducible all the time.
```
{"kind":"Project","apiVersion":"odo.openshift.io/v1alpha1","metadata":{"name":"odo2-1555323251","creationTimestamp":null},"spec":{"apps":["myapp"]},"status":{"active":false}}
```

However it's good to have reuse of ```gomega``` library instead of writing the same library externally.

**Comment by mohammedzee1000** [comment]
We actually have a mismatch. The expected and actual do not match. We have bigger problems apparently. Is the previous test state spilling over?

**Comment by amitkrout** [comment]
Created - https://github.com/openshift/odo/pull/1627 for e2e_test namespace clean up

**Comment by amitkrout** [comment]
> We actually have a mismatch. The expected and actual do not match. We have bigger problems apparently. Is the previous test state spilling over?

Few days back it was not the issue i guess. Seems a regression to me

**Comment by girishramnani** [comment]
/retest
checking if this happens again

**Comment by kadel** [comment]
> @kadel I am not fully sure that this would work all the time. TBH `gomega` matcher will be using similar kind of logic like `compareJSON`
> 
> Analysis :
> 
> ```
> desired := {"kind":"List","apiVersion":"odo.openshift.io/v1alpha1","metadata":{},"items":[{"kind":"Project","apiVersion":"odo.openshift.io/v1alpha1","metadata":{"name":"json-test","creationTimestamp":null},"spec":{"apps":["myapp"]},"status":{"active":true}},{"kind":"Project","apiVersion":"odo.openshift.io/v1alpha1","metadata":{"name":"myproject","creationTimestamp":null},"spec":{"apps":["myapp"]},"status":{"active":false}}]}
> ```
> Copied actual output from https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_odo/1601/pull-ci-openshift-odo-master-e2e-core/523
> 
> ```
> actaul := {"kind":"List","apiVersion":"odo.openshift.io/v1alpha1","metadata":{},"items":[{"kind":"Project","apiVersion":"odo.openshift.io/v1alpha1","metadata":{"name":"json-test","creationTimestamp":null},"spec":{"apps":["myapp"]},"status":{"active":true}},{"kind":"Project","apiVersion":"odo.openshift.io/v1alpha1","metadata":{"name":"myproject","creationTimestamp":null},"spec":{"apps":["myapp"]},"status":{"active":false}},{"kind":"Project","apiVersion":"odo.openshift.io/v1alpha1","metadata":{"name":"odo2-1555323251","creationTimestamp":null},"spec":{"apps":["myapp"]},"status":{"active":false}}]}
> ```
> The extra output added in the actual output pasted below causing the mismatch. So project `odo2-1555323251` is being added in the output. IMO cleanup of spec would be helpful. Locally it can be reproducible if `e2e_test.go` then followed by `json_test.go` runs on the same cluster. The namespace created by `e2e_test.go` should be cleaned up then only i hope no json mismatch will appear.
> 
> ```
> {"kind":"Project","apiVersion":"odo.openshift.io/v1alpha1","metadata":{"name":"odo2-1555323251","creationTimestamp":null},"spec":{"apps":["myapp"]},"status":{"active":false}}
> ```
> However it's good to have reuse of `gomega` library instead of writing the same library externally.

hmm, that is new. The issue that I saw was that the `compareJSON` was returning false even if the JSON output matched.

**Comment by surajnarwade** [comment]
@kadel , same tests passed on travis but failed on openshift CI ? :sob:

**Comment by amitkrout** [comment]
@kadel pr #1627 went in. Can you please rebase

**Comment by kadel** [comment]
> @kadel pr #1627 went in. Can you please rebase

done

**Comment by amitkrout** [comment]
> @kadel , same tests passed on travis but failed on openshift CI ? 😭

@surajnarwade Yes, it is expected as e2e_test and json_test do not run on same cluster in travis where as in OpenShift CI both are run on same cluster.

**Comment by kadel** [comment]
/retest 

```
unable to update DeploymentConfig image for nodejs component: unable to update the current DeploymentConfig nodejs-myapp: unable to wait for DeploymentConfig nodejs-myapp to update: Timed out waiting for annotation to update
```

**Comment by surajnarwade** [comment]
```
•Creating a new project: fjtwaphyjw
Running command: oc new-project fjtwaphyjw --skip-config-write
Project "fjtwaphyjw" created on server "https://api.ci-op-xxkkzxy1-5186a.origin-ci-int-aws.dev.rhcloud.com:6443".

To switch to this project and start adding applications, use:

    oc project fjtwaphyjw
Result: 
 stdout: Project "fjtwaphyjw" created on server "https://api.ci-op-xxkkzxy1-5186a.origin-ci-int-aws.dev.rhcloud.com:6443".

To switch to this project and start adding applications, use:

    oc project fjtwaphyjw

 stderr: 
 exitcode: 0 
Created dir: /tmp/954607284
Current working dir: /go/src/github.com/openshift/odo/tests/e2e
Setting current dir to: /tmp/954607284
Running command: odo component create nodejs nodejs --app nodejs-push-test --project fjtwaphyjw
 ✗  this directory already contains a component
Result: 
 stdout: 
 stderr: ✗  this directory already contains a component
 
 exitcode: 1 
Setting current dir to: /go/src/github.com/openshift/odo/tests/e2e
Deleting project: fjtwaphyjw
Running command: oc delete project fjtwaphyjw --now
project.project.openshift.io "fjtwaphyjw" deleted
Result: 
 stdout: project.project.openshift.io "fjtwaphyjw" deleted

 stderr: 
 exitcode: 0 
Deleating dir: /tmp/954607284

------------------------------
• Failure [1.931 seconds]
odoCmpE2e Component tests Test odo push with --source and --config flags when project flag(--project) is used when using current directory [It] create local nodejs component and push source and code separately 
/go/src/github.com/openshift/odo/tests/e2e/component.go:532

  Expected
      <int>: 1
  to equal
      <int>: 0

  /go/src/github.com/openshift/odo/tests/e2e/helper/helper_run.go:38
------------------------------
Creating a new project: uktwtvfbee
Running command: oc new-project uktwtvfbee --skip-config-write
Project "uktwtvfbee" created on server "https://api.ci-op-xxkkzxy1-5186a.origin-ci-int-aws.dev.rhcloud.com:6443".

To switch to this project and start adding applications, use:

    oc project uktwtvfbee
Result: 
 stdout: Project "uktwtvfbee" created on server "https://api.ci-op-xxkkzxy1-5186a.origin-ci-int-aws.dev.rhcloud.com:6443".

To switch to this project and start adding applications, use:

    oc project uktwtvfbee

 stderr: 
 exitcode: 0 
Created dir: /tmp/811010691
Current working dir: /go/src/github.com/openshift/odo/tests/e2e
Setting current dir to: /tmp/811010691
Running command: odo component create nodejs nodejs-push-atonce --app nodejs-push-test --project uktwtvfbee
 ✗  this directory already contains a component
Result: 
 stdout: 
 stderr: ✗  this directory already contains a component
 
 exitcode: 1 
Setting current dir to: /go/src/github.com/openshift/odo/tests/e2e
Deleting project: uktwtvfbee
Running command: oc delete project uktwtvfbee --now
project.project.openshift.io "uktwtvfbee" deleted
Result: 
 stdout: project.project.openshift.io "uktwtvfbee" deleted

 stderr: 
 exitcode: 0 
Deleating dir: /tmp/811010691
• Failure [1.945 seconds]
odoCmpE2e Component tests Test odo push with --source and --config flags when project flag(--project) is used when using current directory [It] create local nodejs component and push source and code at once 
/go/src/github.com/openshift/odo/tests/e2e/component.go:564

  Expected
      <int>: 1
  to equal
      <int>: 0

  /go/src/github.com/openshift/odo/tests/e2e/helper/helper_run.go:38
------------------------------
Creating a new project: scfdhqbauu
Running command: oc new-project scfdhqbauu --skip-config-write
Project "scfdhqbauu" created on server "https://api.ci-op-xxkkzxy1-5186a.origin-ci-int-aws.dev.rhcloud.com:6443".

To switch to this project and start adding applications, use:

    oc project scfdhqbauu
Result: 
 stdout: Project "scfdhqbauu" created on server "https://api.ci-op-xxkkzxy1-5186a.origin-ci-int-aws.dev.rhcloud.com:6443".

To switch to this project and start adding applications, use:

    oc project scfdhqbauu

 stderr: 
 exitcode: 0 
Created dir: /tmp/917037062
Running command: odo component create nodejs nodejs --context /tmp/917037062 --app nodejs-push-context-test --project scfdhqbauu
 ✗  this directory already contains a component
Result: 
 stdout: 
 stderr: ✗  this directory already contains a component
 
 exitcode: 1 
Deleting project: scfdhqbauu
Running command: oc delete project scfdhqbauu --now
project.project.openshift.io "scfdhqbauu" deleted
Result: 
 stdout: project.project.openshift.io "scfdhqbauu" deleted

 stderr: 
 exitcode: 0 
Deleating dir: /tmp/917037062
• Failure [1.925 seconds]
odoCmpE2e Component tests Test odo push with --source and --config flags when project flag(--project) is used when --context is used [It] create local nodejs component and push source and code separately 
/go/src/github.com/openshift/odo/tests/e2e/component.go:593

  Expected
      <int>: 1
  to equal
      <int>: 0

  /go/src/github.com/openshift/odo/tests/e2e/helper/helper_run.go:38
------------------------------
Creating a new project: qfrskldbxn
Running command: oc new-project qfrskldbxn --skip-config-write
Project "qfrskldbxn" created on server "https://api.ci-op-xxkkzxy1-5186a.origin-ci-int-aws.dev.rhcloud.com:6443".

To switch to this project and start adding applications, use:

    oc project qfrskldbxn
Result: 
 stdout: Project "qfrskldbxn" created on server "https://api.ci-op-xxkkzxy1-5186a.origin-ci-int-aws.dev.rhcloud.com:6443".

To switch to this project and start adding applications, use:

    oc project qfrskldbxn

 stderr: 
 exitcode: 0 
Created dir: /tmp/126565293
Running command: odo component create nodejs nodejs-push-atonce --app nodejs-push-context-test --context /tmp/126565293 --project qfrskldbxn
 ✗  this directory already contains a component
Result: 
 stdout: 
 stderr: ✗  this directory already contains a component
 
 exitcode: 1 
Deleting project: qfrskldbxn
Running command: oc delete project qfrskldbxn --now
project.project.openshift.io "qfrskldbxn" deleted
Result: 
 stdout: project.project.openshift.io "qfrskldbxn" deleted

 stderr: 
 exitcode: 0 
Deleating dir: /tmp/126565293
```

Looks like cleanup is not happening properly.

**Comment by kadel** [comment]
/test e2e-core

```
go test -v github.com/openshift/odo/tests/e2e --ginkgo.focus="odoe2e" -ginkgo.succinct -timeout 30m
=== RUN   TestOdo
[1556019353] odo test suite - 27/92 specs SSSSSSSSSSSSSSS•••Running command: odo create nodejs
 ✗  Please log in to the cluster
Result: 
 stdout: 
 stderr: ✗  Please log in to the cluster
```

**Comment by kadel** [comment]
```
secret/htpasswd-secret created
Warning: oc apply should be used on resource created by either oc create --save-config or oc apply
oauth.config.openshift.io/cluster configured
Failed to login as developer
```
/retest

**Comment by kadel** [comment]
> /hold

any reasons to keep the hold?

**Comment by kadel** [comment]
```
panic: test timed out after 30m0s
```

/test e2e-core

**Pull request merged**
