### PR TITLE
Update go 1.15

### PR DESCRIPTION
**Pull request by anandrkskd**
**What type of PR is this?**
/kind task

**What does this PR do / why we need it**:
By this we will be able to use the go 1.15 (latest available) on build target and tests.
**Which issue(s) this PR fixes**:

Fixes part of #4778 

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [ ] Update changelog

- [x] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by feloy** [comment]
Don't you want to also change the content of go.mod / go.sum to to reference go 1.15?

**Comment by anandrkskd** [comment]
ci/prow/v4.7-integration-e2e failed due to `could not run steps: step integration-e2e failed: failed to acquire lease for "aws-quota-slice": status 500 Internal Server Error, status code 500 `

**Pull request merged**
