### PR TITLE
Removed QE members from top-level reviewers

### PR DESCRIPTION
**Pull request by dharmit**
/kind cleanup

**What does this PR do / why we need it**:
To ensure right folks get selected by the bot for reviews

**Which issue(s) this PR fixes**:

Fixes - NA

### CODE REVIEW

**Comment by valaparthvi** [comment]
What about reviewing files from the `tests` dir? The OWNER file in tests does not have any reviewer, would QE be assigned to review changes made to tests?

**Comment by dharmit** [comment]
> What about reviewing files from the `tests` dir? The OWNER file in tests does not have any reviewer, would QE be assigned to review changes made to tests?

Yeah, they could be.

**Comment by dharmit** [comment]
@valaparthvi updated. PTAL.

**Review by rnapoles-rh — COMMENTED** [review]
/lgtm

**Pull request merged**
