### PR TITLE
Updates `odo describe` output

### PR DESCRIPTION
**Pull request by cdrage**
Updates the `odo describe` output to be a bit more intuitive / better
looking.

### CODE REVIEW

**Comment by cdrage** [comment]
See the comparison below:


### New

Screenshot from 2019-10-02 15-43-01


### Old

Screenshot from 2019-10-02 15-44-15

**Comment by girishramnani** [comment]
Looks the same on windows?

**Comment by girishramnani** [comment]
as a follow up show we change the output of `app describe` and `catalog describe` to the same **Bold**  headers?

**Comment by cdrage** [comment]
@girishramnani Yes, we should change it in `app describe` and `catalog describe` too. But that'll be for a different PR. We should get this one merged in first.

**Comment by girishramnani** [comment]
Cool,
/approve

**Comment by girishramnani** [comment]
An issue to track the follow up task would be great @cdrage

**Pull request merged**
