### PR TITLE
Validate application exist before describe it

### LINKED ISSUE #3348: odo app describe need provide clearer message when app not exist
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:**

[jichen@jjtest2 odo]$ odo version
odo v1.2.2 (a15a99e)

## How did you run odo exactly?
```
$ odo app describe t --project myproject
Application t has no components or services deployed.


[jichen@jjtest2 nodejs-ex]$ odo app delete  te
 ✗  te app does not exists

```

better to be 
```
]$ dist/bin/linux-amd64/odo app describe t --project myproject
 ✗  t app does not exists

```

### PR DESCRIPTION
**Pull request by jichenjc**
**What type of PR is this?**
> Uncomment only one ` /kind` line, and delete the rest.
> For example, `> /kind bug` would simply become: `/kind bug`

 /kind bug

**What does does this PR do / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #3348

**How to test changes / Special notes to the reviewer**:

`odo app describe t --project myproject` can be used to do test

### CODE REVIEW

**Comment by mik-dass** [comment]
@jichenjc Can you please add a note on how to test this PR?

**Comment by jichenjc** [comment]
@mik-dass done, added in commit msg, thanks

**Pull request merged**
