### PR TITLE
resolved resource limit not reflecting on unsetting

### PR DESCRIPTION
**Pull request by girishramnani**
## What is the purpose of this change? What does it change?
resolved resource limit not reflecting on unsetting.

## Was the change discussed in an issue?
fixes https://github.com/openshift/odo/issues/1576

## How to test changes?

```
odo create java --port 8080 --port 8088
odo config set memory 2Gi
odo push
oc get pod <pod-name> -o yaml # should have memory
odo config unset memory
oc get pod <pod-name> -o yaml # should not have memory
```

### CODE REVIEW

**Comment by kadel** [comment]
/hold
no tests :-(

**Comment by kadel** [comment]
@girishramnani how are tests going? We just need one simple test that verifies that the value is unset from the DC. It doesn' have to be the whole e2e scenario just one simple integration test case

**Comment by kadel** [comment]
👍 

/lgtm

**Comment by amitkrout** [comment]
Test looks awesome to me. 👍

**Pull request merged**
