### PR TITLE
Delete devfile when creation fails

### LINKED ISSUE #4939: `odo create` errored out but created devfile.yaml
/kind bug

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:**

## How did you run odo exactly?

```
▶ mkdir asdf
▶ ls

▶ odo create nodejs --starter=ffff
Devfile Object Validation
 ✓  Checking devfile existence [24770ns]
 ✓  Creating a devfile component from registry: DefaultDevfileRegistry [55600ns]
Validation
 ✓  Validating if devfile name is correct [33970ns]
 ✗  the project: ffff specified in --starter does not exist, available projects: nodejs-starter

▶ ls
devfile.yaml
```

## Actual behavior
`odo create`  failed but `devfile.yaml` was created

## Expected behavior
if `odo create` fails it should not create `devfile.yaml

### PR DESCRIPTION
**Pull request by feloy**
/kind bug

**What does this PR do / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #4939 

**PR acceptance criteria**:

- [ ] Unit test 

- [x] Integration test 

- [ ] Documentation 

- [x] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by feloy** [comment]
/hold

Should fix some shadowed err in the function first

**Review by rnapoles-rh — COMMENTED** [review]
/lgtm

**Comment by rnapoles-rh** [comment]
Currently checking out ci/prow/psi-k8s-ibmc-integration-e2e, looks like can not ssh to the linux VM that runs tests against K8S cluster in IBM Cloud. So not related to this PR

**Review by dharmit — COMMENTED** [review]
/approve

**Pull request merged**
