### PR TITLE
Add documentation for `odo url create ` for host flag

### LINKED ISSUE #2832: Document use of "odo url create" for devfile in CLI and docs
/kind bug

## What versions of software are you using?

**Operating System:** all

**Output of `odo version`:** master

## How did you run odo exactly?
Tried `odo url create` for a component based on DevFile.
```sh
$ odo url create
 ✗  host must be provided in order to create ingress

$ odo url create -h
Create a URL for a component. The created URL can be used to access the specified component from outside the OpenShift cluster.

Usage:
  odo url create [url name] [flags]

Examples:
  # Create a URL with a specific name by automatically detecting the port used by the component
  odo url create example
  # Create a URL for the current component with a specific port
  odo url create --port 8080
  
  # Create a URL with a specific name and port
  odo url create example --port 8080

Flags:
      --context string      Use given context directory as a source for component settings
      --devfile string      Path to a devfile.yaml (default "./devfile.yaml")
  -h, --help                Help for create
      --host string         Cluster ip for this URL
      --now                 Push changes to the cluster immediately
      --port int            Port number for the url of the component, required in case of components which expose more than one service port (default -1)
      --secure              Creates a secure https url
      --tls-secret string   Tls secret name for the url of the component if the user bring his own tls secret

Additional Flags:
  -v, --v Level              Log level for V logs. Level varies from 0 to 9 (default 0).
      --vmodule moduleSpec   Comma-separated list of pattern=N settings for file-filtered logging
```

## Actual behavior
 Command failed asking me to provide a value for `host`. But there's no example for how this can be done in `odo url create -h` or in the docs.

## Expected behavior
There should at least be CLI docs (i..e. and example in output of `odo url create -h`) for this.

I understand that adding it to documentation might take some time since this is experimental and subject to change.

### PR DESCRIPTION
**Pull request by dharmit**
**What type of PR is this?**

/kind documentation
[skip ci]

**What does does this PR do / why we need it**:
We need it because it's not clear as to how to use `odo url create` with devfile based components.

**Which issue(s) this PR fixes**:
Fixes #2832 

**How to test changes / Special notes to the reviewer**:
Enable the experimental mode and check the output of `odo url create -h` command.

### CODE REVIEW

**Comment by prietyc123** [comment]
Having flake and will be covered in the issue https://github.com/openshift/odo/issues/2877

/retest

**Comment by dharmit** [comment]
@cdrage this one's flagged as documentation and has `[skip-ci]` in the opening comment. Yet it's being tested. Am I missing something here?

**Comment by cdrage** [comment]
@dharmit this is actually a CLI change, you weren't supposed to add `[skip ci]` since this is directly changing the CLI.

Documentation tag / skipping CI is more meant for actual `.adoc` files :)

**Pull request merged**
