### PR TITLE
[WIP] Refactor idea

### PR DESCRIPTION
**Pull request by mik-dass**
**What type of PR is this?**
> Uncomment only one ` /kind` line, and delete the rest.
> For example, `> /kind bug` would simply become: `/kind bug`

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind failing-test
> /kind feature
> /kind flake
> /kind code-refactoring
>
> Documentation changes: Please include [skip ci] in your commit message as well
> /kind documentation
> [skip ci]

**What does does this PR do / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #?

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [ ] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by metacosm** [comment]
CI should not run on this… 🤦

**Comment by mik-dass** [comment]
> CI should not run on this… facepalm

Sorry about that, forgot to mark this as a draft PR.

**Comment by metacosm** [comment]
Please do not force push, this makes it difficult to comment and follow changes.

**Comment by metacosm** [comment]
@mik-dass @kadel I think we need to step back a little bit and discuss what needs to vary because, indeed, looking at the current design there are several options when it comes to isolating implementations but we need to take some decisions as to what we want to allow as far as variations and assumptions (i.e. is everything going to be put on a k8s cluster eventually or not). Without clarifying this, we will have a hard time coming up with a design that makes sense.

**Comment by mik-dass** [comment]
> @mik-dass @kadel I think we need to step back a little bit and discuss what needs to vary because, indeed, looking at the current design there are several options when it comes to isolating implementations but we need to take some decisions as to what we want to allow as far as variations and assumptions (i.e. is everything going to be put on a k8s cluster eventually or not). Without clarifying this, we will have a hard time coming up with a design that makes sense.

Indeed we need to discuss this and decide on the variations.

**Comment by girishramnani** [comment]
we should close this now?

**Pull request closed without merging**
