### PR TITLE
Remove metadata.namespace from ALM Examples

### LINKED ISSUE #5019: service creation fails with wrong namespace
/kind bug


## What versions of software are you using?

**Operating System:** Win10Pro

**Output of `odo version`:**

```
odo v2.3.0 (089b8ea26)

Server: https://api.sandbox.x8i5.p1.openshiftapps.com:6443
Kubernetes: v1.20.0+558d959
```

## How did you run odo exactly?
```
odo service create rhoas-operator.0.7.8/KafkaConnection
odo push

```
## Actual behavior

```
Validation                                                                                                                                                                                     
 V  Validating the devfile [0ns]                                                                                                                                                               
                                                                                                                                                                                               
Creating Services for component ncomp                                                                                                                                                          
 X  Failed to start component with name "ncomp". Error: Failed to create the component: failed to create service(s) associated with the component: the namespace of the provided object does not match the namespace sent on the request                                                                                                                                                      
```
                                                                                                                                                                                               

## Expected behavior

Service should be created

## Any logs, error output, etc?

`odo service create rhoas-operator.0.7.8/KafkaConnection --dry-run` gives the following output:

```
apiVersion: rhoas.redhat.com/v1alpha1                       
kind: KafkaConnection                                       
metadata:                                                   
  labels:                                                   
    app.kubernetes.io/component: external-service           
    app.kubernetes.io/managed-by: rhoas                     
  name: example                                             
  namespace: example-namespace                              
spec:                                                       
  accessTokenSecretName: rh-managed-services-api-accesstoken
  credentials:                                              
    serviceAccountSecretName: service-account-secret        
  kafkaId: exampleId                                        
```

### PR DESCRIPTION
**Pull request by feloy**
**What type of PR is this?**

/kind bug

**What does this PR do / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #5019 

**PR acceptance criteria**:

- [x] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [x] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

```
odo service create rhoas-operator.0.9.0/ServiceRegistryConnection
odo push
```

### CODE REVIEW

**Comment by feloy** [comment]
/test psi-kubernetes-integration-e2e

```
[ssh:Fedora-32-minikube] [Fail] odo devfile describe command tests when devfile has missing metadata when projectType is missing when the component is pushed [BeforeEach] should show the language for 'Type' in odo describe 
```

**Comment by feloy** [comment]
/test psi-kubernetes-integration-e2e

```
Ran for 4h0m30s                              
```

**Review by valaparthvi — COMMENTED** [review]
The code lgtm, but don't we need to add integration test?

**Comment by feloy** [comment]
> The code lgtm, but don't we need to add integration test?

A unit test covers the change, and I can see a risk by using an integration test, that we are not sure to find an operator that will keep a namespace in their examples in the future: we could start with the Crunchy operator which currently adds a namespace in the example, but could remove it in the future and break our integration test.

**Pull request merged**
