### PR TITLE
Upgrade the minikube version on travis CI

### LINKED ISSUE #2928: devfile odo push failed to start component on kubernetes cluster
/kind bug

## What versions of software are you using?

**Operating System:**
All supported

**Output of `odo version`:**
master

## How did you run odo exactly?

Steps to reproduce:

1. Create single node kubernetes cluster using **minikube [0.25.2](https://github.com/kubernetes/minikube/releases/tag/v0.25.2)**
2. Enable experimental mode
3. git clone https://github.com/che-samples/web-nodejs-sample.git && cd che-samples
4. odo create nodejs --project zxobygmpyf
5. odo push --devfile devfile.yaml --namespace zxobygmpyf

## Actual behavior

Its throwing error while ```odo push``` in starting the component on kuberenetes cluster.

**NOTE:** minikube version 0.25.2 is being used for testing

## Expected behavior

The component should get pushed in the deployment directory.

## Any logs, error output, etc?

```
Running git with args [git clone https://github.com/che-samples/web-nodejs-sample.git /tmp/394302036/projectDir]
[git] Cloning into '/tmp/394302036/projectDir'...
Setting current dir to: /tmp/394302036/projectDir
Running odo with args [odo create nodejs --project zxobygmpyf umffvx]
[odo] Experimental mode is enabled, use at your own risk
[odo] 
[odo] Validation
[odo]  •  Checking devfile compatibility  ...
 ✓  Checking devfile compatibility [33281ns]
[odo]  •  Validating devfile component  ...
 ✓  Validating devfile component [64477ns]
[odo] 
[odo] Please use `odo push` command to create the component with source deployed
Running odo with args [odo push --devfile devfile.yaml --namespace zxobygmpyf]
[odo]  •  Push devfile component umffvx  ...
[odo]  ✗  Failed to start component with name umffvx.
[odo] Error: Failed to create the component: unable to create or update component: unable to create Deployment umffvx: the server could not find the requested resource
Deleting project: zxobygmpyf
Running kubectl with args [kubectl delete namespaces zxobygmpyf]
[kubectl] namespace "zxobygmpyf" deleted
Setting current dir to: /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile
Deleting dir: /tmp/394302036
```
Detailed logs : https://travis-ci.com/github/openshift/odo/jobs/321025144#L617

### LINKED ISSUE #3055: Odo push fails on 3.11 cluster having docker version (18.06.0-ce) running on travis xenial distro
/kind bug

## What versions of software are you using?

**Operating System:**
All supported

**Output of `odo version`:**
master

## How did you run odo exactly?
Running tests jobs on travis CI

## Actual behavior
Hitting error https://travis-ci.com/github/openshift/odo/jobs/324857465#L582 and some more different errors in the test running on openshift 3.11 with xenial distro of travis CI.

I am suspecting ```oc cluster up``` is having compatibility issue with the default docker available on xenial distro causing error like i mentioned above.

## Expected behavior

Tests associated with openshift should also run on xenial distro of travis CI.

## Any logs, error output, etc?
 more details of errors : https://github.com/openshift/odo/pull/2913/checks?check_run_id=632261884

### PR DESCRIPTION
**Pull request by prietyc123**
**What type of PR is this?**

/kind feature

**What does does this PR do / why we need it**:

```odo push``` is supported only on minikube version 0.25+ . So upgrading minikube version on travis CI

**Which issue(s) this PR fixes**:

Fixes #2928 
Fixes #3055 

**How to test changes / Special notes to the reviewer**:
devfile integration test should run on upgraded version of minikube.

### CODE REVIEW

**Comment by kadel** [comment]
/hold 
waiting for travis to pass

**Comment by prietyc123** [comment]
> /hold
> waiting for travis to pass

Travis passed. 

/hold cancel

**Pull request merged**
