### PR TITLE
Fixing os.GetWd() usage for getting component name

### LINKED ISSUE #2959: Should use context to get appropriate envinfo instead of using os.Getwd()
/kind bug

Since context is currently not supported in experimental mode, we use `os.Getwd()` to get the env.yaml
https://github.com/openshift/odo/blob/5a26a56426b5d4e214c0817c2820350d9b862e0a/pkg/odo/cli/component/devfile.go#L116-L117
https://github.com/openshift/odo/blob/5a26a56426b5d4e214c0817c2820350d9b862e0a/pkg/odo/cli/component/devfile.go#L130-L131
https://github.com/openshift/odo/blob/10826cc3f43c74ebadd917c3c53e9b40d6853aa6/pkg/devfile/adapters/docker/component/utils.go#L292

However, after context is supported, the project might be under a different directory; we need to switch to use context instead of using the current directory.

This issue is now blocked by experimental mode context support.

### PR DESCRIPTION
**Pull request by mohammedzee1000**
Signed-off-by: Mohammed Zeeshan Ahmed <mohammed.zee1000@gmail.com>

**What type of PR is this?**
> Uncomment only one ` /kind` line, and delete the rest.
> For example, `> /kind bug` would simply become: `/kind bug`

> /kind cleanup
> /kind deprecation
> /kind design
> /kind failing-test
> /kind feature
> /kind flake
/kind code-refactoring
>
> Documentation changes: Please include [skip ci] in your commit message as well
> /kind documentation
> [skip ci]

**What does does this PR do / why we need it**:
See title

**Which issue(s) this PR fixes**:
Fixes #2959 

**PR acceptance criteria**:

- [ ] Existing tests should not break

- [ ] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by girishramnani** [comment]
Unit test failed

**Comment by mohammedzee1000** [comment]
Yep, copy paste golangci issue now fixed @girishramnani

**Comment by mohammedzee1000** [comment]
Timeout error: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_odo/3844/pull-ci-openshift-odo-master-v4.5-integration-e2e/1298851539779063808
/retest

**Review by dharmit — APPROVED** [review]
/lgtm

**Comment by mohammedzee1000** [comment]
Timeout error https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_odo/3844/pull-ci-openshift-odo-master-v4.5-integration-e2e/1298934238824894464

/retest

**Pull request merged**
