### PR TITLE
Change Odo References to odo

### PR DESCRIPTION
**Pull request by danielhelfand**
## What is the purpose of this change? What does it change?
This started as just addressing the situation below, but now changes all `Odo` references to `odo` with the exception of code and comments.

Corrects typo for `utils` description with `odo --help`. 

```
utils       Utilities for terminal commands and modifying Odo configurations (terminal)
```

## Was the change discussed in an issue?
No

## How to test changes?
Verify that no `Odo` references are present for command messaging/descriptions.

### CODE REVIEW

**Comment by danielhelfand** [comment]
@amitkrout Thanks for pointing out other `Odo` references. I have gone through and think I have found them all.

**Comment by amitkrout** [comment]
```
error: could not run steps: step [release:latest] failed: release "release-latest" failed: pod was deleted while ci-operator step was waiting for it
```
/test e2e-scenarios

**Comment by amitkrout** [comment]
Ping @cdrage

**Comment by cdrage** [comment]
@danielhelfand Changes look good!

Just to make sure, you used the `make generate-cli-reference` command to generate the doc, correct?

**Comment by danielhelfand** [comment]
@cdrage Just verified with `make generate-cli-reference`. Should be good.

**Pull request merged**
