### PR TITLE
Commenting test spec due to config issue #1895

### PR DESCRIPTION
**Pull request by amitkrout**
## What is the purpose of this change? What does it change?

Comment out the affected test
## Was the change discussed in an issue?
No, but the reason is described here in - https://github.com/openshift/odo/issues/1895#issuecomment-510114737

## How to test changes?

make test-e2e-scenarios

### CODE REVIEW

**Comment by amitkrout** [comment]
ping @kadel

**Comment by amitkrout** [comment]
```
[odo] Pushing to component nodejs of type local
[odo]  •  Waiting for component to start  ...
[odo]  ✗  Waiting for component to start [4m]
[odo]  ✗  waited 4m0s but couldn't find running pod matching selector: 'deploymentconfig=nodejs-app'
```
/test integration

**Comment by girishramnani** [comment]
This PR https://github.com/openshift/odo/pull/1900 resolved the tests so we might not need to uncomment them

**Comment by amitkrout** [comment]
> This PR #1900 resolved the tests so we might not need to uncomment them

@girishramnani Thanks for the quick pr. Will try pr #1900 locally

**Comment by amitkrout** [comment]
Closing as #1900 will fix the regression issue. So no need to comment any test spec.

**Pull request closed without merging**
