### PR TITLE
[WIP] Testing update from local to git

### PR DESCRIPTION
**Pull request by mik-dass**
this is for replicating #1782

### CODE REVIEW

**Comment by mik-dass** [comment]
```
✗  Failed to create component with name cmp-git. Please use `odo config view` to view settings used to create component. Error: unable to wait for build cmp-git-testing-1 to run: timed out waiting for the condition
```
/retest

**Comment by mik-dass** [comment]
```
✗  Applying configuration [1m]
[odo]  ✗  Failed To Update Config To Component Deployed
```
/retest

**Comment by mik-dass** [comment]
```
✓  Waiting for build to finish [2m]
[odo]  ✗  Failed To Update Config To Component Deployed
[odo]  ✗  Applying configuration [2m]
```
/retest

**Comment by amitkrout** [comment]
> ```
> ✓  Waiting for build to finish [2m]
> [odo]  ✗  Failed To Update Config To Component Deployed
> [odo]  ✗  Applying configuration [2m]
> ```
> 
> /retest

So you able to reproduce the flake, right ?

**Comment by mik-dass** [comment]
> So you able to reproduce the flake, right ?

The test scenario I uncommented, passed. This is a different scenario and a known flake.

**Comment by mik-dass** [comment]
@amitkrout It passed again :D

**Comment by mik-dass** [comment]
```
[odo]  ✗  waited 4m0s but couldn't find running pod matching selector: 'deploymentconfig=python-pyapp'
```
/retest

**Comment by mik-dass** [comment]
```
Submitted failure event to sentry (id=f199902d654b46d193a9e73bffce5f2a)
error: could not run steps: step integration failed: template pod "integration" failed: the pod ci-op-dv00v55p/integration failed after 2h30m23s (failed containers: lease, setup, test): ContainerFailed one or more containers exited
```
/retest

**Comment by mik-dass** [comment]
```
✗  Failed To Update Config To Component Deployed
```
in `should list appropriate URLs and push message`
/retest

**Comment by mik-dass** [comment]
```
git clone https://github.com/onsi/ginkgo /go/src/github.com/onsi/ginkgo
fatal: unable to access 'https://github.com/onsi/ginkgo/': Could not resolve host: github.com; Unknown error
package github.com/onsi/ginkgo/ginkgo: exit status 128
```
/retest

**Comment by mik-dass** [comment]
```
✗  Applying configuration [2m]
[odo] I0808 08:21:58.112014   19906 cmdutils.go:26] Error:
[odo] unable to update DeploymentConfig image for cmp-git component: unable to update the current DeploymentConfig cmp-git-testing: unable to start deployment: unable to instantiate Deployment for cmp-git-testing: replicationcontrollers "cmp-git-testing-2" not found
[odo]  ✗  Failed To Update Config To Component Deployed
```
@amitkrout Finally was able to reproduce the error

**Comment by mik-dass** [comment]
closing this for later

**Pull request closed without merging**
