### PR TITLE
Validation spinners refactor

### PR DESCRIPTION
**Pull request by niconosenzo**
**What type of PR is this?**

/kind code-refactoring

**What does does this PR do / why we need it**:
This PR redefine the "Validation" header into below different headers:

- Devfile Object Validation 
- Devfile Component Name Validation
- Supportability Validation

Also re-phrased ValidateK8sResourceName() spinner so it now reflects what kind of check it performs. 
`odo create` output now looks like:

<p align="center">

</p>

And,
<p align="center">

</p>

**Which issue(s) this PR fixes**:
Address issue #3924 

Fixes #?

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [x] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by girishramnani** [comment]
the `Devfile Component Name` validation would always have a single check so we should keep it under the `Validation` header only.

**Comment by niconosenzo** [comment]
> the `Devfile Component Name` validation would always have a single check so we should keep it under the `Validation` header only.

@girishramnani so the headers would be like:

Devfile Object Validation
Validation (Merged Devfile Component Name Validation and Supportability Validation, both are single check validations).

Is that correct ?

**Comment by girishramnani** [comment]
Yes

**Comment by niconosenzo** [comment]
> Yes

Done.

**Pull request merged**
