### PR TITLE
Buming odo version for release

### PR DESCRIPTION
**Pull request by mohammedzee1000**
Signed-off-by: Mohammed Zeeshan Ahmed <mohammed.zee1000@gmail.com>

### CODE REVIEW

**Review by dharmit — APPROVED** [review]
/LGTM
/Approve

**Comment by girishramnani** [comment]
Reason https://github.com/openshift/odo/issues/4281#issuecomment-776085277

**Comment by kadel** [comment]
/hold cancel
No need to block release for this. We can't remove support for existing s2i LocalConfig components we don't know how many people use it. We can't risk breaking existing components.

**Comment by dharmit** [comment]
```
 [ssh:Fedora 32] [odo]  ✗  Waiting for component to start [5m] [WARNING x7: Failed]
[ssh:Fedora 32] [odo]  ✗  Failed to start component with name arjsby. Error: Failed to create the component: error while waiting for deployment rollout: timeout while waiting for arjsby deployment roll out\nFor more information to help determine the cause of the error, re-run with '-v'.
[ssh:Fedora 32] [odo] See below for a list of failed events that occured more than 5 times during deployment:
[ssh:Fedora 32] [odo] 
[ssh:Fedora 32] [odo]  NAME                                      COUNT  REASON  MESSAGE                        
[ssh:Fedora 32] [odo] 
[ssh:Fedora 32] [odo]  arjsby-5d6ff59fc6-r487l.16629cba447eb118  7      Failed  Error: secret                  
[ssh:Fedora 32] [odo]                                                           "arjsby-etcdcluster-example"   
[ssh:Fedora 32] [odo]                                                           not found                      
[ssh:Fedora 32] [odo] 
[ssh:Fedora 32] [odo] 
[ssh:Fedora 32] Deleting project: dhblyehqdf
[ssh:Fedora 32] Running odo with args [odo project delete dhblyehqdf -f] 
```
#4301

/override ci/prow/v4.6-integration-e2e

**Comment by mohammedzee1000** [comment]
It appears the bot has forgotten to merge this PR. It satisfied the conditions for merge, 3 hrs ago.
So taking action and merging manually so i can actually initate release today

**Pull request merged**
