### PR TITLE
Covering java component debug test

### LINKED ISSUE #2153: Add java integration tests for debug
As discussed in https://github.com/openshift/odo/pull/2043. we are currently testing only nodejs in odo debug.
We need to add java tests for odo debug as well.

### PR DESCRIPTION
**Pull request by amitkrout**
**What type of PR is this?**

/kind test

**What does does this PR do / why we need it**:
Adding integration test coverage for java debug test

**Which issue(s) this PR fixes**:

Fixes #2153 

**How to test changes / Special notes to the reviewer**:
make test-cmd-debug

### CODE REVIEW

**Comment by girishramnani** [comment]
@amitkrout any update on this?

**Comment by amitkrout** [comment]
> @amitkrout any update on this?

Actually i did not get time to update this pr. Will update and open it for review

**Comment by amitkrout** [comment]
@girishramnani This is a real failure. I can reproduce it locally too. Can you please have a look. 
```
Running odo with args [odo debug port-forward --local-port 36978 --context /tmp/447265959]
error while requesting: Get http://localhost:36978: dial tcp 127.0.0.1:36978: connect: connection refused
```

NOTE : I am using free free port in the test script

Details - https://travis-ci.com/github/openshift/odo/jobs/320371654#L1299

**Comment by prietyc123** [comment]
> @girishramnani This is a real failure. I can reproduce it locally too. Can you please have a look.
> 
> ```
> Running odo with args [odo debug port-forward --local-port 36978 --context /tmp/447265959]
> error while requesting: Get http://localhost:36978: dial tcp 127.0.0.1:36978: connect: connection refused
> ```
> 
> NOTE : I am using free free port in the test script
> 
> Details - https://travis-ci.com/github/openshift/odo/jobs/320371654#L1299

Ping @mik-dass @girishramnani

**Comment by mik-dass** [comment]
> @girishramnani This is a real failure. I can reproduce it locally too. Can you please have a look.

Does the port-forward command pass locally?

**Comment by amitkrout** [comment]
Issue https://github.com/openshift/odo/issues/2153 is removed from the current sprint, So i am closing this atm.

**Pull request closed without merging**
