### PR TITLE
Removes duplication of devfile parsing and validation

### PR DESCRIPTION
**Pull request by dharmit**
**What type of PR is this?**
/kind cleanup
/kind code-refactoring

**What does this PR do / why we need it**:
Parsing and Validation of devfile already happens in "Complete"
function.

**Which issue(s) this PR fixes**:

Fixes NA
Part of #4298 

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [x] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:
Tests should pass

### CODE REVIEW

**Comment by dharmit** [comment]
/hold

Some genuine failure with `odo create --now`.

**Comment by girishramnani** [comment]
Any update on this PR?

**Pull request closed without merging**
