### PR TITLE
Run component commands with and without shortcut commands

### LINKED ISSUE #2432: Run component command test with and without shortcuts commands
/kind bug

## What versions of software are you using?

**Operating System:**
All supported
**Output of `odo version`:**
master
## How did you run odo exactly?
make test-cmd-cmp
make test-cmd-cmp-sub

## Actual behavior
Component command with and without shortcuts commands are updated properly in the test file.

For example: 

https://github.com/openshift/odo/blob/master/tests/integration/component.go#L65. 

## Expected behavior

helper.CmdShouldPass("odo", append(args, "push", "--context", context, "-v4")...)

### PR DESCRIPTION
**Pull request by prietyc123**
/kind bug

**What does does this PR do / why we need it**:
Runs component commands with and without shortcut commands

**Which issue(s) this PR fixes**:

Fixes #2432 

**How to test changes / Special notes to the reviewer**:
```make test-cmd-cmp```
```make test-cmd-cmp-sub```

### CODE REVIEW

**Comment by amitkrout** [comment]
@prietyc123 Unnecessary files has been added to this fix. Please remove those

**Comment by prietyc123** [comment]
> @prietyc123 Unnecessary files has been added to this fix. Please remove those

That got added accidently. Now I have removed the unnecessary files.

**Pull request merged**
