### PR TITLE
Do not run e2e test in verbose

### LINKED ISSUE #2350: Don't run tests in verbose mode
We don't need to run all tests in verbose mode `-v`.
If the test fails it will automatically print all information.
For successful tests we don't need any information by default.

### PR DESCRIPTION
**Pull request by kadel**
**What kind of PR is this?**
/kind test

**What does does this PR do / why we need it**:
We have a lot of tests and running everithing in verbose mode create
output with few thousends of lines and it makes it really hard to find
failures.
Ginkgo is smart enought to dump all availble output when for failing
test even if verbose mode is not enabled.

**Which issue(s) this PR fixes**:

Fixes #2350

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by kadel** [comment]
/retest

some weird CI error
```
[odo]  ✗  invalid configuration: [context was not found for specified context: rzdqyanktr/api-ci-op-zivw5d4i-00a90-origin-ci-int-aws-dev-rhcloud-com:6443/developer, cluster has no server defined]
```

**Comment by cdrage** [comment]
/lgtm

Although tests are failing >.>

**Comment by amitkrout** [comment]
> /lgtm

/approve

**Comment by kadel** [comment]
small fix -> self approve
/approve

**Pull request merged**
