### PR TITLE
Adding plugin handler test makefile target

### PR DESCRIPTION
**Pull request by prietyc123**
**What type of PR is this?**

/kind feature

**What does does this PR do / why we need it**:

$SUBJECT It was missed in the make target. To run the individual target we need it.

**Which issue(s) this PR fixes**:

Fixes NA

**PR acceptance criteria**:

- [ ] Unit test 

- [x] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer**:

`make test-plugin-handler` as well as `make test-integration` should run

### CODE REVIEW

**Comment by girishramnani** [comment]
Is it present in .travis.yaml?

**Comment by prietyc123** [comment]
> Is it present in .travis.yaml?

No, I didn't find any. Let me add it to travis as well 👍

**Comment by girishramnani** [comment]
Cool

**Review by amitkrout — CHANGES_REQUESTED** [review]
Add the test target in travis CI

**Pull request merged**
