### PR TITLE
Update CI reference doc

### PR DESCRIPTION
**Pull request by amitkrout**
**What type of PR is this?**
/kind cleanup
/kind documentation
[skip ci]

**What does does this PR do / why we need it**:
Doc - https://github.com/openshift/odo/blob/master/docs/dev/ci-reference.adoc is outdated.
**Which issue(s) this PR fixes**:

Fixes - Updated https://github.com/openshift/odo/blob/master/docs/dev/ci-reference.adoc

NOTE: I was referring odo ci-reference doc for the current project i am working on and found the [doc](https://github.com/openshift/odo/blob/master/docs/dev/ci-reference.adoc) was referring to template base testing and travis CI snippet was pretty old. 

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [x] Documentation 

- [x] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:
https://github.com/openshift/odo/blob/master/docs/dev/ci-reference.adoc should be updated as per the recent ci structure used in odo.

### CODE REVIEW

**Review by mohammedzee1000 — APPROVED** [review]
Looks good
/lgtm

**Comment by amitkrout** [comment]
```
[odo]  ✗  Waiting for component to start [5m]
[odo]  ✗  Failed to start component with name szfwrg. Error: Failed to create the component: error while waiting for
 deployment rollout: timeout while waiting for szfwrg deployment roll out
```
Details log - https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_odo/4265/pull-ci-openshift-odo-master-v4.5-integration-e2e/1332269239624536064#1:build-log.txt%3A1366

@prietyc123 AFAIK similar or same failure has been tracked in some issues, if not please create an issue. 


@girishramnani @dharmit As this pr comprises only doc changes, then integration test job failure does not matter IMO. So you can overwrite the failure job just by applying ```/override v4.5-integration-e2e```

**Comment by dharmit** [comment]
> ```
> [odo]  ✗  Waiting for component to start [5m]
> [odo]  ✗  Failed to start component with name szfwrg. Error: Failed to create the component: error while waiting for
>  deployment rollout: timeout while waiting for szfwrg deployment roll out
> ```
> 
> 
> Details log - https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_odo/4265/pull-ci-openshift-odo-master-v4.5-integration-e2e/1332269239624536064#1:build-log.txt%3A1366
> 
> @prietyc123 AFAIK similar kind of or very same failure has been tracked in some issues, if not please create an issue.

#3256

**Comment by dharmit** [comment]
> @girishramnani @dharmit As this pr comprises only doc changes, then integration test job failure does not matter IMO. So you can overwrite the failure job just by applying `/override v4.5-integration-e2e` label

@amitkrout is there a doc where we can refer these commands? I'm sure I'd forget that if I can't refer it somewhere. :disappointed: 

overriding integration checks since this is docs PR.

/override v4.5-integration-e2e
/override v4.6-integration-e2e

**Comment by prietyc123** [comment]
> > @girishramnani @dharmit As this pr comprises only doc changes, then integration test job failure does not matter IMO. So you can overwrite the failure job just by applying `/override v4.5-integration-e2e` label
> 
> @amitkrout is there a doc where we can refer these commands? I'm sure I'd forget that if I can't refer it somewhere. 😞
> 
> overriding integration checks since this is docs PR.
> 
> /override v4.5-integration-e2e
> /override v4.6-integration-e2e

@dharmit Yes, we have documented it in our development guide - https://github.com/openshift/odo/blob/master/docs/dev/development.adoc#about-prow. But unfortunately the link https://deck-ci.svc.ci.openshift.org/command-help is broken.
This is correct link for prow commands - https://prow.ci.openshift.org/command-help. Please bookmark it for a quick access.
I will create a pr to consume this new working link.

**Comment by prietyc123** [comment]
> I will create a pr to consume this new working link.

Opened a PR https://github.com/openshift/odo/pull/4268

**Review by dharmit — APPROVED** [review]
/approve

**Pull request merged**
