### PR TITLE
Splitting configure-installer-test-cluster into a library.

### PR DESCRIPTION
**Pull request by mohammedzee1000**
Signed-off-by: Mohammed Zeeshan Ahmed <mohammed.zee1000@gmail.com>

#4199

/kind code-refactoring

**What does does this PR do / why we need it**:
Splits the script into a library that could be used individually.

**PR acceptance criteria**:

- [x] Nothing major breaks in the behavior of the scripts
- [x] We have lesser scripts to maintain
- [x] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by rnapoles-rh** [comment]
```
setupfirstprojectandvalidate() {
    # Setup project
    oc new-project myproject
    sleep 4
    oc version
    # Project list
    oc projects
```

firs project is setup but there is no validation that commands were successful

**Comment by dharmit** [comment]
Is this ready for review or is still WIP?

**Comment by girishramnani** [comment]
Like the readability 
/approve
/lgtm

**Pull request merged**
