### PR TITLE
Bumping odo version from v2.0.3 to v2.0.4

### PR DESCRIPTION
**Pull request by mohammedzee1000**
Signed-off-by: Mohammed Zeeshan Ahmed <mohammed.zee1000@gmail.com>

### CODE REVIEW

**Comment by mohammedzee1000** [comment]
/hold
Release of cli shifted to next week

**Comment by dharmit** [comment]
@mohammedzee1000 @prietyc123 this should go in after #4360, right?

**Review by dharmit — APPROVED** [review]
/approve

**Pull request merged**
