### PR TITLE
Adding link to Connector extension on Open VSX

### PR DESCRIPTION
**Pull request by brianking**
**What type of PR is this?**
> Uncomment only one ` /kind` line, and delete the rest.
> For example, `> /kind bug` would simply become: `/kind bug`

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind failing-test
> /kind feature
> /kind flake
> /kind code-refactoring
>
> Documentation changes: Please include [skip ci] in your commit message as well

/kind documentation
[skip ci]

**What does does this PR do / why we need it**:

Open VSX is an open registry for VS Code extensions. OpenShift Connector is listed there as well.

**Which issue(s) this PR fixes**:

Fixes #?

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [ ] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by dharmit** [comment]
@brianking thanks for your contirbution!

/ok-to-test
/approve
/lgtm

**Comment by dharmit** [comment]
Hey Brian, this PR's merged. A `retest` isn't going to do test anything. Is there something specific you're looking for?

**Comment by brianking** [comment]
@dharmit Noted. I was just blindly following instructions from the comment above. Apologies, I'm not familiar with the project's build/merge system.

**Pull request merged**
