### PR TITLE
[DO-NOT-MERGE]Separate out minikube script

### LINKED ISSUE #4287: Use PSI for running Kubernetes tests
Kubernetes tests that were earlier working on Travis need to run on PSI infrastructure.

### Acceptance Critera
- [ ] Kubernetes test results for every PR

### Scope of the issue 
https://github.com/openshift/odo/issues/4287#issuecomment-752359444
https://github.com/openshift/odo/issues/4287#issuecomment-754408501

/area testing
/priority high
/assign @mohammedzee1000

### PR DESCRIPTION
**Pull request by prietyc123**
**What type of PR is this?**

/kind feature

**What does does this PR do / why we need it**:
Separating out minikube script until we address https://github.com/openshift/odo/issues/4523 . Workarounds for 4523 are not helpful

**Which issue(s) this PR fixes**:

Fixes #4287 

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [ ] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:
kubernetes job should run successfully.

### CODE REVIEW

**Review by rnapoles-rh — APPROVED** [review]
/lgtm

**Comment by prietyc123** [comment]
I will keep it on hold until kubernetes job go green

**Comment by prietyc123** [comment]
fixes timeout for vm creation on jenkins.

/test psi-kubernetes-integration-e2e

**Comment by prietyc123** [comment]
Flake on psi end 
```
[ssh:Fedora 32] Cloning into 'amqp_ci_rcv_odo-minikube-pr-build_PR_4539/repo'...
[ssh:Fedora 32] fatal: unable to open /home/fedora/amqp_ci_rcv_odo-minikube-pr-build_PR_4539/repo/.git/objects/pack/tmp_pack_98T3tO: No such file or directory
[ssh:Fedora 32] fatal: index-pack failed
```
/test psi-kubernetes-integration-e2e

**Comment by prietyc123** [comment]
```
[ssh:Fedora 32] ++ minikube delete
[ssh:Fedora 32] ./scripts/kubernetes-all-test.sh: line 41: minikube: command not found
[ssh:Fedora 32] !!!run failed, skipping!!!
2021/03/24 10:08:35 : failed due to err Failed the test, see logs above ^
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2021-03-24T10:08:35Z"}
error: failed to execute wrapped command: exit status 1
``` 
has been fixed in https://github.com/openshift/odo/pull/4539/commits/939446bb7e44b01db060e0061b9a2d81bba2b2ab

**Comment by prietyc123** [comment]
Parameter issue has been resolve, so dropping off the idea to separate out the script.

**Pull request closed without merging**
