### PR TITLE
Updates the help usage of odo

### PR DESCRIPTION
**Pull request by cdrage**
This PR:
  - Modifies the output of running JUST `odo` similar to how `oc` does
  it.
  - There is now a difference between running `odo` and running `odo
  --help`
  - Removes "Normalize" for the long description since it was messing up
  newline formatting
  - Adds integration tests for help usage

Closes https://github.com/openshift/odo/issues/1672

Example of running JUST `odo`:

```sh
(OpenShift Do) odo is a CLI tool for running OpenShift applications in a fast and automated manner.
Reducing the complexity of deployment, odo adds iterative development without the worry of deploying your source code.

Find more information at https://github.com/openshift/odo

Get started by creating a new application:

 git clone https://github.com/openshift/nodejs-ex && cd nodejs-ex
 odo create nodejs
 odo push

Your nodejs application has now been deployed. odo has pushed the source code, built the application and deployed it on OpenShift.
You can now edit your code in real time and watch as odo automatically deploys your application.

 odo watch

To access your application, create a URL:

 odo url create myurl
 odo push

More information such as logs or what components you've deployed can be accessed with these commands:

 odo describe
 odo list
 odo log

To see a full list of commands, run 'odo --help'
```

### CODE REVIEW

**Comment by kadel** [comment]
/retest

https://github.com/openshift/odo/issues/2244

**Comment by amitkrout** [comment]
```
$ odo
(OpenShift Do) odo is a CLI tool for running OpenShift applications in a fast and automated manner.
Reducing the complexity of deployment, odo adds iterative development without the worry of deploying your source code.

Find more information at https://github.com/openshift/odo

Get started by creating a new application:

 git clone https://github.com/openshift/nodejs-ex && cd nodejs-ex
 odo create nodejs
 odo push

Your nodejs application has now been deployed. odo has pushed the source code, built the application and deployed it on OpenShift. 
You can now edit your code in real time and watch as odo automatically deploys your application.

 odo watch

To access your application, create a URL:

 odo url create myurl
 odo push

More information such as logs or what components you've deployed can be accessed with these commands:

 odo describe
 odo list
 odo log

To see a full list of commands, run 'odo --help'
Amits-MacBook-Pro:odo amit$ odo -h
(OpenShift Do) odo is a CLI tool for running OpenShift applications in a fast and automated manner.
Reducing the complexity of deployment, odo adds iterative development without the worry of deploying your source code.

Find more information at https://github.com/openshift/odo

Usage:
  odo [flags]
  odo [command]

Examples:
  # Creating and deploying a Node.js project
  git clone https://github.com/openshift/nodejs-ex && cd nodejs-ex
  odo create nodejs
  odo push
  
  # Accessing your Node.js component
  odo url create

Shortcuts:
  create      Create a new component (shortcut for "component create") 
  delete      Delete component (shortcut for "component delete") 
  describe    Describe component (shortcut for "component describe") 
  link        Link component to a service or component (shortcut for "component link") 
  list        List all components in the current application (shortcut for "component list") 
  log         Retrieve the log for the given component (shortcut for "component log") 
  push        Push source code to a component (shortcut for "component push") 
  unlink      Unlink component to a service or component (shortcut for "component unlink") 
  update      Update the source code path of a component (shortcut for "component update") 
  watch       Watch for changes, update component on change (shortcut for "component watch") 

Commands:
  app         Perform application operations (delete, describe, list)
  catalog     Catalog related operations (describe, list, search)
  component   Manage components (create, delete, describe, link, list, log, push, unlink, update, watch)
  config      Change or view configuration (set, unset, view)
  debug       Debug commands (port-forward)
  preference  Modifies preference settings (set, unset, view)
  project     Perform project operations (create, delete, get, list, set)
  service     Perform service catalog operations (create, delete, list)
  storage     Perform storage operations (create, delete, list)
  url         Expose component to the outside world (create, delete, list)

Utility Commands:
  login       Login to cluster
  logout      Log out of the current OpenShift session
  utils       Utilities for terminal commands and modifying odo configurations (terminal)
  version     Print the client version information

Flags:
      --complete             Install completion for odo command
  -o, --o string             Specify output format, supported format: json (default "json")
      --uncomplete           Uninstall completion for odo command
  -v, --v Level              Log level for V logs. Level varies from 0 to 9 (default 0).
      --vmodule moduleSpec   Comma-separated list of pattern=N settings for file-filtered logging
  -y, --y                    Don't prompt user for typing 'yes' when installing completion

Use "odo [command] --help" for more information about a command.
Amits-MacBook-Pro:odo amit$ odo component -h
Manage components (create, delete, describe, link, list, log, push, unlink, update, watch)

Usage:
  odo component [flags]
  odo component [command]

Examples:
odo component
create

  See sub-commands individually for more examples

Available Commands:
  create      Create a new component
  delete      Delete component
  describe    Describe component
  link        Link component to a service or component
  list        List all components in the current application
  log         Retrieve the log for the given component
  push        Push source code to a component
  unlink      Unlink component to a service or component
  update      Update the source code path of a component
  watch       Watch for changes, update component on change

Flags:
      --app string       Application, defaults to active application
      --context string   Use given context directory as a source for component settings
  -h, --help             Help for component
      --project string   Project, defaults to active project
  -q, --short            If true, display only the component name

Global Flags:
  -o, --o string             Specify output format, supported format: json (default "json")
  -v, --v Level              Log level for V logs. Level varies from 0 to 9 (default 0).
      --vmodule moduleSpec   Comma-separated list of pattern=N settings for file-filtered logging

Use "odo component [command] --help" for more information about a command.
```
/approve

**Comment by kadel** [comment]
One small thing regarding help.

Would it be possible to reorder `Shortcuts`, `Commands`, `Utility Commands` sections to:

```
Commands:

Utility commands:

Component shortcuts:
```

`Commands` section is most important so it would be nice to have it first.


Changes in this PR look good.
@cdrage if you want to change the order in a different PR, or if you think that the order is not that important feel free to do `/hold cancel`

/lgtm
/hold

**Comment by cdrage** [comment]
@kadel Updated the order! See below:

```sh
Commands:
  app         Perform application operations (delete, describe, list)
  catalog     Catalog related operations (describe, list, search)
  component   Manage components (create, delete, describe, link, list, log, push, unlink, update, watch)
  config      Change or view configuration (set, unset, view)
  debug       Debug commands (port-forward)
  preference  Modifies preference settings (set, unset, view)
  project     Perform project operations (create, delete, get, list, set)
  service     Perform service catalog operations (create, delete, list)
  storage     Perform storage operations (create, delete, list)
  url         Expose component to the outside world (create, delete, list)

Utility Commands:
  login       Login to cluster
  logout      Log out of the current OpenShift session
  utils       Utilities for terminal commands and modifying odo configurations (terminal)
  version     Print the client version information

Component Shortcuts:
  create      Create a new component (shortcut for "component create")
  delete      Delete component (shortcut for "component delete")
  describe    Describe component (shortcut for "component describe")
  link        Link component to a service or component (shortcut for "component link")
  list        List all components in the current application (shortcut for "component list")
  log         Retrieve the log for the given component (shortcut for "component log")
  push        Push source code to a component (shortcut for "component push")
  unlink      Unlink component to a service or component (shortcut for "component unlink")
  update      Update the source code path of a component (shortcut for "component update")
  watch       Watch for changes, update component on change (shortcut for "component watch")
```

/hold cancel

**Pull request merged**
