### PR TITLE
Run json format test in parallel

### PR DESCRIPTION
**Pull request by amitkrout**
## What is the purpose of this change? What does it change?

To reduce test time both locally and on CI too.
## Was the change discussed in an issue?
fixes - part of #1473

## How to test changes?

make test-json-format-output

### CODE REVIEW

**Comment by amitkrout** [comment]
Wait till #1759 goes in first

/hold

**Comment by kadel** [comment]
> Wait till #1759 goes in first
> 
> /hold

#1759 is merged, does this still need to be on hold?

**Comment by amitkrout** [comment]
> > Wait till #1759 goes in first
> > /hold
> 
> #1759 is merged, does this still need to be on hold?

/hold cancel

**Pull request merged**
