### PR TITLE
Move file sync to its own package

### PR DESCRIPTION
**Pull request by johnmcollier**
Signed-off-by: John Collier <John.J.Collier@ibm.com>

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:

/kind feature
/kind code-refactoring

**What does does this PR do / why we need it**:
In order to implement file syncing for devfile components, we need to make the file sync functions that exist in occlient, available to kclient. The file sync functionality only needs a very small modification to work with devfile components (adding the option to specify a container name in `ExecCmdInContainer`). As such, we'd likely be duplicating a lot of code if we had the sync code in both occlient **and** kclient. 

So, this PR moves the file sync functionality from `occlient` into its own package, `sync`. I then created an interface (`SyncClient`) that both `occlient` and `kclient` implement, allowing the sync function to be called from both "legacy" odo (with `occlient`) and the "devfile" parts of odo (with `kclient`)

This PR does the following:
- Creates an interface, `SyncClient`, with one function: `ExecCMDInContainer` that both `occlient` and `kclient implement
- Moves `CopyFile()` (and the functions it depends on) from the `occlient` package to sync.go in the `sync` package.
    - Updates `odo push` and `odo watch` so that they call this function for file syncing
- Modifies `occlient`'s ExecCMDInContainer function to take in a container name as a parameter (required to implement `SyncClient`).
    - If a blank/no container name is passed in, it defaults to the first container.

**Which issue(s) this PR fixes**:
https://github.com/openshift/odo/issues/2473 (partially)

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by johnmcollier** [comment]
The tests appear to be failing with the following RBAC errors from the OpenShift CI:
```
 [odo] E0224 18:55:57.750852   12628 glog.go:119] err: error while streaming command: pods "backend-app-1-ch87l" is forbidden: User "developer" cannot create resource "pods/exec" in API group "" in the namespace "vxgcyuwihe"
[odo]  ✗  Syncing files to the component [340ms]
[odo]  ✗  pods "backend-app-1-ch87l" is forbidden: User "developer" cannot create resource "pods/exec" in API group "" in the namespace "vxgcyuwihe"
```

**Comment by johnmcollier** [comment]
Fixed the above issue, it was occurring when `odo push` was called and the current Kube namespace differs from the namespace/project specified in the config.yaml.

**Comment by johnmcollier** [comment]
Updating the PR title to reflect changes:
- Moved file sync into its own package, `sync`, which has an interface `SyncClient` that both kclient and occlient implement.
- No longer adding `kclient` to the CLI context with "legacy" odo components
    - We can always do this later, but for now it's not needed and makes for a riskier code change

The alternative to this PR is https://github.com/openshift/odo/pull/2643

**Comment by johnmcollier** [comment]
@kanchwala-yusuf Thanks! Agreed that this is the better approach. So I've closed https://github.com/openshift/odo/pull/2643

Regarding unit tests for the sync package, I had been thinking about it, but I couldn't find any existing tests for those file sync in the occlient package, and since CopyFile requires an already running pod, I didn't think it was something that could be easily unit-testable with the mock Kube-api. 

What are your thoughts?

**Comment by kadel** [comment]
I agree that those functions are important for odo functionality and they should be covered. But to be completely fair to @johnmcollier this PR just moves uncovered functions to a different package. It is not adding anything new. I'm not sure if it is fair to require unit tests for functions that were just moved. 
/approve

**Comment by johnmcollier** [comment]
@kadel I'll go open an issue so that we can get at least _some_ unittest coverage on the file sync functionality

**Comment by kanchwala-yusuf** [comment]
Looks good to me.
/lgtm

**Pull request merged**
