### PR TITLE
Development guide review and adoc conversion

### PR DESCRIPTION
**Pull request by Preeticp**
## What is the purpose of this change? What does it change?
This PR reviews, modifies and converts the Development guide from .md to .adoc

### CODE REVIEW

**Comment by Preeticp** [comment]
@cdrage @kadel please review and merge if you find it alright.

**Comment by Preeticp** [comment]
As per discussions with Robert (rkratky), to keep it consistent with documentation standards, `odo` willl be referenced as OpenShift Do in the headings and titles for all docs. In the current case retaining odo-bot as is as the bot is called odo-bot.

**Comment by cdrage** [comment]
@Preeticp Any way to not get the "note" sections in tables? I think instead it should be bolded like so:


**Note:** blah blah blah

**Comment by Preeticp** [comment]
@cdrage the syntax to be used as per doc conventions and Asciidoc syntax is 'NOTE:' 
As for rendering we should try to render it as the OC docs do it, so that it is consistent. I will discuss it with @rkratky and see if we can tweak the css to render it without tables. For now the syntax used is correct and I would suggest we let it be as is.

**Pull request merged**
