### PR TITLE
Added v4 log level to project creation

### LINKED ISSUE #1707: odo project create stuck inconsistently
[kind/bug]

## What versions of software are you using?
- Operating System: macOS
- Output of `odo version`: master

## How did you run odo exactly?
```
$odo login -u <username> -p <password>
$ odo project create test1 -w
 ◐  Waiting for project to come up
```
## Actual behavior
```
$odo login -u <username> -p <password>
✓  Login successful.

You have access to the following projects and can switch between them with 'odo project <project-name>':

  * default
    kube-public
    kube-system
    myproject
[...]

$ odo project create test1 -w
 ◐  Waiting for project to come up
```
## Expected behavior
Should not stuck

### PR DESCRIPTION
**Pull request by surajnarwade**
## Was the change discussed in an issue?
fixes #1707

### CODE REVIEW

**Comment by amitkrout** [comment]
Only for debug purpose. So
/hold

**Comment by surajnarwade** [comment]
```
Creating a new project: dxdhpvjiul
Running odo with args: [project create dxdhpvjiul -w -v4] 
[odo] I0521 09:57:08.440362   11595 preference.go:116] The configFile is /tmp/artifacts/.odo/config.yaml
[odo] I0521 09:57:08.440473   11595 occlient.go:452] Trying to connect to server api.ci-op-hlg0lc31-eed38.origin-ci-int-aws.dev.rhcloud.com:6443
[odo] I0521 09:57:09.440795   11595 occlient.go:455] unable to connect to server: dial tcp: i/o timeout
[odo] I0521 09:57:09.440876   11595 cmdutils.go:26] Error:
[odo] Unable to connect to OpenShift cluster, is it down?
[odo]  ✗  Unable to connect to OpenShift cluster, is it down?
Deleting project: 
Running odo with args: [project delete  -f] 
[odo]  ✗  Unable to connect to OpenShift cluster, is it down?
```

/retest

**Comment by amitkrout** [comment]
To reproduce the flake
/retest

**Comment by amitkrout** [comment]
@surajnarwade Same project creation issue #1707 can be observed in CI  (travis and prow) failure log

**Comment by cdrage** [comment]
Why /hold cancel @amitkrout  thought this was only for diagnosing #1707

**Comment by amitkrout** [comment]
> Why /hold cancel @amitkrout thought this was only for diagnosing #1707

@cdrage It really takes a long time to reproduce this, i mean repeated restart of job is required even this also not ensure the the issue will be hit. So rather spending time on reproducing this i thought merge of this issue helps @surajnarwade to debug if any incoming new pr finds the same issue.

@surajnarwade Can you please add proper description in the pr description area ?

**Pull request merged**
