### PR TITLE
Release v1.0.0-beta2

### PR DESCRIPTION
**Pull request by girishramnani**
## What is the purpose of this change? What does it change?

Releasing the v1.0.0-beta2 version of odo
## Was the change discussed in an issue?
fixes #???

### Enhancements
- Resolved odoignore not working in windows (https://github.com/openshift/odo/pull/1711)
- Hidden the `component get` command (https://github.com/openshift/odo/pull/1734)
- New workflow for odo storage (https://github.com/openshift/odo/pull/1547)
- Fixed multiple deployments for local component (https://github.com/openshift/odo/pull/1684)
- Fixed odo login not working properly for insecure https connections (https://github.com/openshift/odo/pull/1652)
- Added --all flag for `odo component delete` to allow removal of both config and component in one command (https://github.com/openshift/odo/pull/1731)
- Added show flag for `odo watch` (https://github.com/openshift/odo/pull/1659)
- `odo catalog list` now doesn't require a `.odo/config.yaml` to be present in the working directory (https://github.com/openshift/odo/pull/1714)
- `odo project delete` now doesn't break after consecutive runs (https://github.com/openshift/odo/pull/1710)

### Testing
- Better organisation of the tests by following ginkgo standards (https://github.com/openshift/odo/pull/1612)
- Used Gomega watcher for json tests (https://github.com/openshift/odo/pull/1625)

### Internal
- Fixed invalid paths using rsync on windows (https://github.com/openshift/odo/pull/1705)
- Used a more robust `project.Exists` to reduce flaky tests (https://github.com/openshift/odo/pull/1719)

### Documentation
- Modified README for formatting and clear installation instructions based on OS (https://github.com/openshift/odo/pull/1735)
- Fixed typos in the documentation (https://github.com/openshift/odo/pull/1666)
- Migrated to `.adoc` from `.md` for documentations (https://github.com/openshift/odo/pull/1645)

### CODE REVIEW

**Comment by surajnarwade** [comment]
extension of `cli reference` file should be `adoc`

**Comment by girishramnani** [comment]
@surajnarwade resolved it

**Comment by mohammedzee1000** [comment]
draft release notes in the description, please

**Comment by girishramnani** [comment]
@mohammedzee1000 added release notes

**Comment by mohammedzee1000** [comment]
Looks ok, but Maybe a bit more description
See previous release notes https://github.com/openshift/odo/releases

**Pull request merged**
