### PR TITLE
Adding sleep to project test flake

### PR DESCRIPTION
**Pull request by amitkrout**
**What kind of PR is this?**

/kind flake

**What does does this PR do / why we need it**:
https://github.com/openshift/odo/pull/2356#issuecomment-549794079

**How to test changes / Special notes to the reviewer**:
CI should not throw project list flake

### CODE REVIEW

**Comment by amitkrout** [comment]
@girishramnani AFAIU pr #2362 is a test blocker for now. Even after fixing it there is a high chance of getting ```project list``` flake in CI. I would recommend please add this single line change to your pr and close this pr.

**Comment by girishramnani** [comment]
Travis still seems to be failing @amitkrout

**Comment by girishramnani** [comment]
added the changes @amitkrout https://github.com/openshift/odo/pull/2362. lets wait to confirm that this PR only fails on 4.3 intg

**Comment by kadel** [comment]
/test v4.3-e2e-scenarios

```
level=fatal msg="failed to fetch Cluster: failed to generate asset \"Cluster\": failed to create cluster: failed to apply using Terraform"
```


v4.3-integration failed due to https://github.com/openshift/odo/issues/2357

**Comment by kadel** [comment]
/override v4.3-integration
 4.3 specific issue will be solved in #2357

**Pull request merged**
