### PR TITLE
Update Storage Type

### LINKED ISSUE #2527: odo storage list -o json strange output
/kind bug

## What versions of software are you using?

**Operating System:**
Win10Pro

**Output of `odo version`:**
```
odo v1.0.3 (HEAD)

Server: https://172.18.1.78:8443
Kubernetes: v1.11.0+d4cacc0
```
## How did you run odo exactly?
`odo storage list -o json`

## Actual behavior

Output:

```
{                                                         
    "kind": "List",                                       
    "apiVersion": "odo.openshift.io/v1alpha1",            
    "metadata": {},                                       
    "items": [                                            
        {                                                 
            "kind": "storage",                            
            "apiVersion": "odo.openshift.io/v1alpha1",    
            "metadata": {                                 
                "name": "stor1",                          
                "creationTimestamp": null                 
            },                                            
            "spec": {                                     
                "size": "1Gi"                             
            },                                            
            "status": {                                   
                "path": "/mnt1"                           
            }                                             
        }                                                 
    ]                                                     
}
```

## Expected behavior

I would expect:

- `path` to be part of the `spec` element
- `status` element should contain `state` for the storage (pushed, not pushed) like what's done for the URL

### PR DESCRIPTION
**Pull request by adisky**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake
> /kind code-refactoring

**What does does this PR do / why we need it**:
Update storage structure 
`Status.Path moved to Spec.Path`
`State moved to Status`

**Which issue(s) this PR fixes**:

Fixes #2527 

**How to test changes / Special notes to the reviewer**:

```
$ odo storage list -o json // should list path under spec.
{                                                         
    "kind": "List",                                       
    "apiVersion": "odo.openshift.io/v1alpha1",            
    "metadata": {},                                       
    "items": [                                            
        {                                                 
            "kind": "storage",                            
            "apiVersion": "odo.openshift.io/v1alpha1",    
            "metadata": {                                 
                "name": "stor1",                          
                "creationTimestamp": null                 
            },                                            
            "spec": {                                     
                "size": "1Gi"  
                "path": "/mnt1"                           
            },                                            
            "status": "Pushed"                                     
        }                                                 
    ]                                                     
}

```

### CODE REVIEW

**Comment by girishramnani** [comment]
as this changes the json output we would need to make sure this PR is added in the release note.
/approve

**Comment by mik-dass** [comment]
please update the machine-output.md doc with the latest json output.

/hold

**Comment by adisky** [comment]
> please update the machine-output.md doc with the latest json output.
> 
> /hold

@mik-dass Done.

**Comment by mik-dass** [comment]
@adisky All the tests seem to be failing with a build error. Please have a look.

**Comment by adisky** [comment]
@mik-dass Thanks 
/hold cancel

**Pull request merged**
