### PR TITLE
Changes the route and ingress names to include the app name 

### PR DESCRIPTION
**Pull request by mik-dass**
**What type of PR is this?**

/kind bug
/kind cleanup
/kind code-refactoring

**What does this PR do / why we need it**:

It also refactors the URL package code.

**Which issue(s) this PR fixes**:

Fixes part of #4550 and #4402

**PR acceptance criteria**:

- [X] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [ ] Update changelog

- [ ] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

- Route and ingress names should include the app name for newly created components.
- Commands should work with old routes and ingresses.
- Tests should pass.

### CODE REVIEW

**Comment by mik-dass** [comment]
@feloy Fixed

**Comment by prietyc123** [comment]
PR has been rebased.

/lgtm

**Comment by mik-dass** [comment]
```
level=error msg=Cluster initialization failed because one or more operators are not functioning properly.
level=error msg=The cluster should be accessible for troubleshooting as detailed in the documentation linked below,
level=error msg=https://docs.openshift.com/container-platform/latest/support/troubleshooting/troubleshooting-installations.html
level=error msg=The 'wait-for install-complete' subcommand can then be used to continue the installation
level=fatal msg=failed to initialize the cluster: Working towards 4.7.0-0.ci.test-2021-06-15-083632-ci-op-xfsg4bfm-latest: 668 of 669 done (99% complete), waiting on monitoring
Setup phase finished, prepare env for next steps
Copying log bundle...
Removing REDACTED info from log...
Copying required artifacts to shared dir
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2021-06-15T09:55:00Z"}
error: failed to execute wrapped command: exit status 1
```
/retest

**Comment by mik-dass** [comment]
```
while waiting for deployment rollout: timeout while waiting for gxzbha-app deployment roll out
```
/retest

**Comment by mik-dass** [comment]
```
{"component":"entrypoint","file":"prow/entrypoint/run.go:165","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 4h0m0s timeout","severity":"error","time":"2021-06-16T12:37:43Z"}
INFO[2021-06-16T12:37:43Z] Received signal.                              signal=interrupt
INFO[2021-06-16T12:37:43Z] error: Process interrupted with signal interrupt, cancelling execution... 
INFO[2021-06-16T12:37:43Z] Step kubernetes-integration-e2e-kubernetes-integration-e2e-steps failed after 3h57m54s. 
INFO[2021-06-16T12:37:43Z] cleanup: Deleting pods with label ci.openshift.io/multi-stage-test=kubernetes-integration-e2e 
INFO[2021-06-16T12:38:13Z] Ran for 4h0m30s                              
ERRO[2021-06-16T12:38:13Z] Some steps failed:                           
ERRO[2021-06-16T12:38:13Z] 
```
/retest

**Pull request merged**
