### PR TITLE
Release v2.2.1

### PR DESCRIPTION
**Pull request by kadel**

### CODE REVIEW

**Review by mohammedzee1000 — APPROVED** [review]
Looks good to me. I guess we need to get better at changelogs (manual or automatic)
/lgtm

**Comment by mik-dass** [comment]
Shouldn't we update https://github.com/openshift/odo/blob/main/build/VERSION as well?

**Comment by mohammedzee1000** [comment]
> Shouldn't we update https://github.com/openshift/odo/blob/main/build/VERSION as well?

Not here, after the release is done.

**Comment by mohammedzee1000** [comment]
It will be the last step essentially

**Comment by mohammedzee1000** [comment]
Prow timeout
/retest

**Comment by mohammedzee1000** [comment]
Prow failure
/retest

**Pull request merged**
