### PR TITLE
update dependencies to OpenShift 4.9

### PR DESCRIPTION
**Pull request by kadel**
**What type of PR is this?**
/kind dependency-change

**What does this PR do / why we need it**:
update dependecies to OpenShift 4.9 and Kubernetes 1.22

### CODE REVIEW

**Comment by feloy** [comment]
/lgtm
/approve
All tests pass on IBM Pipeline: https://github.com/feloy/odo/pull/11

**Comment by feloy** [comment]
/hold
The execution of ginkgo fails on PSI:

```
[ssh:Fedora-32-minikube] GOFLAGS='-mod=vendor' go run -mod=vendor github.com/onsi/ginkgo/ginkgo  -randomizeAllSpecs -slowSpecThreshold=120 -timeout 14400s -nodes=4 tests/integration/operatorhub/
[ssh:Fedora-32-minikube] Failed to compile operatorhub:
[ssh:Fedora-32-minikube] 
[ssh:Fedora-32-minikube] # github.com/openshift/odo/tests/integration/operatorhub
[ssh:Fedora-32-minikube] package github.com/openshift/odo/tests/integration/operatorhub (test)
[ssh:Fedora-32-minikube] 	imports github.com/openshift/odo/tests/helper
[ssh:Fedora-32-minikube] 	imports github.com/openshift/odo/pkg/devfile
[ssh:Fedora-32-minikube] 	imports github.com/devfile/library/pkg/devfile
[ssh:Fedora-32-minikube] 	imports github.com/devfile/library/pkg/devfile/parser
[ssh:Fedora-32-minikube] 	imports k8s.io/client-go/tools/clientcmd
[ssh:Fedora-32-minikube] 	imports k8s.io/client-go/rest
[ssh:Fedora-32-minikube] 	imports k8s.io/client-go/plugin/pkg/client/auth/exec
[ssh:Fedora-32-minikube] 	imports io/fs: cannot find package "." in:
[ssh:Fedora-32-minikube] 	/home/fedora/amqp_ci_rcv_odo-minikube-pr-build_PR_5133/zJJAA/repo/vendor/io/fs
[ssh:Fedora-32-minikube] FAIL	github.com/openshift/odo/tests/integration/operatorhub [setup failed]
[ssh:Fedora-32-minikube] FAIL
```

**Comment by feloy** [comment]
@anandrkskd any clue on this?

**Comment by anandrkskd** [comment]
> @anandrkskd any clue on this?

Checking!

**Comment by valaparthvi** [comment]
@feloy can we remove the hold on this PR now? PSI tests are no longer failing.

**Comment by feloy** [comment]
> @feloy can we remove the hold on this PR now? PSI tests are no longer failing.

Removing it, thanks @anandrkskd @valaparthvi

**Pull request merged**
