### PR TITLE
Update s2i image for the library change on s390x plaftorm.

### PR DESCRIPTION
**Pull request by zhengxiaomei123**
**What type of PR is this?**
/kind bug
**What does does this PR do / why we need it**:
Make the same change with #3939 

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [ ] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by jichenjc** [comment]
lgtm

**Review by mohammedzee1000 — APPROVED** [review]
Looking good

/lgtm

**Review by amitkrout — COMMENTED** [review]
/approve

**Pull request merged**
