### PR TITLE
Make the file sync destination more consistent

### PR DESCRIPTION
**Pull request by johnmcollier**
Signed-off-by: John Collier <John.J.Collier@ibm.com>

**What type of PR is this?**
/kind cleanup

**What does does this PR do / why we need it**:
This PR implements the changes to the file sync destination as described in https://github.com/openshift/odo/pull/3630:

1) If `sourceMapping` is set, the source code will be mounted (and synced) to that folder (as-is today)

2) If `sourceMapping` is not set, and if the `PROJECTS_ROOT` env is set in a given container, the source code will be mounted and synced to that destination

3) Else, the source code will be synced to `/projects`

**Which issue(s) this PR fixes**:

Fixes https://github.com/openshift/odo/issues/3494

**PR acceptance criteria**:

- [x] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by adisky** [comment]
@johnmcollier Looks good to me, some devfiles needs update,
https://github.com/odo-devfiles/registry/blob/master/devfiles/java-springboot/devfile.yaml
https://github.com/odo-devfiles/registry/blob/master/devfiles/java-quarkus/devfile.yaml#L30
Link the PR, so that both PR's could be merged in parallel.

**Comment by dharmit** [comment]
> This PR implements the changes to the file sync destination as described in #3630:
> 
>   1. If `sourceMapping` is set, the source code will be mounted (and synced) to that folder (as-is today)
> 
>   2. If `sourceMapping` is not set, and if the `PROJECTS_ROOT` env is set in a given container, the source code will be mounted and synced to that destination
> 
>   3. Else, the source code will be synced to `/projects`

Above works for me along with this scenario I was wondering about https://github.com/openshift/odo/pull/3630#discussion_r460786946. 

/approve

**Pull request merged**
