### PR TITLE
devfile create Interation test on kubernetes cluster using travis CI

### LINKED ISSUE #2752: devfile integration tests should run against Kubernetes cluster
Everything related to devfiles should work with Kubernetes as well as OpenShift clusters.

Integration tests need to be executed against Kubernetes as well as OpenShift cluster

/area devfile
/kind test
/area testing
/priority high

### PR DESCRIPTION
**Pull request by prietyc123**
**What type of PR is this?**

/kind test

**What does does this PR do / why we need it**:

Runs the devfile create integration test on kubernetes cluster.

**Which issue(s) this PR fixes**:

Fixes #2752

**How to test changes / Special notes to the reviewer**:

The test should pass on travis with ```make test-cmd-devfile-create``` command.

### CODE REVIEW

**Comment by amitkrout** [comment]
Blocked due to - https://github.com/openshift/odo/issues/2888

**Comment by prietyc123** [comment]
Blocked with the ```odo create fakecomponent``` in devfile create integration test.
Logs:
```
Running odo with args [odo create fake-component]
[odo] Experimental mode is enabled, use at your own risk
[odo] 
[odo] Validation
[odo]  •  Checking Devfile compatibility  ...
[odo]  ✗  Checking Devfile compatibility [13703ns]
[odo] 
[odo] Please run 'odo catalog list components' for a list of supported devfile component types
[odo]  ✗  the server could not find the requested resource (get imagestreams.image.openshift.io fake-component)
Deleting project: hywllfifwd
Running kubectl with args [kubectl delete namespaces hywllfifwd]
[kubectl] namespace "hywllfifwd" deleted
Setting current dir to: /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile
Deleting dir: /tmp/392710421
• Failure [3.229 seconds]
odo devfile create command tests
/home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_create_test.go:13
  When executing odo create with an invalid devfile component
  /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_create_test.go:96
    should fail with please run 'odo catalog list components' [It]
    /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_create_test.go:97
    Expected
        <string>:  ✗  the server could not find the requested resource (get imagestreams.image.openshift.io fake-component)
        
    to contain substring
        <string>: "fake-component" not found
```
Issue is being tracked in https://github.com/openshift/odo/issues/2888

**Comment by prietyc123** [comment]
Holding this pr as it has dependency on issue #2888 

/hold

**Comment by adisky** [comment]
@prietyc123  The error is changed now, you need to check for the error string i am returning.
https://github.com/openshift/odo/pull/3124/files#diff-58fe314b4e3f9120402717ab8c2b3049R475
```
• Failure [7.037 seconds]
odo devfile create command tests
/home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_create_test.go:15
  When executing odo create with an invalid devfile component
  /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_create_test.go:140
    should fail with please run 'odo catalog list components' [It]
    /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_create_test.go:141
    Expected
        <string>: I0511 12:35:05.182331   17071 preference.go:188] The path for preference file is /tmp/740193925/config.yaml
        I0511 12:35:05.182523   17071 util.go:396] path ./.odo/config.yaml doesn't exist, skipping it
        I0511 12:35:05.182531   17071 preference.go:188] The path for preference file is /tmp/740193925/config.yaml
        I0511 12:35:05.185502   17071 preference.go:188] The path for preference file is /tmp/740193925/config.yaml
        I0511 12:35:05.186032   17071 cert_rotation.go:137] Starting client certificate rotation controller
        I0511 12:35:06.284585   17071 util.go:396] path devfile.yaml doesn't exist, skipping it
        I0511 12:35:06.284612   17071 util.go:396] path devfile.yaml doesn't exist, skipping it
         ✗  component not found
        
    to contain substring
        <string>: "fake-component" not found
    /home/travis/gopath/src/github.com/openshift/odo/tests/helper/helper_generic.go:75
```

**Comment by amitkrout** [comment]
Travis error;
```
------------------------------
Created dir: /tmp/964965407
Running odo with args [odo preference set Experimental true]
[odo] Global preference was successfully updated
Creating a new project: zktkdksubk
Running kubectl with args [kubectl create namespace zktkdksubk]
[kubectl] namespace/zktkdksubk created
Running kubectl with args [kubectl config set-context /tmp/964965407/config --namespace zktkdksubk]
[kubectl] Context "/tmp/964965407/config" created.
Running kubectl with args [kubectl get namespaces]
[kubectl] NAME              STATUS        AGE
[kubectl] default           Active        4m23s
[kubectl] kube-node-lease   Active        4m26s
[kubectl] kube-public       Active        4m26s
[kubectl] kube-system       Active        4m26s
[kubectl] tkovuglhnt        Terminating   7s
[kubectl] zktkdksubk        Active        0s
Current working dir: /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile
Setting current dir to: /tmp/964965407
Running odo with args [odo preference set Experimental false -f]
[odo] Global preference was successfully updated
Running odo with args [odo create nodejs]
[odo] I0512 07:10:40.345599   17222 cert_rotation.go:137] Starting client certificate rotation controller
[odo]  ✗  component not found
Deleting project: zktkdksubk
Running kubectl with args [kubectl delete namespaces zktkdksubk]
[kubectl] namespace "zktkdksubk" deleted
Setting current dir to: /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile
Deleting dir: /tmp/964965407
• Failure [5.797 seconds]
odo devfile create command tests
/home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_create_test.go:15
  Enabling experimental preference should show a disclaimer
  /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_create_test.go:52
    checks that the experimental warning does *not* appear when Experimental is set to false for create [It]
    /home/travis/gopath/src/github.com/openshift/odo/tests/integration/devfile/cmd_devfile_create_test.go:63
    No future change is possible.  Bailing out early after 0.082s.
    Running odo with args [odo create nodejs]
    Expected
        <int>: 1
    to match exit code:
        <int>: 0
    /home/travis/gopath/src/github.com/openshift/odo/tests/helper/helper_run.go:34
------------------------------
```

**Comment by amitkrout** [comment]
travis test fails at
```
It("checks that the experimental warning does *not* appear when Experimental is set to false for create", func() {
			helper.CmdShouldPass("odo", "preference", "set", "Experimental", "false", "-f")
			helper.CopyExample(filepath.Join("source", "nodejs"), context)

			// Check that it will contain the experimental mode output
			experimentalOutputMsg := "Experimental mode is enabled, use at your own risk"
			Expect(helper.CmdShouldPass("odo", "create", "nodejs")).To(Not(ContainSubstring(experimentalOutputMsg)))
		})
```

**Comment by amitkrout** [comment]
> travis test fails at
> 
> ```
> It("checks that the experimental warning does *not* appear when Experimental is set to false for create", func() {
> 			helper.CmdShouldPass("odo", "preference", "set", "Experimental", "false", "-f")
> 			helper.CopyExample(filepath.Join("source", "nodejs"), context)
> 
> 			// Check that it will contain the experimental mode output
> 			experimentalOutputMsg := "Experimental mode is enabled, use at your own risk"
> 			Expect(helper.CmdShouldPass("odo", "create", "nodejs")).To(Not(ContainSubstring(experimentalOutputMsg)))
> 		})
> ```

@prietyc123 It fails because nodejs s2i image is not supported on kubernetes cluster. So it deserves a skip against kubernetes cluster. We just need to add another teardown steps to fix it. For example

```
Context("Enabling experimental preference should show a disclaimer", func() {
		JustBeforeEach(func() {
			if os.Getenv("KUBERNETES") == "true" {
				Skip("Skipping test because s2i image is not supported on Kubernetes cluster")
			}
		})
		It("checks that the experimental warning does *not* appear when Experimental is set to false for create", func() {
			helper.CmdShouldPass("odo", "preference", "set", "Experimental", "false", "-f")
			helper.CopyExample(filepath.Join("source", "nodejs"), context)

			// Check that it will contain the experimental mode output
			experimentalOutputMsg := "Experimental mode is enabled, use at your own risk"
			Expect(helper.CmdShouldPass("odo", "create", "nodejs")).To(Not(ContainSubstring(experimentalOutputMsg)))
		})
	})
```

**Comment by prietyc123** [comment]
> Holding this pr as it has dependency on issue #2888

#2888 is resolved. Removing hold

/hold cancel

**Comment by prietyc123** [comment]
Failure 4.4 : #2641 
https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/pr-logs/pull/openshift_odo/2884/pull-ci-openshift-odo-master-v4.4-integration-e2e/1089#1:build-log.txt%3A2405

/retest

**Pull request merged**
