### PR TITLE
Commenting project command test flake spec

### PR DESCRIPTION
**Pull request by amitkrout**
**What kind of PR is this?**

/kind flake

**What does does this PR do / why we need it**:

There is already an ongoing pr #2330 that @mik-dass is working on to fix this flake. For time being to avoid the pain of same flake in other pr i just commented out the test. 

**Which issue(s) this PR fixes**:

Fixes - None, For time being i just commented the test that causing the flake in most of the pr 

**How to test changes / Special notes to the reviewer**:
CI should pass without throwing the same flake

### CODE REVIEW

**Comment by kadel** [comment]
Do we know when this started failing and what changes introduced it?

**Comment by amitkrout** [comment]
> Do we know when this started failing and what changes introduced it?

@kadel The flake was introduced after pr #2221. cc_ @mik-dass

**Comment by kadel** [comment]
> > Do we know when this started failing and what changes introduced it?
> 
> @kadel The flake was introduced after pr #2221. cc_ @mik-dass

So it is there for exactly one month? Why do you want to comment it now?

**Comment by amitkrout** [comment]
> > > Do we know when this started failing and what changes introduced it?
> > 
> > 
> > @kadel The flake was introduced after pr #2221. cc_ @mik-dass
> 
> So it is there for exactly one month? Why do you want to comment it now?

Because the appearance of the flake is more frequent. Moreover @mik-dass has WIP pr #2330 to fix this and we don't know when it will be fixed as per the last triage call.

**Comment by girishramnani** [comment]
This PR also has the https://github.com/openshift/odo/issues/2357 4.3 intg failures @amitkrout

**Comment by girishramnani** [comment]
@amitkrout the error seems different this time
```
[odo] unable to create new project: unable to create new project mwjiohfdco: projectrequests.project.openshift.io is forbidden: User "system:serviceaccount:ci-op-xb0s2vyf:default" cannot create projectrequests.project.openshift.io at the cluster scope: no RBAC policy matched
[odo]  ✗  projectrequests.project.openshift.io is forbidden: User "system:serviceaccount:ci-op-xb0s2vyf:default" cannot create projectrequests.project.openshift.io at the cluster scope: no RBAC policy matched
[odo]  ✗  Waiting for project to come up [2ms]```

**Comment by girishramnani** [comment]
@mik-dass's PR makes the project -w command wait till its active, this error seems to be related to not having enough permissions to create one

**Comment by mik-dass** [comment]
> Do we know when this started failing and what changes introduced it?

@amitkrout @kadel The error was introduced in #2099. It introduced a project test file and the since `project list` was failing back then also, the PR used sleep of 1 second. 

> @kadel The flake was introduced after pr #2221. cc_ @mik-dass

#2221 just tried to solve it, but couldn't completely. Maybe we should just introduce a sleep of 1 second as done in #2009 ?

**Comment by kadel** [comment]
> #2221 just tried to solve it, but couldn't eliminate it completely. Maybe we should just introduce a sleep of 1 second as done in #2009 ?

If we don't have a solution right now, adding `sleep` and keeping the test is a much better solution than just commenting it out.

**Comment by amitkrout** [comment]
> > #2221 just tried to solve it, but couldn't eliminate it completely. Maybe we should just introduce a sleep of 1 second as done in #2009 ?
> 
> If we don't have a solution right now, adding `sleep` and keeping the test is a much better solution than just commenting it out.

Ok, then i will add a sleep of 1 sec as it was before. @mik-dass make sure that you will remove the sleep in your fix.

**Pull request closed without merging**
