### PR TITLE
Bump release version 1.0.2 -> 1.0.3

### PR DESCRIPTION
**Pull request by mohammedzee1000**
Preparing to release v1.0.3
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake
> /kind code-refactoring

Signed-off-by: Mohammed Zeeshan Ahmed <mohammed.zee1000@gmail.com>

### CODE REVIEW

**Comment by mohammedzee1000** [comment]
> Don't we need to change the version info in `build/VERSION` file?
> 
we do it after the release.
> And what about changing image reference in `pkg/occlient/occlient.go` in the variable `defaultBootstrapperImage`? Do we do that after updating the init image?
Already updated

**Comment by kadel** [comment]
> Don't we need to change the version info in `build/VERSION` file?

That should be done only after release. This file is used by update notifier and we don't want for users to be notified about the new version before it is available to download.



> 
> And what about changing image reference in `pkg/occlient/occlient.go` in the variable `defaultBootstrapperImage`? Do we do that after updating the init image?

that was already updated. image has its own versioning and it doesn't have to be updated with each release

**Comment by dharmit** [comment]
Thanks for the answers @mohammedzee1000 @kadel 

/lgtm

**Pull request merged**
