### PR TITLE
Remove devfile integration test dependency on git clone

### PR DESCRIPTION
**Pull request by maysunfaisal**
**What type of PR is this?**
/kind cleanup
/kind flake

**What does does this PR do / why we need it**:
- Removes external dependency on git clone for integration tests, PR now has sample project in the examples dir, and copies it for performing the integration test
- update .gitignore to list DS_Store

**Which issue(s) this PR fixes**:

#3020

**How to test changes / Special notes to the reviewer**:
make <any of the devfile test>

### CODE REVIEW

**Comment by maysunfaisal** [comment]
@cdrage can you pls add the approved label as well? thx

**Comment by cdrage** [comment]
Will need another maintainer review, ping @openshift/odo-maintainers-1

**Comment by mik-dass** [comment]
> Will need another maintainer review, ping @girishramnani @kadel @dharmit @mik-dass

I don't have the approval rights. Sorry.

**Comment by maysunfaisal** [comment]
@cdrage could you pls rer-eview/re-add `lgtm` label?

**Pull request merged**
