### PR TITLE
Set 4 nodes for ginkgo tests

### PR DESCRIPTION
**Pull request by feloy**
**What type of PR is this?**

Run the parallel ginkgo tests on 4 nodes (instead of 2 previously).

The non-parallel tests are still running on a single node.

### CODE REVIEW

**Comment by dharmit** [comment]
Cause of v4.7 integration e2e failure:
```
 [odo] All settings correct for using Composer
[odo] Downloading...
[odo] Failed to decode zlib stream
[odo] error: build error: error building at STEP "RUN /usr/libexec/s2i/assemble": error while running runtime: exit status 1
[odo] I0616 07:21:03.655837   18439 buildConfigs.go:139] Status of testcmp-testing-1 build is Running
[odo] I0616 07:21:03.656243   18439 buildConfigs.go:139] Status of testcmp-testing-1 build is Failed
[odo]  ✗  Waiting for build to finish [3m]
[odo]  ✗  Failed to create component with name testcmp. Please use `odo config view` to view settings used to create component. Error: failed to build component with args {Name:testcmp SourcePath:https://github.com/appuio/example-php-sti-helloworld SourceRef:master SourceType:git ImageName:php EnvVars:[DEBUG_PORT=5858] Ports:[8443/TCP 8080/TCP] Resources:&ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},} ApplicationName:testing Wait:true StorageToBeMounted:map[] StdOut:0xc000010018}: unable to build testcmp-testing-1, error: : build testcmp-testing-1 status Failed
Deleting project: generic-test170dzj
Running odo with args [odo project delete generic-test170dzj -f] 
```
I'm facing the same error locally without this change. Haven't yet dug into what could have caused it.

/test v4.7-integration-e2e

**Comment by prietyc123** [comment]
Lets observe this change for 1-2 days and see how parallel runs behave 🙂 

/test v4.7-integration-e2e

**Comment by feloy** [comment]
ci/prow/v4.7-integration-e2e: 183/183 tests passed! after 1h49m7s

ci/prow/psi-kubernetes-integration-e2e: Test passed after 2h38m0s

**Comment by dharmit** [comment]
@prietyc123 I'm inclined to move ahead with this. Are there any concerns from CI point of view that you are still concerned of before we go ahead? If not, can you LGTM this PR?

/approve

**Review by mohammedzee1000 — APPROVED** [review]
Looks good to me
/lgtm

**Pull request merged**
