### PR TITLE
Fix JSON output context path on windows platform

### LINKED ISSUE #2127: Desired json output reported invalid format on win10 platform
[kind/bug]

## What versions of software are you using?
- Operating System: Win10
- Output of `odo version`: master

## How did you run odo exactly?
```
odo component command tests Creating component
 create component twice fails from same directory
 C:/Users/User/go/src/github.com/openshift/odo/tests/integration/component.go:94
Created dir: C:\Users\User\AppData\Local\Temp\283954347
Creating a new project: wqftposkme
Running odo.exe with args [odo project create wqftposkme -w -v4]
[odo]  -  Waiting for project to come up  ...
V  Waiting for project to come up [645ms]
[odo]  V  Project 'wqftposkme' is ready for use
[odo]  V  New project created and now using project : wqftposkme
[odo] I0915 23:28:41.623211    2896 odo.go:70] Could not get the latest release information in time. Never mind, exiting gracefully :slightly_smiling_face:
Current working dir: C:\Users\User\go\src\github.com\openshift\odo\tests\integration
Setting current dir to: C:\Users\User\AppData\Local\Temp\283954347
Running odo.exe with args [odo create nodejs nodejs --project wqftposkme]
V  Validating component [671ms]
[odo] Please use odo push command to create the component with source deployed



Running odo.exe with args [odo list -o json --path C:\Users\User\AppData\Local\Temp\283954347]
[odo] {"kind":"List","apiVersion":"odo.openshift.io/v1alpha1","metadata":{},"items":
[{"kind":"Component","apiVersion":"odo.openshift.io/v1alpha1","metadata":
{"name":"nodejs","namespace":"wqftposkme","creationTimestamp":null},"spec":
{"app":"app","type":"nodejs","source":"./","ports":["8080/TCP"]},"status":{"context":"C:\\Users\\User
\\AppData\\Local\\Temp\\283954347","state":"Not Pushed"}}]}



Deleting project: wqftposkme
Running odo.exe with args [odo project delete wqftposkme -f]
V  Deleting project wqftposkme [6s]
[odo]  V  Deleted project : wqftposkme
Setting current dir to: C:\Users\User\go\src\github.com\openshift\odo\tests\integration
Deleting dir: C:\Users\User\AppData\Local\Temp\283954347+ Failure [14.737 seconds]
odo component command tests
C:/Users/User/go/src/github.com/openshift/odo/tests/integration/cmd_cmp_test.go:13
 Creating component
 C:/Users/User/go/src/github.com/openshift/odo/tests/integration/component.go:40
   create component twice fails from same directory [It]
   C:/Users/User/go/src/github.com/openshift/odo/tests/integration/component.go:94    



Actual '{"kind":"List","apiVersion":"odo.openshift.io/v1alpha1","metadata":{},"items":
[{"kind":"Component","apiVersion":"odo.openshift.io/v1alpha1","metadata":
{"name":"nodejs","namespace":"wqftposkme","creationTimestamp":null},"spec":
{"app":"app","type":"nodejs","source":"./","ports":["8080/TCP"]},"status":{"context":"C:\Users
\User\AppData\Local\Temp\283954347","state":"Not Pushed"}}]}' should be valid JSON, but it is not.
Underlying error:invalid character 'U' in string escape code    C:/Users/User/go/src/github.com/openshift/odo/tests/integration/component.go:98
```

## Actual behavior
Invalid json format

## Expected behavior
Should be a valid json

### PR DESCRIPTION
**Pull request by amitkrout**
## Was the change discussed in an issue?
fixes #2127 

## How to test changes?

Run ```make test-cmd-cmp``` on windows platform

### CODE REVIEW

**Comment by amitkrout** [comment]
#2088 
/test v4.1-integration

**Comment by girishramnani** [comment]
Looks good @amitkrout . Will approve but just one doubt. Can the escaping be done in the code instead of tests? Or am I think of this incorrectly.
/approve

**Comment by amitkrout** [comment]
> Looks good @amitkrout . Will approve but just one doubt. Can the escaping be done in the code instead of tests? Or am I think of this incorrectly.
> /approve

@girishramnani it would be a smart solution if we fix it in odo code but not sure if it complicates the existing implementation. @kadel WDYT?

**Comment by amitkrout** [comment]
#1981 
/test v4.1-integration

**Pull request merged**
