### PR TITLE
increase timeout on odo log -f in tests to resolve a flake

### PR DESCRIPTION
**Pull request by girishramnani**
**What type of PR is this?**
> Uncomment only one ` /kind` line, and delete the rest.
> For example, `> /kind bug` would simply become: `/kind bug`

> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
 /kind failing-test
> /kind feature
> /kind flake
> /kind code-refactoring
>
> Documentation changes: Please include [skip ci] in your commit message as well
> /kind documentation
> [skip ci]

**What does does this PR do / why we need it**:
see $SUBJECT

**Which issue(s) this PR fixes**:

Fixes https://github.com/openshift/odo/issues/3610

**PR acceptance criteria**:

- [ ] Unit test 

- [X] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer**:
failing test should pass in multiple runs

### CODE REVIEW

**Comment by adisky** [comment]
@girishramnani @amitkrout I am bit skeptical about the failure reason, it is more related to string we are checking
https://github.com/openshift/odo/blob/6c507ec98f9e054b8c2db0ecb43980469d953001/tests/integration/devfile/cmd_devfile_log_test.go#L87

If it is immediately run after `odo push`, output log is `time="2020-07-22T05:38:00Z" level=debug msg="wait program exit" program=devrun `, if the app has started log is `App started on PORT 3000`.

**Comment by adisky** [comment]
possibly we could check `odo log -f` output to not contain empty string?

**Comment by girishramnani** [comment]
yeah sure - adding /hold

**Comment by amitkrout** [comment]
```helper.CmdShouldPass("odo", "push", "--project", namespace)``` waits till the command executed successfully. AFAIU ```helper.CmdShouldPass("odo", "log")``` will fetch the log of executed push command output and assert with a substring. 

@adisky I want to understand what output will be streamed through ```odo log -f```, nothing right ? because we started following the log just after push is finished. 

TBH increasing or decreasing the time out won't work to fix the flake. This need a proper programming like we did for watch command test. For example

https://github.com/openshift/odo/blob/master/tests/helper/helper_generic.go#L108

@girishramnani As a clean up you can remove the step ```odo log -f``` and fix it in a separate pr or you can fix it here aswell.

**Comment by adisky** [comment]
> For

@amitkrout we are running `odo log -f` with tail lines 1, so it would surely log something.
https://github.com/openshift/odo/blob/55cc0bd005b5d83eaa4f62773f6750dbe28e73d0/pkg/kclient/pods.go#L185
problem here is the assertion sub string. 

IMO it does not required fix as done for `odo watch`, as we complete odo push it triggers the run command and odo log -f would surely log something,  only updating the string assertion to not contain a empty string should work.

**Comment by amitkrout** [comment]
Copy pasting from the failure log
```
Running odo with args [odo log]
[odo] I0721 07:11:30.538768    6925 preference.go:196] The path for preference file is /tmp/187530165/config.yaml
[odo] I0721 07:11:30.539265    6925 preference.go:196] The path for preference file is /tmp/187530165/config.yaml
[odo] I0721 07:11:30.964129    6925 preference.go:196] The path for preference file is /tmp/187530165/config.yaml
[odo] I0721 07:11:30.964337    6925 context.go:58] absolute devfile path: '/tmp/187530165/projectDir/devfile.yaml'
[...]
[odo] 
[odo] > nodejs-starter@1.0.0 start /projects/nodejs-starter
[odo] > node server.js
[odo] 
[odo] App started on PORT 3000
[odo] time="2020-07-21T07:11:29Z" level=debug msg="wait program exit" program=devrun 
[odo] I0721 07:11:31.261078    6925 odo.go:72] Could not get the latest release information in time. Never mind, exiting gracefully :)
```
```
Running odo with args [odo log -f]
[odo] I0721 07:11:31.820487    6939 preference.go:196] The path for preference file is /tmp/187530165/config.yaml
[odo] I0721 07:11:31.820763    6939 preference.go:196] The path for preference file is /tmp/187530165/config.yaml 
```
> @amitkrout we are running odo log -f with tail lines 1, so it would surely log something.

@adisky Got it. ```-f``` flag is capturing something but it does not capture the last line where as ```odo log``` executed successfully just before it. Anything went wrong here ?

**Comment by adisky** [comment]
> Copy pasting from the failure log
> 
> ```
> Running odo with args [odo log]
> [odo] I0721 07:11:30.538768    6925 preference.go:196] The path for preference file is /tmp/187530165/config.yaml
> [odo] I0721 07:11:30.539265    6925 preference.go:196] The path for preference file is /tmp/187530165/config.yaml
> [odo] I0721 07:11:30.964129    6925 preference.go:196] The path for preference file is /tmp/187530165/config.yaml
> [odo] I0721 07:11:30.964337    6925 context.go:58] absolute devfile path: '/tmp/187530165/projectDir/devfile.yaml'
> [...]
> [odo] 
> [odo] > nodejs-starter@1.0.0 start /projects/nodejs-starter
> [odo] > node server.js
> [odo] 
> [odo] App started on PORT 3000
> [odo] time="2020-07-21T07:11:29Z" level=debug msg="wait program exit" program=devrun 
> [odo] I0721 07:11:31.261078    6925 odo.go:72] Could not get the latest release information in time. Never mind, exiting gracefully :)
> ```
> 
> ```
> Running odo with args [odo log -f]
> [odo] I0721 07:11:31.820487    6939 preference.go:196] The path for preference file is /tmp/187530165/config.yaml
> [odo] I0721 07:11:31.820763    6939 preference.go:196] The path for preference file is /tmp/187530165/config.yaml 
> ```
> 
> > @amitkrout we are running odo log -f with tail lines 1, so it would surely log something.
> 
> @adisky Got it. `-f` flag is capturing something but it does not capture the last line where as `odo log` executed successfully just before it. Anything went wrong here ?

nothing wrong here, `odo log -f`, stream logs live, `-f` here is for `follow`, so whatever log app is giving at that time it is streaming.

**Comment by amitkrout** [comment]
> > Copy pasting from the failure log
> > ```
> > Running odo with args [odo log]
> > [odo] I0721 07:11:30.538768    6925 preference.go:196] The path for preference file is /tmp/187530165/config.yaml
> > [odo] I0721 07:11:30.539265    6925 preference.go:196] The path for preference file is /tmp/187530165/config.yaml
> > [odo] I0721 07:11:30.964129    6925 preference.go:196] The path for preference file is /tmp/187530165/config.yaml
> > [odo] I0721 07:11:30.964337    6925 context.go:58] absolute devfile path: '/tmp/187530165/projectDir/devfile.yaml'
> > [...]
> > [odo] 
> > [odo] > nodejs-starter@1.0.0 start /projects/nodejs-starter
> > [odo] > node server.js
> > [odo] 
> > [odo] App started on PORT 3000
> > [odo] time="2020-07-21T07:11:29Z" level=debug msg="wait program exit" program=devrun 
> > [odo] I0721 07:11:31.261078    6925 odo.go:72] Could not get the latest release information in time. Never mind, exiting gracefully :)
> > ```
> > 
> > 
> > ```
> > Running odo with args [odo log -f]
> > [odo] I0721 07:11:31.820487    6939 preference.go:196] The path for preference file is /tmp/187530165/config.yaml
> > [odo] I0721 07:11:31.820763    6939 preference.go:196] The path for preference file is /tmp/187530165/config.yaml 
> > ```
> > 
> > 
> > > @amitkrout we are running odo log -f with tail lines 1, so it would surely log something.
> > 
> > 
> > @adisky Got it. `-f` flag is capturing something but it does not capture the last line where as `odo log` executed successfully just before it. Anything went wrong here ?
> 
> nothing wrong here, `odo log -f`, stream logs live, `-f` here is for `follow`, so whatever log app is giving at that time it is streaming.

hmmm, then its better to check that the output should not contain any empty string. I do not think we need to increase the sleep time.

**Comment by amitkrout** [comment]
> > > Copy pasting from the failure log
> > > ```
> > > Running odo with args [odo log]
> > > [odo] I0721 07:11:30.538768    6925 preference.go:196] The path for preference file is /tmp/187530165/config.yaml
> > > [odo] I0721 07:11:30.539265    6925 preference.go:196] The path for preference file is /tmp/187530165/config.yaml
> > > [odo] I0721 07:11:30.964129    6925 preference.go:196] The path for preference file is /tmp/187530165/config.yaml
> > > [odo] I0721 07:11:30.964337    6925 context.go:58] absolute devfile path: '/tmp/187530165/projectDir/devfile.yaml'
> > > [...]
> > > [odo] 
> > > [odo] > nodejs-starter@1.0.0 start /projects/nodejs-starter
> > > [odo] > node server.js
> > > [odo] 
> > > [odo] App started on PORT 3000
> > > [odo] time="2020-07-21T07:11:29Z" level=debug msg="wait program exit" program=devrun 
> > > [odo] I0721 07:11:31.261078    6925 odo.go:72] Could not get the latest release information in time. Never mind, exiting gracefully :)
> > > ```
> > > 
> > > 
> > > ```
> > > Running odo with args [odo log -f]
> > > [odo] I0721 07:11:31.820487    6939 preference.go:196] The path for preference file is /tmp/187530165/config.yaml
> > > [odo] I0721 07:11:31.820763    6939 preference.go:196] The path for preference file is /tmp/187530165/config.yaml 
> > > ```
> > > 
> > > 
> > > > @amitkrout we are running odo log -f with tail lines 1, so it would surely log something.
> > > 
> > > 
> > > @adisky Got it. `-f` flag is capturing something but it does not capture the last line where as `odo log` executed successfully just before it. Anything went wrong here ?
> > 
> > 
> > nothing wrong here, `odo log -f`, stream logs live, `-f` here is for `follow`, so whatever log app is giving at that time it is streaming.
> 
> hmmm, then its better to check that the output should not contain any empty string. I do not think we need to increase the sleep time.

@girishramnani We can use some thing like this - https://github.com/openshift/odo/pull/3619/files#diff-66f499c995fc950f403a939757588820R104.

**Comment by girishramnani** [comment]
sure, changing the PR as mentioned

**Comment by kadel** [comment]
> hmmm, then its better to check that the output should not contain any empty string. I do not think we need to increase the sleep time.

That alone wouldn't help. What if after the timeout the string is still empty? -> It would fail.


The correct approach is to execute the command, wait for the correct string if the correct strict is detected exit with success. If after a timeout, which can be in this case much longer (even 1min is fine) exit with failure

**Comment by girishramnani** [comment]
@adisky would work on this issue so closing this PR

**Pull request closed without merging**
