### PR TITLE
get imageStreamRef back to catalog component out list

### LINKED ISSUE #2707: 'odo catalog list components -o json' does not have `imageStreamRef` in json output after update from v1.0.x to v1.1.0
/kind bug
## How did you run odo exactly?
`odo catalog list components -o json`
imageStreamRef

## Actual behavior
`odo catalog list components -o json` for v1.0.x prints json with `imageStreamRef` attribute for every component. It is, I guess, copy of imageStream resource manifest.
`odo catalog list components -o json` for v1.1.0 does not have ``imageStreamRef` anymore. That is backward compatibility issue. VSCode OpenShift Connector extension is using that node metadata to detect component type to identify what debugger Java or Node.js to start. After upgrading odo from 1.0.0 to 1.1.0 it stopped working.

## Expected behavior
-o json output can have additional information included into json output for new releases, but should preserve json structures from previous releases.

## Any logs, error output, etc?
N/A

### PR DESCRIPTION
**Pull request by jichenjc**
**What type of PR is this?**

/kind bug
**What does does this PR do / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #2707 

**How to test changes **:
`odo catalog list components -o json` will have `imageStreamRef` included in its output

### CODE REVIEW

**Comment by kadel** [comment]
@jichenjc thank you for this quick fix.

/ok-to-test
/approve

**Comment by amitkrout** [comment]
@jichenjc Can you please clean up the ```What type of PR is this?``` section of the pr description area. Its really confusing to find out the pr type. 

Can you please remove all the label except the proper one. For example in this case you can keep ```/kind bug``` and remove rest label.

**Comment by jichenjc** [comment]
@amitkrout I updated just now ,let me know whether it's not ok to you, thanks

**Comment by amitkrout** [comment]
@jichenjc can you please update ```How to test changes / Special notes to the reviewer:``` field too

**Comment by jichenjc** [comment]
> @jichenjc can you please update `How to test changes / Special notes to the reviewer:` field too

done :)

**Comment by amitkrout** [comment]
> > @jichenjc can you please update `How to test changes / Special notes to the reviewer:` field too
> 
> done :)

The reference issue #2707 says something related to machine readable output. And even the code change does not refer what you mentioned above :). Can you please re visit it

**Comment by jichenjc** [comment]
> > > @jichenjc can you please update `How to test changes / Special notes to the reviewer:` field too
> > 
> > 
> > done :)
> 
> The reference issue #2707 says something related to machine readable output. And even the code change does not refer what you mentioned above :). Can you please re visit it

my bad, it's my Friday evening so I made a mistake ( thought this is another PR that I am working on ).. so updated just now, sorry for inconvenience.

**Comment by girishramnani** [comment]
we removed this for a reason and I would prefer to only provide the information needed by the adapter

**Comment by girishramnani** [comment]
I would suggest to discuss with @dgolovin to understand how they were using the `imageStreamRef` and only provide the fields that were necessary for detecting the debugger.

**Comment by kadel** [comment]
> we removed this for a reason and I would prefer to only provide the information needed by the adapter

What was the reason for removing it?
For reference, this is PR where it was removed https://github.com/openshift/odo/pull/2451

I don't see anything mentioning why it is getting removed from the output there.

**Comment by girishramnani** [comment]
It was never supposed to be in there actually. It was exposed by mistake and hence I was removing it

**Comment by girishramnani** [comment]
And the reason is very well documented here 
https://github.com/openshift/odo/pull/2451#issuecomment-564717580

**Comment by girishramnani** [comment]
>I remember adding `ImageStreamRef` for making it easy to co-relate a component and underlying imageStream. It wasn't supposed to show up in the machine readable output.
> But just in case, we can confirm that it's not being used by the vs code plugin @kadel

**Comment by girishramnani** [comment]
Closing this PR as we need to figure out a different way to resolve this issue

**Pull request closed without merging**
