### PR TITLE
Fix minikube tests if kubelet gets stopped

### PR DESCRIPTION
**Pull request by prietyc123**
**What type of PR is this?**

/kind failing-test

**What does this PR do / why we need it**:
Fix test failure if `kubelet` gets stopped somehow https://github.com/openshift/odo/pull/4661#issuecomment-864912787 
```
$ minikube status
minikube
type: Control Plane
host: Running
kubelet: Stopped
apiserver: Stopped
kubeconfig: Configured
```

**Which issue(s) this PR fixes**:

Fixes #?

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [ ] Update changelog

- [ ] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:
minikube should run test successfully.

### CODE REVIEW

**Comment by prietyc123** [comment]
Prow failure

/retest

**Review by mohammedzee1000 — APPROVED** [review]
looks good
/lgtm

**Comment by mohammedzee1000** [comment]
oops
/approve

**Pull request merged**
