### PR TITLE
Updates docs to use the new schema changes for commands and components

### LINKED ISSUE #3925: Update docs according to schema changes in the command and component struct
/kind documentation

## What mistake did you find / what is missing in the documentation?

Changes due to https://github.com/openshift/odo/pull/3872

### PR DESCRIPTION
**Pull request by mik-dass**
**What type of PR is this?**

/kind documentation

**What does does this PR do / why we need it**:

Updates docs to use the new schema changes for components and commands

**Which issue(s) this PR fixes**:

Fixes #3925

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [X] Documentation 

- [x] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

Check if all the docs are updated to the new schema.

### CODE REVIEW

**Review by adisky — COMMENTED** [review]
This also needs to be update https://github.com/openshift/odo/blob/b05cd786bbf4a3ed77f6b64ddeb6640d3f2734e8/docs/file-reference/index.md#starterproject-object

**Comment by adisky** [comment]
> This also needs to be updated https://github.com/openshift/odo/blob/b05cd786bbf4a3ed77f6b64ddeb6640d3f2734e8/docs/file-reference/index.md#starterproject-object

or we want a different issue for project schema update?

**Comment by mik-dass** [comment]
> or we want a different issue for project schema update?

Let's do that in a separate PR.

**Comment by cdrage** [comment]
Thank you!

/lgtm
/approve

**Pull request merged**
