### PR TITLE
cleanup for dead code, lints and imports

### PR DESCRIPTION
**Pull request by girishramnani**
**What type of PR is this?**

/kind cleanup
/kind code-refactoring

**What does does this PR do / why we need it**:
Cleaning up dead code, multiple imports of the same package and general linting like error formats.

**Which issue(s) this PR fixes**:

No issue

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [X] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:
Tests should pass and things should work correctly

### CODE REVIEW

**Comment by adisky** [comment]
mostly looks goods to me, tests needs to fixed as some error messages updated to use lower case
/lgtm

**Comment by mik-dass** [comment]
```
• Failure [16.780 seconds]
odo service command tests for OperatorHub
/go/src/github.com/openshift/odo/tests/integration/operatorhub/cmd_service_test.go:17
  When linking devfile component with Operator backed service
  /go/src/github.com/openshift/odo/tests/integration/operatorhub/cmd_service_test.go:365
    should fail if service name doesn't adhere to <service-type>/<service-name> format [It]
    /go/src/github.com/openshift/odo/tests/integration/operatorhub/cmd_service_test.go:384
    Expected
      
        <string>: I0924 20:56:04.572998   66826 util.go:708] HTTPGetRequest: https://raw.githubusercontent.com/openshift/odo/master/build/VERSION
        I0924 20:56:04.573152   66826 preference.go:209] The path for preference file is /tmp/artifacts/.odo/preference.yaml
        I0924 20:56:04.573264   66826 util.go:729] Response will be cached in /tmp/odohttpcache for 1h0m0s
        I0924 20:56:04.573397   66826 util.go:742] Cached response used.
         ✗  invalid service name. Must adhere to <service-type>/<service-name> formatting. For example: "EtcdCluster/example". Execute "odo service list" for list of services.
        
    to contain substring
        <string>: Invalid service name
```
Operator hub tests need to be updated.

**Comment by prietyc123** [comment]
> invalid service name

@girishramnani Its a real failure from operatorhub test script. It is not failing on travis because operatorhub run only on 4.* cluster.

**Comment by mik-dass** [comment]
Build is failing
```
+ make bin
go build -mod=vendor -ldflags="-X github.com/openshift/odo/pkg/version.GITCOMMIT=35a2abc" cmd/odo/odo.go
# github.com/openshift/odo/pkg/kclient
pkg/kclient/deployments.go:328:19: undefined: fields
make: *** [bin] Error 2
```
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_odo/4028/pull-ci-openshift-odo-master-v4.5-integration-e2e/1315926778979553280#1:build-log.txt%3A421

**Comment by girishramnani** [comment]
I am getting bored on managing this PR, so I am gonna open smaller PRs

**Comment by girishramnani** [comment]
this PR has become out of sync - will open smaller ones

**Pull request closed without merging**
