### PR TITLE
Fixing link test flake

### PR DESCRIPTION
**Pull request by amitkrout**
## What is the purpose of this change? What does it change?

Fixing of link test flake
## Was the change discussed in an issue?
No. But saw some test failure in CI due to this link test flake

## How to test changes?

make test-link-e2e

### CODE REVIEW

**Comment by amitkrout** [comment]
@surajnarwade ping

**Comment by surajnarwade** [comment]
https://github.com/openshift/odo/blob/master/tests/integration/generic_test.go#L61 is causing problem in generic test

**Comment by amitkrout** [comment]
```
odoCmpE2e Creating component 
  should list the component using --all flag
  /go/src/github.com/openshift/odo/tests/integration/component.go:97
 Created dir: /tmp/569491165
Creating a new project: hakcdrymho
Running odo with args: [project create hakcdrymho -w -v4] 
[odo] I0703 07:59:36.983836   21135 preference.go:116] The configFile is /tmp/569491165/config.yaml
[odo] I0703 07:59:36.983925   21135 occlient.go:455] Trying to connect to server api.ci-op-xk70f65r-f09f4.origin-ci-int-aws.dev.rhcloud.com:6443
[odo] I0703 07:59:37.006823   21135 occlient.go:462] Server https://api.ci-op-xk70f65r-f09f4.origin-ci-int-aws.dev.rhcloud.com:6443 is up
[odo] I0703 07:59:37.074388   21135 occlient.go:385] isLoggedIn err:  <nil> 
[odo]  output: "developer"
[odo] I0703 07:59:37.074439   21135 context.go:355] Ignoring error as it usually means flag wasn't set: flag accessed but not defined: context
[odo] I0703 07:59:37.074449   21135 context.go:355] Ignoring error as it usually means flag wasn't set: flag accessed but not defined: context
[odo] I0703 07:59:37.074526   21135 context.go:355] Ignoring error as it usually means flag wasn't set: flag accessed but not defined: app
[odo] I0703 07:59:37.074533   21135 context.go:355] Ignoring error as it usually means flag wasn't set: flag accessed but not defined: project
[odo] I0703 07:59:37.088714   21135 context.go:355] Ignoring error as it usually means flag wasn't set: flag accessed but not defined: app
[odo] I0703 07:59:37.088761   21135 context.go:355] Ignoring error as it usually means flag wasn't set: flag accessed but not defined: output
[odo] I0703 07:59:37.088766   21135 context.go:355] Ignoring error as it usually means flag wasn't set: flag accessed but not defined: component
[odo]  •  Waiting for project to come up  ...
[odo]  ✓  Waiting for project to come up [329ms]
[odo]  ✓  Project 'hakcdrymho' is ready for use
[odo] I0703 07:59:37.427533   21135 odo.go:70] Could not get the latest release information in time. Never mind, exiting gracefully :)
[odo]  ✓  New project created and now using project : hakcdrymho
Current working dir: /go/src/github.com/openshift/odo/tests/integration
Setting current dir to: /tmp/569491165
Running odo with args: [create nodejs cmp-git --project hakcdrymho --git https://github.com/openshift/nodejs-ex --min-memory 100Mi --max-memory 300Mi --min-cpu 0.1 --max-cpu 2 --context /tmp/569491165 --app testing] 
[odo]  •  Validating component  ...
[odo]  ✓  Validating component [323ms]
[odo] Please use `odo push` command to create the component with source deployed
Running odo with args: [push --context /tmp/569491165] 
[odo] Validation
[odo]  •  Validating component  ...
[odo]  ✓  Validating component [376ms]
[odo]  •  Checking component  ...
[odo]  ✓  Checking component [19ms]
[odo] 
[odo] Configuration changes
[odo]  •  Creating component  ...
[odo]  ✓  Initializing component
[odo]  •  Triggering build from git  ...
[odo]  ✓  Triggering build from git [77ms]
[odo]  •  Waiting for build to finish  ...
[odo]  ✗  Waiting for build to finish [30s]
[odo]  ✗  Failed to create component with name cmp-git. Please use `odo config view` to view settings used to create component. Error: unable to wait for build cmp-git-testing-1 to run: timed out waiting for the condition
[odo] unable get build log cmp-git-testing-1
```
Seems a flake to me 
/test integration

**Comment by amitkrout** [comment]
```
Running odo with args: [url list --context /tmp/032855663] 
[odo] Found the following URLs for component fxlzrh in application app:
[odo] NAME      IN CONFIG     URL                          PORT
[odo] itvan     Present       <not created on cluster>     8080
[odo] To create URLs on the OpenShift Cluster, please use `odo push` 
Running odo with args: [push --context /tmp/032855663] 
[odo] Validation
[odo]  •  Validating component  ...
[odo]  ✓  Validating component [485ms]
[odo]  •  Checking component  ...
[odo]  ✓  Checking component [260ms]
[odo] 
[odo] Configuration changes
[odo]  •  Applying configuration  ...
[odo]  •  Triggering build from git  ...
[odo]  ✓  Triggering build from git [70ms]
[odo]  •  Waiting for build to finish  ...
[odo]  ✓  Waiting for build to finish [2m]
[odo]  ✗  Failed To Update Config To Component Deployed
[odo]  ✗  Applying configuration [2m]
```
/test integration

**Pull request merged**
