### PR TITLE
Readme conversion from .md to .adoc 

### PR DESCRIPTION
**Pull request by Preeticp**
## What is the purpose of this change? What does it change?
This PR converts the Readme from markdown to asciidoc format.

### CODE REVIEW

**Comment by Preeticp** [comment]
@cdrage, @kadel we can merge this PR. I have added the final reviewed Readme in adoc format and deleted the markdown one. I will close the other PR as it had a merge conflict on a file I had deleted in my PR. I have checked the history and added the information from the 2 PRs raised last on the markdown to this asciidoc version.

**Comment by Preeticp** [comment]
@cdrage @kadel request you to merge thisin as early as possible to prevent anymore merge conflicts. I had to close #1551 for this very reason.

**Comment by kadel** [comment]
> /lgtm

if you are adding second review please use the other command :-)
in this case

/approve

**Pull request merged**
