### PR TITLE
Refactor Kubernetes storage utils for devfile/library migration

### PR DESCRIPTION
**Pull request by maysunfaisal**
Signed-off-by: Maysun J Faisal <maysunaneek@gmail.com>

**What type of PR is this?**
/kind cleanup
/kind code-refactoring

**What does this PR do / why we need it**:
The odo storage utils code for Kubernetes reads data from the devfile and returns a list of Kubernetes volumes and appends to the Kubernetes container's volume mounts

Ideally, this code should be extracted out and stored in devfile/library generator code like for the other Kubernetes objects - https://github.com/devfile/library/blob/master/pkg/devfile/generator/generators.go

Since other aspects of the storage code had been refactored, I was able to cleanup and refactor further for these util code. I have also removed the unnecessary docker code that were associated.

**Which issue(s) this PR fixes**:

Fixes #https://github.com/openshift/odo/issues/4397

**PR acceptance criteria**:

- [x] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [x] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:
All the integration and unit tests should pass.

I have also tested my copy of a devfile with two containers to ensure odo push is working as expected. If you're curious this is my test devfile for spring, which just mounts the same volume across different containers and also at different paths in the same container:

```yaml
commands:
- exec:
    commandLine: mvn clean -Dmaven.repo.local=/home/user/.m2/repository package -Dmaven.test.skip=true
    component: tools
    group:
      isDefault: true
      kind: build
  id: build
- exec:
    commandLine: mvn -Dmaven.repo.local=/home/user/.m2/repository spring-boot:run
    component: tools
    group:
      isDefault: true
      kind: run
  id: run
- exec:
    commandLine: java -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=${DEBUG_PORT},suspend=n -jar target/*.jar
    component: tools
    group:
      isDefault: true
      kind: debug
  id: debug
components:
- container:
    endpoints:
    - name: 8080-tcp
      targetPort: 8080
    - exposure: public
      name: myurl
      path: /
      protocol: http
      targetPort: 8080
    image: quay.io/eclipse/che-java11-maven:nightly
    memoryLimit: 768Mi
    mountSources: true
    volumeMounts:
    - name: m2
      path: /home/user/.m2
  name: tools
- container:
    args:
    - -f
    - /dev/null
    command:
    - tail
    image: maysunfaisal/springbootbuild
    volumeMounts:
    - name: m2
      path: /data2
    - name: m2
      path: /data22
    - name: m3
      path: /data3
  name: test
- name: m2
  volume:
    size: 3Gi
- name: m3
  volume: {}
metadata:
  name: java-springboot
  version: 1.1.0
schemaVersion: 2.0.0
starterProjects:
- git:
    remotes:
      origin: https://github.com/odo-devfiles/springboot-ex.git
  name: springbootproject
```

### CODE REVIEW

**Comment by dharmit** [comment]
Timeout
```
 INFO[2021-04-16T07:58:29Z] {"component":"entrypoint","error":"process timed out","file":"prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2021-04-16T07:58:19Z"} 
```
/test psi-kubernetes-integration-e2e

**Review by mik-dass — APPROVED** [review]
/lgtm

**Pull request merged**
