### PR TITLE
Fix Operatorhub test to use CreateNewContext()

### PR DESCRIPTION
**Pull request by anandrkskd**
**What type of PR is this?**

 /kind failing-test

**What does this PR do / why we need it**:
This PR fix Operatorhub test to uses CreateNewContext() in the test to compatible with windows.

**Which issue(s) this PR fixes**:

Fixes https://github.com/openshift/odo/issues/4680

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [ ] Update changelog

- [x] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:
`make test-operator-hub`

### CODE REVIEW

**Comment by rnapoles-rh** [comment]
@anandrkskd integration tests are failing with:
```
INFO[2021-05-14T07:33:05Z] [ssh:Fedora 32] verifying github.com/mikefarah/yaml/v2@v2.4.0/go.mod: checksum mismatch 
INFO[2021-05-14T07:33:05Z] [ssh:Fedora 32] 	downloaded: h1:RDklbk79AGWmwhnvt/jBztapEOGDOx6ZbXqjP6csGnQ= 
INFO[2021-05-14T07:33:05Z]                                              
INFO[2021-05-14T07:33:05Z] [ssh:Fedora 32] 	go.sum:     h1:ahVqZF4n1W4NqwvVnZzC4es67xsW9uR/RRf2RRxieJU= 
INFO[2021-05-14T07:33:05Z] [ssh:Fedora 32]                              
INFO[2021-05-14T07:33:05Z] [ssh:Fedora 32] SECURITY ERROR               
INFO[2021-05-14T07:33:05Z] [ssh:Fedora 32] This download does NOT match an earlier download recorded in go.sum. 
INFO[2021-05-14T07:33:05Z] [ssh:Fedora 32] The bits may have been replaced on the origin server, or an attacker may 
INFO[2021-05-14T07:33:05Z] [ssh:Fedora 32] have intercepted the download attempt. 
```

**Comment by prietyc123** [comment]
@anandrkskd there are some real failure on kubernetes 
```
verifying github.com/mikefarah/yaml/v2@v2.4.0/go.mod: checksum mismatch 
ERRO[2021-05-17T04:16:32Z] [ssh:Fedora 32] 	downloaded: h1:RDklbk79AGWmwhnvt/jBztapEOGDOx6ZbXqjP6csGnQ= 
ERRO[2021-05-17T04:16:32Z] [ssh:Fedora 32] 	go.sum:     h1:ahVqZF4n1W4NqwvVnZzC4es67xsW9uR/RRf2RRxieJU= 
ERRO[2021-05-17T04:16:32Z] [ssh:Fedora 32]                              
ERRO[2021-05-17T04:16:32Z] [ssh:Fedora 32] SECURITY ERROR               
ERRO[2021-05-17T04:16:32Z] [ssh:Fedora 32] This download does NOT match an earlier download recorded in go.sum. 
ERRO[2021-05-17T04:16:32Z] [ssh:Fedora 32] The bits may have been replaced on the origin server, or an attacker may 
ERRO[2021-05-17T04:16:32Z] [ssh:Fedora 32] have intercepted the download attempt. 
ERRO[2021-05-17T04:16:32Z] [ssh:Fedora 32]                              
ERRO[2021-05-17T04:16:32Z] [ssh:Fedora 32] For more information, see 'go help module-auth'. 
```

/hold

**Comment by prietyc123** [comment]
> @anandrkskd there are some real failure on kubernetes
> 
> ```
> verifying github.com/mikefarah/yaml/v2@v2.4.0/go.mod: checksum mismatch 
> ERRO[2021-05-17T04:16:32Z] [ssh:Fedora 32] 	downloaded: h1:RDklbk79AGWmwhnvt/jBztapEOGDOx6ZbXqjP6csGnQ= 
> ERRO[2021-05-17T04:16:32Z] [ssh:Fedora 32] 	go.sum:     h1:ahVqZF4n1W4NqwvVnZzC4es67xsW9uR/RRf2RRxieJU= 
> ERRO[2021-05-17T04:16:32Z] [ssh:Fedora 32]                              
> ERRO[2021-05-17T04:16:32Z] [ssh:Fedora 32] SECURITY ERROR               
> ERRO[2021-05-17T04:16:32Z] [ssh:Fedora 32] This download does NOT match an earlier download recorded in go.sum. 
> ERRO[2021-05-17T04:16:32Z] [ssh:Fedora 32] The bits may have been replaced on the origin server, or an attacker may 
> ERRO[2021-05-17T04:16:32Z] [ssh:Fedora 32] have intercepted the download attempt. 
> ERRO[2021-05-17T04:16:32Z] [ssh:Fedora 32]                              
> ERRO[2021-05-17T04:16:32Z] [ssh:Fedora 32] For more information, see 'go help module-auth'. 
> ```
> 
> /hold

Issue is not related to this pr. We are facing this issue on main. So unholding the pr.

/hold cancel

**Review by rnapoles-rh — APPROVED** [review]
/lgtm

**Review by valaparthvi — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
