### PR TITLE
Update devfile tests with OCI-based registry

### PR DESCRIPTION
**Pull request by josephca**
**What type of PR is this?**
 /kind cleanup
 
**What does this PR do / why we need it**:
After moving to use OCI-based registry (https://github.com/openshift/odo/pull/4525), devfile tests should be using OCI-based registry as well. 

**Which issue(s) this PR fixes**:

Related issues:
https://github.com/devfile/api/issues/367
https://github.com/openshift/odo/issues/4504
https://github.com/openshift/odo/pull/4525

**PR acceptance criteria**:

- [x] Unit test 

- [x] Integration test 

- [ ] Documentation 

- [x] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:
This PR is for changing test codes.

### CODE REVIEW

**Review by rnapoles-rh — COMMENTED** [review]
@mohammedzee1000  Looks like both:

- https://github.com/odo-devfiles/registry

and 

- https://registry.devfile.io

have the same content, why use different URLs?

**Comment by josephca** [comment]
> @mohammedzee1000 Looks like both:
> 
> * https://registry.stage.devfile.io
> 
> and
> 
> * https://registry.devfile.io
> 
> have the same content, why use different URLs?

@rnapoles-rh 
I intentionally used two registries to test out different test cases against the official OCI-based registry vs. staging registry (contains the latest contents) and also to ensure the availability of the registries. 

Here is the detail : 

- Official registry (https://registry.devfile.io) updated weekly vs. staging registry(https://registry.stage.devfile.io) updated with PR merges. 
- odo registry command test uses the official registry as it doesn't cause much overload on the public registry vs. odo catalog test uses the staging registry to avoid potential overload on the official registry.

**Comment by josephca** [comment]
@GeekArthur - please review. Thanks,

**Comment by girishramnani** [comment]
> > @mohammedzee1000 Looks like both:
> > 
> > * https://registry.stage.devfile.io
> > 
> > and
> > 
> > * https://registry.devfile.io
> > 
> > have the same content, why use different URLs?
> 
> @rnapoles-rh
> I intentionally used two registries to test out different test cases against the official OCI-based registry vs. staging registry (contains the latest contents) and also to ensure the availability of both registries.
> 
> Here is the detail :
> 
> * Official registry (https://registry.devfile.io) updated weekly vs. staging registry(https://registry.stage.devfile.io) updated with PR merges.
> * odo registry command test uses the official registry as it doesn't cause much overload on the public registry vs. odo catalog test uses the staging registry to avoid potential overload on the official registry.

So odo tests would fail if there is breaking changing in the staging registry? wouldn't that block us?

**Comment by prietyc123** [comment]
> So odo tests would fail if there is breaking changing in the staging registry? wouldn't that block us?

Even I do feel the same. @josephca Currently the breaking changes in Official registry are bothering us more and now it seems like we need to deal with staging one as well, no?

**Comment by josephca** [comment]
> > So odo tests would fail if there is breaking changing in the staging registry? wouldn't that block us?
> 
> Even I do feel the same. @josephca Currently the breaking changes in devfile registry are bothering us more and now it seems like we need to deal with staging one as well, no?

@girishramnani @prietyc123 Thanks for your inputs. 
After discussion with devfile service team, it would be sufficient to test only with staging server. In addition, they will try to get some telemetry data in the future to track usage patterns on the community registry. Therefore, it will be good to use the staging server for testing to avoid polluting the data.

That said, I will update the code to use the staging server only.

**Review by rnapoles-rh — APPROVED** [review]
/lgtm

**Pull request merged**
