### PR TITLE
Updates devfile/library to alpha release 3

### PR DESCRIPTION
**Pull request by maysunfaisal**
**What type of PR is this?**
/kind api-change
/kind cleanup

**What does this PR do / why we need it**:
- This PR updates devfile/library version to [alpha release 3](https://github.com/devfile/library/releases/tag/v1.0.0-alpha.3) and makes the necessary updates
- The new alpha release also utilizes top level variable substitution which is left blank with this PR update

**Which issue(s) this PR fixes**:
N/A

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [ ] Update changelog

- [ ] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:
The PR tests should pass

### CODE REVIEW

**Comment by prietyc123** [comment]
@maysunfaisal There are some compilation error while running `ginkgo tests/integration/project` tests on minikube
```
[ssh:Fedora-32-minikube] make: *** [Makefile:179: test-cmd-project] Error 1 
INFO[2021-05-18T20:48:01Z]                                              
INFO[2021-05-18T20:48:01Z] [ssh:Fedora-32-minikube] !!!run failed, skipping!!! 
INFO[2021-05-18T20:48:01Z]                                              
INFO[2021-05-18T20:48:01Z] 2021/05/18 20:47:54 : failed due to err Failed the test, see logs above ^ 
INFO[2021-05-18T20:48:01Z] {"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2021-05-18T20:47:54Z"} 
INFO[2021-05-18T20:48:01Z] error: failed to execute wrapped command: exit status 1 
INFO[2021-05-18T20:48:01Z]   [...]
ERRO[2021-05-18T20:48:01Z] Container test exited with code 1, reason Error 
ERRO[2021-05-18T20:48:01Z] ---                                          
ERRO[2021-05-18T20:48:01Z] github.com/devfile/library@v1.0.0-alpha.2/pkg/devfile/parser/data/v2/common/command_helper.go:19:12: dc.VscodeTask undefined (type v1alpha2.Command has no field or method VscodeTask) 
ERRO[2021-05-18T20:48:01Z] [ssh:Fedora-32-minikube]                     
ERRO[2021-05-18T20:48:01Z] [ssh:Fedora-32-minikube] Ginkgo ran 1 suite in 2.41118345s 
ERRO[2021-05-18T20:48:01Z] [ssh:Fedora-32-minikube] Test Suite Failed   
```
This failure is on multiple lines.
```
ginkgo  -randomizeAllSpecs -slowSpecThreshold=120 -timeout 14400s -nodes=1 -focus="odo project command tests" tests/integration/project/

[ssh:Fedora-32-minikube] Failed to compile project:

[ssh:Fedora-32-minikube] 

[ssh:Fedora-32-minikube] # github.com/devfile/library/pkg/devfile/parser/data/v2/common

[ssh:Fedora-32-minikube] ../../go/pkg/mod/github.com/devfile/library@v1.0.0-alpha.2/pkg/devfile/parser/data/v2/common/command_helper.go:16:9: dc.VscodeLaunch undefined (type v1alpha2.Command has no field or method VscodeLaunch)

[ssh:Fedora-32-minikube] ../../go/pkg/mod/github.com/devfile/library@v1.0.0-alpha.2/pkg/devfile/parser/data/v2/common/command_helper.go:17:12: dc.VscodeLaunch undefined (type v1alpha2.Command has no field or method VscodeLaunch)

[ssh:Fedora-32-minikube] ../../go/pkg/mod/github.com/devfile/library@v1.0.0-alpha.2/pkg/devfile/parser/data/v2/common/command_helper.go:18:9: dc.VscodeTask undefined (type v1alpha2.Command has no field or method VscodeTask)

[ssh:Fedora-32-minikube] ../../go/pkg/mod/github.com/devfile/library@v1.0.0-alpha.2/pkg/devfile/parser/data/v2/common/command_helper.go:19:12: dc.VscodeTask undefined (type v1alpha2.Command has no field or method VscodeTask)
```
Holding this pr until it gets fixed. Please feel free to unhold it once you are done.

/hold

**Comment by maysunfaisal** [comment]
@prietyc123 I am able to make locally without any issues:
```
Maysuns-MacBook-Pro:odo maysun$ make bin
go build -mod=vendor -ldflags="-X github.com/openshift/odo/pkg/version.GITCOMMIT=84bcf1c4b" cmd/odo/odo.go


Maysuns-MacBook-Pro:odo maysun$ make test-cmd-project
ginkgo  -randomizeAllSpecs -slowSpecThreshold=120 -timeout 14400s -nodes=1 -focus="odo project command tests" tests/integration/project/
Running Suite: Project Suite
============================
Random Seed: 1621444518 - Will randomize all specs
Will run 7 of 7 specs

•••••••
JUnit report was created: /Users/maysun/go/src/github.com/openshift/odo/tests/reports/junit_2021-5-19_13-15-27_1.xml

Ran 7 of 7 Specs in 75.920 seconds
SUCCESS! -- 7 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS

Ginkgo ran 1 suite in 1m25.080496504s
Test Suite Passed
```

I noticed the test err is actually not reflecting my PR change, I have updated the go.mod to  `github.com/devfile/library v1.0.0-alpha.3` but the minikube test is still picking up `devfile/library@v1.0.0-alpha.2` version which is weird.

I have noticed that both [ci/prow/v4.7-integration-e2e](https://github.com/openshift/release/blob/master/ci-operator/config/openshift/odo/openshift-odo-main__v4.7.yaml#L33)  & [ci/prow/psi-kubernetes-integration-e2e](https://github.com/openshift/release/blob/master/ci-operator/config/openshift/odo/openshift-odo-main__psi.yaml#L15) run the same test `make test-cmd-project` but it seems to be failing on minikube 🤔

**Comment by kadel** [comment]
@maysunfaisal sorry I totally missed this PR :-/ 
Yesterday, I've opened PR that updates to the latest master revision of the devfile library including  handling warning https://github.com/openshift/odo/pull/4769

**Comment by maysunfaisal** [comment]
closing as there is https://github.com/openshift/odo/pull/4769 which has reviews

**Pull request closed without merging**
