### PR TITLE
2669 devfile parser refactor and odo specific validations

### LINKED ISSUE #2669: Consider moving the Devfile Parser to the top level and update the Parse function also validate
## Which functionality do you think we should add?

We can consider moving pkg/devfile/parser and pkg/devfile/versions to a top-level folder since it seems like it could be moved to a separate repo altogether and so should be more decoupled from the odo code. Maybe pkg/parser or pkg/devfile-parser so it will make it easier to separate it out later?

https://github.com/openshift/odo/pull/2629 removed some validation code. Maybe we can add it back to a new package like pkg/devfile/validation that lives within the odo code. I'm thinking for odo we'd want the pkg/devfile/Parse function to still validate but just call the validation from an odo package.

This is based on a previous comment: https://github.com/openshift/odo/pull/2629#discussion_r385865159

/kind user-story
/area devfile
/remove kind user-story

### PR DESCRIPTION
**Pull request by kanchwala-yusuf**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:

> /kind feature

**What does does this PR do / why we need it**:
The devfile parser was split into multiple packages (_viz._ `parser`, `versions`). This PR creates a single unified package for the devfile parser `pkg/devfile/parser`. Some sub packages have been moved and renamed as follows:
1. `pkg/devfile/parser` -> `pkg/devfile/parser/context` (_renamed to `context` as this package deals with devfile context information_)
2. `pkg/devfile/versions` -> `pkg/devfile/parser/data` (_renamed to `data` as this package deals with data present in devfiles_)

As a part of this PR, odo specific validations have been added into `pkg/devfile/validate`

Now, the devfile parser package `pkg/devfile/parser` is completely generic and deals with vanilla devfiles. The parser can be independently moved into it's own individual package, if needed.

**Which issue(s) this PR fixes**:

Fixes #2669 

**How to test changes / Special notes to the reviewer**:
All the devfile functionalities/features should work seamlessly.

### CODE REVIEW

**Comment by amitkrout** [comment]
This just a code refactor, so no extra test will be added i guess

**Comment by girishramnani** [comment]
Why was validation logic for projects and commands removed?

**Comment by adisky** [comment]
> Why was validation logic for projects and commands removed?

@girishramnani `commands` we can specify be flags also `--devbuild` `--devrun`, so it may not present in devfile. and i do not remember exact reason for projects but as discussed with @kadel projects are also optional

**Comment by girishramnani** [comment]
> > Why was validation logic for projects and commands removed?
> 
> @girishramnani `commands` we can specify with flags also `--devbuild` `--devrun`, so it may not present in devfile. and i do not remember exact reason for projects but as discussed with @kadel projects are also optional

so wouldn't the `commands` validation translate into having either `devbuild` or `devrun`?

**Comment by adisky** [comment]
> > > Why was validation logic for projects and commands removed?
> > 
> > 
> > @girishramnani `commands` we can specify with flags also `--devbuild` `--devrun`, so it may not present in devfile. and i do not remember exact reason for projects but as discussed with @kadel projects are also optional
> 
> so wouldn't the `commands` validation translate into having either `devbuild` or `devrun`?

It is devfile yaml validation, ``devbuild` and `devrun` command are optional there, but if commands are specified then we could validate if they are supported or not.

build and run commands also needs be updated here
https://github.com/openshift/odo/blob/master/tests/examples/source/devfiles/nodejs/devfile.yaml

More validations we could add as a followup PR, Since we currently do not have common point for validation merged, we are adding validation at random places. This PR also contains some package restructuring, so it needs frequent rebase as other devfile PR's are merged.

**Comment by johnmcollier** [comment]
Unit tests are pretty consistently failing with this error?
```
/adapter_test.go:490:14: undeclared name: devfile make[1]: Leaving directory `/go/src/github.com/openshift/odo' make[1]: *** [vet] Error 2 make: *** [openshiftci-presubmit-unittests] Error 2 
```

**Comment by cdrage** [comment]
It's CI going nuts @johnmcollier it'll eventually pass :laughing:

**Comment by girishramnani** [comment]
@adisky unit tests seems to fail which is odd. As travis CI passes and that runs unit tests

**Comment by girishramnani** [comment]
There seems to be an error in the unit tests
```
pkg/devfile/adapters/kubernetes/component/adapter_test.go:572:14: undeclared name: devfile make[1]: *** [vet] 
```

**Comment by adisky** [comment]
> @adisky unit tests seems to fail which is odd. As travis CI passes and that runs unit tests

I think packages needs to updated in files for other PR merged just before it,

**Pull request merged**
