### PR TITLE
Update some recursive logs to V(5)

### PR DESCRIPTION
**Pull request by adisky**
**What type of PR is this?**
 
/kind code-refactoring

**What does does this PR do / why we need it**:
These are some recursive logs related to sync and file indexer.  They are printed continuously  at V(4)  while `odo push`, making it difficult to check other debug logs. They are trace kind of logs, should be at V(5)

**Which issue(s) this PR fixes**:

Fixes #?

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by amitkrout** [comment]
CI is happy ;) 
/lgtm

**Comment by cdrage** [comment]
We need to have a discussion with regards to `V(5)`, this should not have been merged without an update to documentation.

**Comment by cdrage** [comment]
Reverting the changes for now, as people debugging will suddenly find that the debugging logs have disappeared ..

**Pull request merged**
