### PR TITLE
changed DEBUG_MODE to DEV_MODE in odo-debug design doc

### PR DESCRIPTION
**Pull request by girishramnani**
**What kind of PR is this?**

/kind code-refactoring
/kind enhancement

**What does does this PR do / why we need it**:
After https://github.com/openshift/odo-init-image/pull/45 is merged. we will be using `DEV_MODE` to control debug mode so we need to change the docs to reflect that information
**Which issue(s) this PR fixes**:

Partly https://github.com/openshift/odo/issues/2409

**How to test changes / Special notes to the reviewer**:
Doc change

### CODE REVIEW

**Comment by mik-dass** [comment]
/hold
till https://github.com/openshift/odo-init-image/pull/45 is merged

**Comment by girishramnani** [comment]
https://github.com/openshift/odo-init-image/pull/45 has been merged.

**Pull request merged**
