### PR TITLE
Remove cmd helper functions

### LINKED ISSUE #4517: convert cmd helpers to new CmdRunner
/kind feature

## Which functionality do you think we should add?
Currently we have alot of functions in https://github.com/openshift/odo/blob/master/tests/helper/helper_run.go which can be de-duplicated ( they have a lot of common code ). There is some code already that does that using https://github.com/openshift/odo/blob/master/tests/helper/helper_cmd_wrapper.go 

The ideal target functions would be -
- CmdShouldRunAndTerminate
- CmdShouldFail
- CmdShouldFailWithRetry
- CmdShouldRunWithTimeout

## Why is this needed?
If the chaining design pattern is used then the current helper code can be improved significantly, This would allow for better maintainability and extensibility

## Sub Issues (tasks)
- [x] Createing new functions https://github.com/openshift/odo/issues/4694
- [ ] Updating test to use new functions - issue to be created

### PR DESCRIPTION
**Pull request by anandrkskd**
**What type of PR is this?**

/kind code-refactoring

**What does this PR do / why we need it**:
This PR will remove old helper functions mentioned below
- CmdShouldRunAndTerminate
- CmdShouldFail
- CmdShouldPass
- CmdShouldFailWithRetry
- CmdShouldRunWithTimeout

**Which issue(s) this PR fixes**:

Fixes #4517

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [ ] Update changelog

- [x] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by dharmit** [comment]
@anandrkskd can you PTAL if the test failures are related to this PR? I'm inclined to approve & lgtm this but don't want to create an infinite loop.

**Comment by anandrkskd** [comment]
> @anandrkskd can you PTAL if the test failures are related to this PR? I'm inclined to approve & lgtm this but don't want to create an infinite loop.

Yeah I am looked into the previous one there was a typo already updated it. looking into k8s failure.

**Comment by anandrkskd** [comment]
prow failure on v4.7-integration-e2e
/test v4.7-integration-e2e

**Pull request merged**
