### PR TITLE
Alpha and move Operator Hub out of experimental

### LINKED ISSUE #3595: Move Operator Hub integration out of Experimental mode
Currently, Operator Hub specific commands are working when Experimental mode is enabled. Move these out of Experimental mode and make sure these commands work in tandem with Service Catalog (when it's enabled).

/area service-operators
/area service
/assign

### PR DESCRIPTION
**Pull request by dharmit**
### This PR is rebased on top of @cdrage's work on alpha release under [alpha-testing branch](https://github.com/cdrage/odo/tree/alpha-testing).
------
**What type of PR is this?**
/kind feature
/kind code-refactoring

**What does does this PR do / why we need it**:
 It moves Operator Hub integration out of experimental mode. We need it for v2.

**Which issue(s) this PR fixes**:

Fixes #3595 

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [x] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

* Tests should pass.
* If Operators are supported by the cluster (4.x), we ignore service catalog altogether.
* If user's working with 3.x cluster, odo should support Service Catalog (if enabled by the user).

### CODE REVIEW

**Comment by prietyc123** [comment]
@dharmit I have gone through the test failures and it seems we have common `odo link` function for component and services. I have observed the tests are failing with `odo link` for ex here - https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_odo/3922/pull-ci-openshift-odo-master-v4.5-integration-e2e/1303916074835644416#1:build-log.txt%3A2213 . So, can you please enable verbose mode of link command for detailed failure logs to get better clarity. Although I suspect the failure might be in deployment config which gets created while linking the component or services. So, could you please describe that too. For ex- `oc describe dc <dc-name>` in the teardown `AfterEach` or `JustAfterEach` step.

**Comment by dharmit** [comment]
>  it seems we have common `odo link` function for component and services

That's right. `odo link` command figures out if the user wants to link the component to a service or a component.

>  tests are failing with `odo link` for ex here - https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_odo/3922/pull-ci-openshift-odo-master-v4.5-integration-e2e/1303916074835644416#1:build-log.txt%3A2213 .

The reason for error in case of above mentioned logs is: `[odo]  ✗  Neither a service nor a component named backend could be located. Please create one of the two before attempting to use 'odo link'`

<details>

<summary> log excerpt </summary>

``` [odo] I0910 06:13:37.756049   28914 common_link.go:155] Unable to determine if backend is a service. This most likely means the service catalog is not installed. Proceesing to only use components
[odo] I0910 06:13:37.756084   28914 occlient.go:2777] Getting DeploymentConfig: backend-app
[odo]  ✗  Neither a service nor a component named backend could be located. Please create one of the two before attempting to use 'odo link'
Deleting dir: /tmp/574490741
Deleting dir: /tmp/594983248
Deleting project: lrqmgayvvu
Running odo with args [odo project delete lrqmgayvvu -f]
[odo] I0910 06:13:38.010176   28936 util.go:730] HTTPGetRequest: https://raw.githubusercontent.com/openshift/odo/master/build/VERSION
[odo] I0910 06:13:38.010349   28936 util.go:751] Response will be cached in /tmp/odohttpcache for 1h0m0s
[odo] I0910 06:13:38.010490   28936 util.go:764] Cached response used.
[odo]  ⚠  Warning! Projects are deleted from the cluster asynchronously. Odo does its best to delete the project. Due to multi-tenant clusters, the project may still exist on a different node.
[odo] I0910 06:13:38.131001   28936 odo.go:72] Could not get the latest release information in time. Never mind, exiting gracefully :)
[odo]  ✓  Deleted project : lrqmgayvvu
Deleting dir: /tmp/126518766
• Failure [129.044 seconds]
odo link and unlink command tests
/go/src/github.com/openshift/odo/tests/integration/cmd_link_unlink_test.go:14
  When handling link/unlink between components
  /go/src/github.com/openshift/odo/tests/integration/cmd_link_unlink_test.go:77
    should link the frontend application to the backend and then unlink successfully [It]
```

</details>

However, when I run the same test locally, it fails with a different error and it's likely more related to the network than with odo. I say this because I'm running tests on a VPN network and the CRC instance is installed in North America while I am trying from India.  

<details>

<summary> Note the timeout. It has succeeded in linking the components! </summary>

```
error while requesting: Get http://frontend-8080-app-vbqmxrhzqx.apps-crc.testing: dial tcp: lookup frontend-8080-app-vbqmxrhzqx.apps-crc.testing on 127.0.0.1:53: read udp 127.0.0.1:39404->127.0.0.1:53: i/o timeout
try 17 of 20
error while requesting: Get http://frontend-8080-app-vbqmxrhzqx.apps-crc.testing: dial tcp: lookup frontend-8080-app-vbqmxrhzqx.apps-crc.testing on 127.0.0.1:53: read udp 127.0.0.1:48012->127.0.0.1:53: i/o timeout
try 18 of 20
error while requesting: Get http://frontend-8080-app-vbqmxrhzqx.apps-crc.testing: dial tcp: lookup frontend-8080-app-vbqmxrhzqx.apps-crc.testing on 127.0.0.1:53: read udp 127.0.0.1:47600->127.0.0.1:53: i/o timeout
try 19 of 20
error while requesting: Get http://frontend-8080-app-vbqmxrhzqx.apps-crc.testing: dial tcp: lookup frontend-8080-app-vbqmxrhzqx.apps-crc.testing on 127.0.0.1:53: read udp 127.0.0.1:34867->127.0.0.1:53: i/o timeout
Last output from http://frontend-8080-app-vbqmxrhzqx.apps-crc.testing: 
Deleting dir: /tmp/088080024
Deleting dir: /tmp/455271703
Deleting project: vbqmxrhzqx
Running odo with args [odo project delete vbqmxrhzqx -f]
[odo]  ✓  Deleted project : vbqmxrhzqx
[odo]  ⚠  Warning! Projects are deleted from the cluster asynchronously. Odo does its best to delete the project. Due to multi-tenant clusters, the project may still exist on a different node.
Deleting dir: /tmp/315556573

------------------------------
• Failure [410.258 seconds]
odo link and unlink command tests
/home/dshah/go/src/github.com/openshift/odo/tests/integration/cmd_link_unlink_test.go:14
  When handling link/unlink between components
  /home/dshah/go/src/github.com/openshift/odo/tests/integration/cmd_link_unlink_test.go:77
    should link the frontend application to the backend and then unlink successfully [It]
    /home/dshah/go/src/github.com/openshift/odo/tests/integration/cmd_link_unlink_test.go:86

    Failed after 20 retries. Content in http://frontend-8080-app-vbqmxrhzqx.apps-crc.testing doesn't include 'Hello world from node.js!'.

    /home/dshah/go/src/github.com/openshift/odo/tests/helper/helper_http.go:50

</details>

**Comment by dharmit** [comment]
> So, can you please enable verbose mode of link command for detailed failure logs to get better clarity. Although I suspect the failure might be in deployment config which gets created while linking the component or services. So, could you please describe that too. For ex- `oc describe dc <dc-name>` in the teardown `AfterEach` or `JustAfterEach` step.

The problem is that I'm stuck in rebase loop. As you see, this PR is already out of sync! And I'm not sure if I should rebase on top of the alpha branch or beta branch or something entirely else. I'd request that if you have a machine, can you please try and add these to your local copy and see if you're able to find more info? But, as I said earlier, the linking itself actually works when I try this against CRC cluster. :confused:

**Comment by dharmit** [comment]
Now talking about the failure for the spec: `Wait till frontend dc rollout properly after linking the frontend application to the backend [It]`


<details>

<summary> Here's the log excerpt. </summary>

```
 [odo] I0910 06:31:25.910121    1514 util.go:764] Cached response used.
[odo] I0910 06:31:25.956783    1514 common_link.go:155] Unable to determine if backend is a service. This most likely means the service catalog is not installed. Proceesing to only use components
[odo] I0910 06:31:25.956817    1514 occlient.go:2777] Getting DeploymentConfig: backend-prjnpjf
[odo]  ✗  Neither a service nor a component named backend could be located. Please create one of the two before attempting to use 'odo link'
Deleting dir: /tmp/880096371
Deleting dir: /tmp/635154742
Deleting project: yjxdlswhxd
Running odo with args [odo project delete yjxdlswhxd -f]
[odo] I0910 06:31:26.229556    1537 util.go:730] HTTPGetRequest: https://raw.githubusercontent.com/openshift/odo/master/build/VERSION
[odo] I0910 06:31:26.229722    1537 util.go:751] Response will be cached in /tmp/odohttpcache for 1h0m0s
[odo] I0910 06:31:26.229865    1537 util.go:764] Cached response used.
[odo]  ⚠  Warning! Projects are deleted from the cluster asynchronously. Odo does its best to delete the project. Due to multi-tenant clusters, the project may still exist on a different node.
[odo] I0910 06:31:26.380976    1537 odo.go:72] Could not get the latest release information in time. Never mind, exiting gracefully :)
[odo]  ✓  Deleted project : yjxdlswhxd
Deleting dir: /tmp/688312932
• Failure [147.897 seconds]
odo link and unlink command tests
/go/src/github.com/openshift/odo/tests/integration/cmd_link_unlink_test.go:14
  When handling link/unlink between components
  /go/src/github.com/openshift/odo/tests/integration/cmd_link_unlink_test.go:77
    Wait till frontend dc rollout properly after linking the frontend application to the backend [It]
    /go/src/github.com/openshift/odo/tests/integration/cmd_link_unlink_test.go:114
    No future change is possible.  Bailing out early after 0.314s.
      
    Running odo with args [odo link backend --port 8080 --wait --context /tmp/880096371]
    Expected
        <int>: 1
    to match exit code:
        <int>: 0
    /go/src/github.com/openshift/odo/tests/helper/helper_run.go:34 
```

</details>

But here's the output when I manually run the steps in that spec:

```sh
$ odo link backend --context . --port 8080 --wait
 ✓  Component backend has been successfully linked to the component frontend

The below secret environment variables were added to the 'frontend' component:

· COMPONENT_BACKEND_HOST
· COMPONENT_BACKEND_PORT

You can now access the environment variables from within the component pod, for example:
$COMPONENT_BACKEND_HOST is now available as a variable within component frontend
 ✓  Waiting for component to redeploy [16s]
 ✓  Waiting for component to start [19s]
```

And here's the error when I run the spec. Please note that it succeeds in creating the link!

<details>

<summary> test log excerpt </summary>

```
[odo]  •  Building component  ...                                                                                                                                                             
 ✓  Building component [26s]                                                                                                                                                                  
[odo]  ✓  Changes successfully pushed to component                                                                                                                                            
Running odo with args [odo link backend --port 8080 --wait --context /tmp/069334073]                                                                                                          
[odo]  ✓  Component backend has been successfully linked to the component frontend                                                                                                            
[odo]                                                                                                                                                                                         
[odo] The below secret environment variables were added to the 'frontend' component:                                                                                                          
[odo]                                                                                                                                                                                         
[odo] · COMPONENT_BACKEND_HOST                                                                                                                                                                
[odo] · COMPONENT_BACKEND_PORT                                                                                                                                                                
[odo]                                                                                                                                                                                         
[odo] You can now access the environment variables from within the component pod, for example:                                                                                                
[odo] $COMPONENT_BACKEND_HOST is now available as a variable within component frontend
....
....
....
error while requesting: Get http://frontend-8080-xqulxtp-ivzysxqgir.apps-crc.testing: dial tcp: lookup frontend-8080-xqulxtp-ivzysxqgir.apps-crc.testing on 127.0.0.1:53: read udp 127.0.0.1:5
5037->127.0.0.1:53: i/o timeout
Last output from http://frontend-8080-xqulxtp-ivzysxqgir.apps-crc.testing: 
Deleting dir: /tmp/069334073
Deleting dir: /tmp/288588868
Deleting project: ivzysxqgir
Running odo with args [odo project delete ivzysxqgir -f]
[odo]  ✓  Deleted project : ivzysxqgir
[odo]  ⚠  Warning! Projects are deleted from the cluster asynchronously. Odo does its best to delete the project. Due to multi-tenant clusters, the project may still exist on a different nod
e.
Deleting dir: /tmp/382389186

------------------------------
• Failure [396.153 seconds]
odo link and unlink command tests
/home/dshah/go/src/github.com/openshift/odo/tests/integration/cmd_link_unlink_test.go:14
  When handling link/unlink between components
  /home/dshah/go/src/github.com/openshift/odo/tests/integration/cmd_link_unlink_test.go:77
    Wait till frontend dc rollout properly after linking the frontend application to the backend [It]
    /home/dshah/go/src/github.com/openshift/odo/tests/integration/cmd_link_unlink_test.go:114

    Failed after 20 retries. Content in http://frontend-8080-xqulxtp-ivzysxqgir.apps-crc.testing doesn't include 'Hello world from node.js!'.

    /home/dshah/go/src/github.com/openshift/odo/tests/helper/helper_http.go:50
------------------------------
S

Summarizing 1 Failure:

[Fail] odo link and unlink command tests When handling link/unlink between components [It] Wait till frontend dc rollout properly after linking the frontend application to the backend 
/home/dshah/go/src/github.com/openshift/odo/tests/helper/helper_http.go:50

Ran 1 of 186 Specs in 396.153 seconds
FAIL! -- 0 Passed | 1 Failed | 0 Pending | 185 Skipped
--- FAIL: TestIntegration (396.17s)
```

</details>

**Comment by dharmit** [comment]
And here's the third test spec that failed. It runs just fine.

```
$ ginkgo --focus "should successfully delete component after linked component is deleted" tests/integration/                                                                                  
Running Suite: Integration Suite                                                                                                                                                              
================================                                                                                                                                                              
Random Seed: 1599815310                                                                                                                                                                       
Will run 1 of 186 specs                                                                                                                                                                       
                                                                                                                                                                                              
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS                                                              
------------------------------                                                                                                                                                                
• [SLOW TEST:157.616 seconds]                                                                                                                                                                 
odo link and unlink command tests                                                                                                                                                             
/home/dshah/go/src/github.com/openshift/odo/tests/integration/cmd_link_unlink_test.go:14                                                                                                      
  When handling link/unlink between components                                                                                                                                                
  /home/dshah/go/src/github.com/openshift/odo/tests/integration/cmd_link_unlink_test.go:77                                                                                                    
    should successfully delete component after linked component is deleted                                                                                                                    
    /home/dshah/go/src/github.com/openshift/odo/tests/integration/cmd_link_unlink_test.go:139                                                                                                 
------------------------------                                                                                                                                                                
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS                                                                                                                                     
Ran 1 of 186 Specs in 157.618 seconds                                                                                                                                                         
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 185 Skipped                                                                                                                                     
PASS                                                                                                                                                                                          
                                                                                                                                                                                              
Ginkgo ran 1 suite in 2m38.927949942s                                                                                                                                                         
Test Suite Passed                                                                                                                                                                             
                                                                                                                                                                                              
$ ginkgo --focus "should successfully delete component after linked component is deleted" tests/integration/
Running Suite: Integration Suite
================================
Random Seed: 1599815499
Will run 1 of 186 specs

SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
------------------------------
• [SLOW TEST:139.925 seconds]
odo link and unlink command tests
/home/dshah/go/src/github.com/openshift/odo/tests/integration/cmd_link_unlink_test.go:14
  When handling link/unlink between components
  /home/dshah/go/src/github.com/openshift/odo/tests/integration/cmd_link_unlink_test.go:77
    should successfully delete component after linked component is deleted
    /home/dshah/go/src/github.com/openshift/odo/tests/integration/cmd_link_unlink_test.go:139
------------------------------
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
Ran 1 of 186 Specs in 139.928 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 185 Skipped
PASS
```

**Comment by dharmit** [comment]
And here's the output from running all tests in `tests/integration/cmd_link_unlink_test.go` on my local system with CRC. All the tests passed!

```
ginkgo --focus "odo link and unlink command tests" tests/integration/
Running Suite: Integration Suite
================================
Random Seed: 1599816815
Will run 6 of 186 specs

SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS••
------------------------------
• [SLOW TEST:80.136 seconds]
odo link and unlink command tests
/home/dshah/go/src/github.com/openshift/odo/tests/integration/cmd_link_unlink_test.go:14
  When link between components using wrong port
  /home/dshah/go/src/github.com/openshift/odo/tests/integration/cmd_link_unlink_test.go:56
    should fail
    /home/dshah/go/src/github.com/openshift/odo/tests/integration/cmd_link_unlink_test.go:65
------------------------------
• [SLOW TEST:199.668 seconds]
odo link and unlink command tests
/home/dshah/go/src/github.com/openshift/odo/tests/integration/cmd_link_unlink_test.go:14
  When handling link/unlink between components
  /home/dshah/go/src/github.com/openshift/odo/tests/integration/cmd_link_unlink_test.go:77
    should link the frontend application to the backend and then unlink successfully
    /home/dshah/go/src/github.com/openshift/odo/tests/integration/cmd_link_unlink_test.go:86
------------------------------
• [SLOW TEST:185.333 seconds]
odo link and unlink command tests
/home/dshah/go/src/github.com/openshift/odo/tests/integration/cmd_link_unlink_test.go:14
  When handling link/unlink between components
  /home/dshah/go/src/github.com/openshift/odo/tests/integration/cmd_link_unlink_test.go:77
    Wait till frontend dc rollout properly after linking the frontend application to the backend
    /home/dshah/go/src/github.com/openshift/odo/tests/integration/cmd_link_unlink_test.go:114
------------------------------
• [SLOW TEST:51.572 seconds]
odo link and unlink command tests
/home/dshah/go/src/github.com/openshift/odo/tests/integration/cmd_link_unlink_test.go:14
  When handling link/unlink between components
  /home/dshah/go/src/github.com/openshift/odo/tests/integration/cmd_link_unlink_test.go:77
    should successfully delete component after linked component is deleted
    /home/dshah/go/src/github.com/openshift/odo/tests/integration/cmd_link_unlink_test.go:139
------------------------------
SSSSSSSSSSSSSSSSSSSSSSS
Ran 6 of 186 Specs in 519.059 seconds
SUCCESS! -- 6 Passed | 0 Failed | 0 Pending | 180 Skipped
PASS

Ginkgo ran 1 suite in 8m41.291223823s
Test Suite Passed
```

**Comment by girishramnani** [comment]
Conflicts Conflicts

**Comment by dharmit** [comment]
> Conflicts Conflicts

That's because I've lost the track of which branch to rebase stuff agains! Should I rebase against alpha branch (gh.com/cdrage/alpha-testing) or the beta branch (https://github.com/openshift/odo/tree/beta). At the time of writing this, it's rebasd on top of alpha that's available at https://github.com/cdrage/odo/tree/alpha-testing.

**Comment by prietyc123** [comment]
> And here's the output from running all tests in tests/integration/cmd_link_unlink_test.go on my local system with CRC. All the tests passed!

Understood, Can you please enable the verbose mode in the link command itself in the pr. For ex - `odo link backend --context <context> --port <portno> -v 4` through the test script, so that we can get some more information in the CI failure log.

**Comment by dharmit** [comment]
Closing since take care by #3938.

/close

**Pull request closed without merging**
