### PR TITLE
[WIP] Adding missing UTs files for later fix

### PR DESCRIPTION
**Pull request by amitkrout**
Will update the description later after discussing with @girishramnani

### CODE REVIEW

**Comment by amitkrout** [comment]
looks better now
```
$ make test-coverage
./scripts/generate-coverage.sh
?   	github.com/openshift/odo/cmd/cli-doc	[no test files]
?   	github.com/openshift/odo/cmd/odo	[no test files]
ok  	github.com/openshift/odo/pkg/application	1.084s	coverage: 18.4% of statements
ok  	github.com/openshift/odo/pkg/application/labels	1.012s	coverage: 100.0% of statements
ok  	github.com/openshift/odo/pkg/auth	1.256s	coverage: 0.0% of statements [no tests to run]
ok  	github.com/openshift/odo/pkg/catalog	1.087s	coverage: 60.8% of statements
ok  	github.com/openshift/odo/pkg/component	0.046s	coverage: 25.7% of statements
ok  	github.com/openshift/odo/pkg/component/labels	1.011s	coverage: 100.0% of statements
ok  	github.com/openshift/odo/pkg/config	1.046s	coverage: 51.9% of statements
ok  	github.com/openshift/odo/pkg/debug	1.076s	coverage: 51.9% of statements
ok  	github.com/openshift/odo/pkg/devfile	1.022s	coverage: 43.8% of statements
ok  	github.com/openshift/odo/pkg/devfile/adapters	1.035s	coverage: 15.4% of statements
ok  	github.com/openshift/odo/pkg/devfile/adapters/common	1.022s	coverage: 100.0% of statements
?   	github.com/openshift/odo/pkg/devfile/adapters/kubernetes	[no test files]
ok  	github.com/openshift/odo/pkg/devfile/adapters/kubernetes/component	1.046s	coverage: 37.8% of statements
ok  	github.com/openshift/odo/pkg/devfile/adapters/kubernetes/storage	1.040s	coverage: 66.7% of statements
ok  	github.com/openshift/odo/pkg/devfile/adapters/kubernetes/utils	1.034s	coverage: 0.0% of statements [no tests to run]
ok  	github.com/openshift/odo/pkg/devfile/parser	1.041s	coverage: 60.0% of statements
ok  	github.com/openshift/odo/pkg/devfile/versions	1.012s	coverage: 100.0% of statements
ok  	github.com/openshift/odo/pkg/devfile/versions/1.0.0	1.009s	coverage: 0.0% of statements [no tests to run]
?   	github.com/openshift/odo/pkg/devfile/versions/common	[no test files]
ok  	github.com/openshift/odo/pkg/envinfo	1.023s	coverage: 67.0% of statements
ok  	github.com/openshift/odo/pkg/kclient	1.047s	coverage: 45.7% of statements
ok  	github.com/openshift/odo/pkg/lclient	1.025s	coverage: 57.4% of statements
ok  	github.com/openshift/odo/pkg/log	1.011s	coverage: 0.0% of statements [no tests to run]
ok  	github.com/openshift/odo/pkg/log/fidget	1.010s	coverage: 0.0% of statements [no tests to run]
ok  	github.com/openshift/odo/pkg/machineoutput	1.016s	coverage: 0.0% of statements [no tests to run]
ok  	github.com/openshift/odo/pkg/notify	1.011s	coverage: 0.0% of statements [no tests to run]
ok  	github.com/openshift/odo/pkg/occlient	6.157s	coverage: 56.5% of statements
ok  	github.com/openshift/odo/pkg/odo/cli	1.271s	coverage: 0.0% of statements [no tests to run]
ok  	github.com/openshift/odo/pkg/odo/cli/application	1.077s	coverage: 0.0% of statements [no tests to run]
ok  	github.com/openshift/odo/pkg/odo/cli/catalog	1.072s	coverage: 0.0% of statements [no tests to run]
ok  	github.com/openshift/odo/pkg/odo/cli/catalog/describe	1.073s	coverage: 0.0% of statements [no tests to run]
ok  	github.com/openshift/odo/pkg/odo/cli/catalog/list	1.077s	coverage: 0.0% of statements [no tests to run]
ok  	github.com/openshift/odo/pkg/odo/cli/catalog/search	1.076s	coverage: 0.0% of statements [no tests to run]
ok  	github.com/openshift/odo/pkg/odo/cli/catalog/util	1.067s	coverage: 36.4% of statements
ok  	github.com/openshift/odo/pkg/odo/cli/component	1.078s	coverage: 0.0% of statements [no tests to run]
ok  	github.com/openshift/odo/pkg/odo/cli/component/ui	1.077s	coverage: 0.0% of statements [no tests to run]
ok  	github.com/openshift/odo/pkg/odo/cli/config	1.071s	coverage: 0.0% of statements [no tests to run]
ok  	github.com/openshift/odo/pkg/odo/cli/debug	1.078s	coverage: 0.0% of statements [no tests to run]
ok  	github.com/openshift/odo/pkg/odo/cli/login	1.268s	coverage: 0.0% of statements [no tests to run]
ok  	github.com/openshift/odo/pkg/odo/cli/logout	1.077s	coverage: 0.0% of statements [no tests to run]
ok  	github.com/openshift/odo/pkg/odo/cli/preference	1.080s	coverage: 0.0% of statements [no tests to run]
ok  	github.com/openshift/odo/pkg/odo/cli/project	1.075s	coverage: 0.0% of statements [no tests to run]
ok  	github.com/openshift/odo/pkg/odo/cli/service	1.088s	coverage: 15.0% of statements
ok  	github.com/openshift/odo/pkg/odo/cli/service/ui	1.078s	coverage: 41.7% of statements
ok  	github.com/openshift/odo/pkg/odo/cli/storage	1.075s	coverage: 3.9% of statements
ok  	github.com/openshift/odo/pkg/odo/cli/ui	1.017s	coverage: 0.0% of statements [no tests to run]
ok  	github.com/openshift/odo/pkg/odo/cli/url	1.080s	coverage: 0.0% of statements [no tests to run]
ok  	github.com/openshift/odo/pkg/odo/cli/utils	1.078s	coverage: 5.3% of statements
ok  	github.com/openshift/odo/pkg/odo/cli/version	1.072s	coverage: 0.0% of statements [no tests to run]
?   	github.com/openshift/odo/pkg/odo/genericclioptions	[no test files]
ok  	github.com/openshift/odo/pkg/odo/util	1.065s	coverage: 1.1% of statements
ok  	github.com/openshift/odo/pkg/odo/util/completion	1.094s	coverage: 38.3% of statements
ok  	github.com/openshift/odo/pkg/odo/util/experimental	1.021s	coverage: 88.9% of statements
ok  	github.com/openshift/odo/pkg/odo/util/pushtarget	1.026s	coverage: 83.3% of statements
ok  	github.com/openshift/odo/pkg/odo/util/validation	1.023s	coverage: 84.3% of statements
ok  	github.com/openshift/odo/pkg/preference	1.034s	coverage: 70.9% of statements
ok  	github.com/openshift/odo/pkg/project	1.070s	coverage: 59.5% of statements
ok  	github.com/openshift/odo/pkg/secret	1.069s	coverage: 94.4% of statements
ok  	github.com/openshift/odo/pkg/service	1.077s	coverage: 75.7% of statements
ok  	github.com/openshift/odo/pkg/storage	1.093s	coverage: 52.7% of statements
ok  	github.com/openshift/odo/pkg/storage/labels	1.011s	coverage: 100.0% of statements
?   	github.com/openshift/odo/pkg/sync	[no test files]
ok  	github.com/openshift/odo/pkg/testingutil	1.022s	coverage: 16.0% of statements
?   	github.com/openshift/odo/pkg/testingutil/filesystem	[no test files]
ok  	github.com/openshift/odo/pkg/url	1.071s	coverage: 40.5% of statements
ok  	github.com/openshift/odo/pkg/url/labels	1.010s	coverage: 100.0% of statements
ok  	github.com/openshift/odo/pkg/util	1.058s	coverage: 50.6% of statements
?   	github.com/openshift/odo/pkg/version	[no test files]
ok  	github.com/openshift/odo/pkg/watch	27.161s	coverage: 81.1% of statements
The command "make test-coverage" exited with 0.
```

**Comment by girishramnani** [comment]
Is this good to go @amitkrout or still WIP?

**Comment by kadel** [comment]
ping @amitkrout is this still WIP?

**Comment by prietyc123** [comment]
@amitkrout Are you actively working on this? It's been a long time in the pr pool, If its not that important ATM you can close this pr and later you can reopened with more content and work on it.

**Comment by amitkrout** [comment]
> @amitkrout Are you actively working on this? It's been a long time in the pr pool, If its not that important ATM you can close this pr and later you can reopened with more content and work on it.

You are right, I ma closing this atm

**Pull request closed without merging**
