### PR TITLE
[WIP] Proposal for linking to Helm Charts

### LINKED ISSUE #4368: Proposal for Helm integration with odo
Document a proposal for integrating Helm and odo. This is limited to `odo link` command only. This is a part of the epic #4236.

/area linking
/assign @kadel

### PR DESCRIPTION
**Pull request by kadel**
**What type of PR is this?**

proposal for new feature

/kind feature
/kind documentation
[skip ci]

**What does does this PR do / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #4368

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [ ] I have read the [test guidelines](https://github.com/openshift/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by dharmit** [comment]
@kadel do you plan to continue working on this when we pick it up post 2.3 or do you plan to do things afresh?

**Review by kadel — COMMENTED** [review]
> @kadel do you plan to continue working on this when we pick it up post 2.3 or do you plan to do things afresh?

if we decide to pick this up for 2.3 I will keep be working on this one

**Comment by dharmit** [comment]
Should we still keep this open? It's not a part of 2.4. And also we haven't figured when to pick it up. Can we close it and re-open a new PR when working on this?

**Comment by kadel** [comment]
ok, 
/close

**Pull request closed without merging**
