### PR TITLE
Fixes TestDownloadFile for go 1.14.2

### PR DESCRIPTION
**Pull request by mik-dass**
**What type of PR is this?**

/kind bug

**What does does this PR do / why we need it**:

This PR fixes TestDownloadFile for go version `go version go1.14.2 linux/amd64` by removing `""` from the expected error string.

**Which issue(s) this PR fixes**:

Fixes https://github.com/openshift/odo/issues/3433

**How to test changes / Special notes to the reviewer**:

make test should pass on go 1.14.2

### CODE REVIEW

**Comment by amitkrout** [comment]
@mik-dass Currently our odo release bits build on go 1.12 due to certain constraint in our internal build environment, so make sure that your change should not bring any last moment release failure surprises.

/hold

**Comment by mik-dass** [comment]
> @mik-dass Currently our odo release bits build on go 1.12 due to certain constraint in our internal build environment, so make sure that your change should not bring any last moment release failure surprises.

Even our travis builds use 1.12+ and the tests have passed on travis.

**Comment by amitkrout** [comment]
> > @mik-dass Currently our odo release bits build on go 1.12 due to certain constraint in our internal build environment, so make sure that your change should not bring any last moment release failure surprises.
> 
> Even our travis builds use 1.12+ and the tests have passed on travis.

On Travis the exact go version is ```go version go1.12.17 linux/amd64``` (https://travis-ci.com/github/openshift/odo/jobs/353970162#L193). @mohammedzee1000 can you please confirm the go version we use in our build env.

By seeing the go version in travis, i guess your changes will work on the version we use in brew build but for double sure can you please test your change on the build env go version once @mohammedzee1000 confirms.

**Comment by mohammedzee1000** [comment]
@amitkrout currently it is 1.12 although new build env does provide us with go 1.13 so we should be moving to that in the near future.

I don't see any problems here as it does not seem to effect anything current. `Get` must no longer be present in error message i 1.14 and not having that in our check is fine as the rest of it is present. So this change is backward compatible

**Comment by kadel** [comment]
> @mik-dass Currently our odo release bits build on go 1.12 due to certain constraint in our internal build environment, so make sure that your change should not bring any last moment release failure surprises.
> 
> /hold

Why put this PR on hold? This doesn't change the minimal required Go version. 

/approve
/lgtm

**Comment by kadel** [comment]
/retest
```
level=fatal msg="failed to fetch Common Manifests: failed to fetch dependency of \"Common Manifests\": failed to generate asset \"DNS Config\": getting public zone for \"origin-ci-int-aws.dev.rhcloud.com\": listing hosted zones: Throttling: Rate exceeded\n\tstatus code: 400, request id: 35be24b2-8482-4b1d-9632-92230d20af89"
```

**Comment by amitkrout** [comment]
> > @mik-dass Currently our odo release bits build on go 1.12 due to certain constraint in our internal build environment, so make sure that your change should not bring any last moment release failure surprises.
> > /hold
> 
> Why put this PR on hold? This doesn't change the minimal required Go version.

TBH i did not see the code change for it. When i see the pr title like updating something that will be compiled on go 1.14.0, which reminds me the last time failure on our internal release env having go 1.12.0. So i though instead of reviewing the code at first place, better to get confirmation from @mohammedzee1000 if this is doable.

**Comment by mik-dass** [comment]
The commit https://github.com/openshift/odo/pull/3291/commits/5ec8274b48878a635fb1d7361efa32fe2049965e in https://github.com/openshift/odo/pull/3291/ resolved the issue. So this PR is not required anymore.
/close

**Pull request closed without merging**
